### ISSUE TITLE
Updating full clade on hal file

### ISSUE THREAD

**Issue by jdamas13** [ComparativeGenomicsToolkit/cactus#1003]
Hi,

This is not an issue with cactus, just a question that might also be helpful for other users.

I have a 25+ species cactus alignment. 
We just generated new assemblies for 5 of the species I used and a few extra ones.
These new genomes are all in the same clade.

So I am wondering what would you advise as the most effective way of updating the 25+ sps alignment?
Replace/add the genomes one by one or align 5+ new genomes and then replace/upgrade that clade in the 25+ sps alignment?

I generated the 25+ sps alignment using the step-by-step approach so I have cigar, fasta, and hal files for every node of the phylogeny.

Thank you so much in advance!

**Comment by glennhickey** [comment]
I think you definitely want to re-align your clade.  Here's an example of how I added some new dogs to the Zoonomia alignment, which I think resembles your use case (except for the additional addition of a cat) here: 

https://cgl.gi.ucsc.edu/data/cactus/241-mammalian-2020v2.1.README.md

**Comment by jdamas13** [comment]
Thank you so much; I will try that!
