### ISSUE TITLE
Working on highly-fragmented draft assemblies 

### ISSUE THREAD

**Issue by xiaoyezao** [ComparativeGenomicsToolkit/cactus#1025]
Hi Cactus designer,

I am working on a plant genera (13 species) with one reference-level assembly and 12 fragmented draft assemblies (100k-200k scaffolds) and the genomes are highly repetitive (~65%). Do you have any suggestions on genome alignment using Cactus?

Thank you,

Xiaoyezao

**Comment by glennhickey** [comment]
Make sure they are well softmasked with RepeatMasker and/or RepeatModeller.
