### ISSUE TITLE
Rooted tree or unrooted tree?

### ISSUE THREAD

**Issue by xiaoyezao** [ComparativeGenomicsToolkit/cactus#1026]
Hi Cactus designers,

Thank you for the great tool. I have a few questions:

1. Should a rooted tree be used as the guide?
2. I am working on a plant genera with 13 genome assemblies. Is it better to include a reference-level genome assembly from the sister genus as an outgroup?
3. In regard to the 13 genome assemblies, a few of them are of reference level. Should I label all of them with "*" to use them as outgroups or just label one of them?

Best wishes,
Xiaoyezao

**Comment by glennhickey** [comment]
1. Rooted. Cactus only understands trees in NEWICK format, which are necessarily rooted.  
2. I do recommend using the outgroup if possible. 
3. Putting *s on all the reference level assemblies is probably a good idea.
