### ISSUE TITLE
How to get the index (.xg) of .vg file ?

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [ComparativeGenomicsToolkit/cactus#1028]
Hi,
    I am trying to use minigraph-cactus. And I'm not sure how to get the .xg file. The pipeline of D. Melanogaster Pangenome Methods can be seen below.
    "cactus ./js 16-fly-pg-2022-05-26-seqfile.txt ./softmask.fly.hal --realTimeLogging --logFile softmask.fly.hal.log"
    "hal2vg ./softmask.fly.hal --noAncesstors > fly-cactus.vg"
    After these steps, shall I use this command "vg index -x fly-cactus.xg -k 16 fly-cactus.vg" to construct the index of .vg file? 
Best wishes,
Yu Liu

**Comment by glennhickey** [comment]
I'd recommend using [cactus-pangenome](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md) to make your graph.  It will output a .gbz file (with `--gbz` and/or `--giraffe` options) that you can use will most vg tools (in place of an .xg).

But yeah, you can indeed convert .vg to .xg with `vg index -x` (or `vg convert -x`).  But I warn you that the output of progressive cactus converted this way will be difficult to use with vg.

**Comment by ggoodstudydaydayup** [comment]
Thanks for your reply !
