### ISSUE TITLE
hprc-graph-filtering-by-allele-frequency guidelines

### ISSUE THREAD

**Issue by peterdfields** [ComparativeGenomicsToolkit/cactus#1054]
I cannot locate the guidelines for doing this sort of graph simplification which occurs in a few previous issues(e.g., https://github.com/ComparativeGenomicsToolkit/cactus/issues/740 and https://github.com/ComparativeGenomicsToolkit/cactus/issues/817) and it also appears that the syntax of `cactus-graphmap-join` has changed quite a lot in the mean time of these earlier issues. Is there analogous way to apply `--vgClipOptions "-d 2 -m 10000"` options?

**Comment by glennhickey** [comment]
If you want to make giraffe indexes with that filtering, you'd use `--giraffe filter` now.  For just graphs `--gbz filter`.  If you want to change `-d 2` to `-d 3` it'd be `giraffe filter --filter 3`.  Please see here for more information https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md
