### ISSUE TITLE
_runner() got an unexpected keyword 'defer'

### ISSUE THREAD

**Issue by nspope** [ComparativeGenomicsToolkit/cactus#106]
Hi, thanks for developing this useful software. 

I had cactus working in the past with an older version of toil; but has broken upon updating to toil 3.21 (& using most recent cactus/master). The entire log from example run is attached, but the salient lines are:

```
kind-RunCactusPreprocessorThenProgressiveDown/instanceKl8rbY      File "/opt/tacc_mounts/home1/03125/nspope/cactus_env/lib/python2.7/site-packages/toil/worker.py", line 366, in workerScript
kind-RunCactusPreprocessorThenProgressiveDown/instanceKl8rbY        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
kind-RunCactusPreprocessorThenProgressiveDown/instanceKl8rbY    TypeError: _runner() got an unexpected keyword argument 'defer'
```

Which makes me think that there may be recent changes in the toil API that are breaking cactus.

[evolverMammals.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/3852932/evolverMammals.log)

**Comment by nspope** [comment]
... and five minutes later I see https://github.com/DataBiosphere/toil/pull/2861. I am leaving this open for now, though, as other users with fresh installations will bump into this issue in the meantime.

**Comment by bollig** [comment]
So what is the solution to get this update? Looks like the fix was merged into master. No new version has been released.
