### ISSUE TITLE
How to increase graph coverage?

### ISSUE THREAD

**Issue by sdws1983** [ComparativeGenomicsToolkit/cactus#1061]
Hello,

I am using the cactus-minigraph pipeline for constructing a pan-genome graph. I have followed the standard procedure described in the tutorial for each step. However, after running the cactus-graphmap-split step, I noticed that the splitting of chromosomes did not yield satisfactory results. In the `minigraph.split.log` file, I observed that many chromosomes have a low coverage (<0.09), which caused them to be assigned to the "ambiguous" category.

`minigraph.split.log` file looks like this:
```
Query contig is ambiguous: id=LAp_F|Chr08  len=59039016 cov=0.00312238 (vs 0.09) uf=3.96537 (vs 2)
 Reference contig mappings:
  Chr01: 27998
  Chr02: 46488
  Chr03: 43541
  Chr06: 6666
  Chr07: 2933
  Chr08: 184342
  Chr09: 2231
  Chr10: 6994
Query contig is ambiguous: id=LAp_E|Chr06  len=70953218 cov=0.014579 (vs 0.09) uf=46.6715 (vs 2)
 Reference contig mappings:
  Chr01: 22164
  Chr02: 17
  Chr03: 13927
  Chr06: 1034428
  Chr09: 2506
  Chr10: 9941
Query contig is ambiguous: id=LAp_E|Chr07  len=66159206 cov=0.00738174 (vs 0.09) uf=29.7714 (vs 2)
 Reference contig mappings:
  Chr01: 9914
  Chr03: 11871
  Chr04: 16404
  Chr07: 488370
```

Is there any way to adjust the parameters to increase the alignment coverage and improve the results?

**Comment by glennhickey** [comment]
You can use something like `--permissiveContigFilter 0.001` to just let everything through.

BUT if minigraph can only map 0.3% of a 60mb chromosome, you won't get a good result either way.  cactus will not be able to fill in the remaining 99.7%.  

I don't know what data this is, but unfortunately it looks like it is too divergent and/or complex to be handled effectively by this tool.

**Comment by sdws1983** [comment]
> You can use something like `--permissiveContigFilter 0.001` to just let everything through.
> 
> BUT if minigraph can only map 0.3% of a 60mb chromosome, you won't get a good result either way. cactus will not be able to fill in the remaining 99.7%.
> 
> I don't know what data this is, but unfortunately it looks like it is too divergent and/or complex to be handled effectively by this tool.

In fact I'm working on the plant genomes. So, is there any way we can increase the minigraph mapping rate?

**Comment by glennhickey** [comment]
`minigraph` has a `-j` parameter you can use to increase the expected divergence, but I haven't personally had much success using it.  (If you want to try this, you're probably best to experiment manually with minigraph outside of cactus)

If you have a phylogeny, you can probably get a much more sensitive alignment with Progressive Cactus. 

Otherwise, you can try [PGGB](https://github.com/pangenome/pggb) to make a graph.
