### ISSUE TITLE
compile error with taffy

### ISSUE THREAD

**Issue by leon945945** [ComparativeGenomicsToolkit/cactus#1089]
Hi, when I ran `build-tools/downloadMafTools`, an error was occurred.

> taf_add_gap_bases.cpp: In function 'void usage()':
taf_add_gap_bases.cpp:26:107: error: expected ')' before 'PRIi64'
   26 |     fprintf(stderr, "-m --maximumGapStringLength : The maximum size of a gap string to add, be default: %" PRIi64 "\n",
      |            ~                                                                                              ^~~~~~~
      |                                                                                                           )
taf_add_gap_bases.cpp:15:1: note: 'PRIi64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
   14 | #include "halBlockViz.h"
  +++ |+#include <cinttypes>
   15 | #endif
taf_add_gap_bases.cpp:26:105: warning: spurious trailing '%' in format [-Wformat=]
   26 |     fprintf(stderr, "-m --maximumGapStringLength : The maximum size of a gap string to add, be default: %" PRIi64 "\n",
      |                                                                                                         ^
taf_add_gap_bases.cpp:26:21: warning: too many arguments for format [-Wformat-extra-args]
   26 |     fprintf(stderr, "-m --maximumGapStringLength : The maximum size of a gap string to add, be default: %" PRIi64 "\n",
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taf_add_gap_bases.cpp:29:136: error: expected ')' before 'PRIi64'
   29 |     fprintf(stderr, "-s --repeatCoordinatesEveryNColumns : Repeat coordinates of each sequence at least every n columns. By default: %" PRIi64 "\n", repeat_coordinates_every_n_columns);
      |            ~                                                                                                                           ^~~~~~~
      |                                                                                                                                        )
taf_add_gap_bases.cpp:29:137: note: 'PRIi64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
   29 |     fprintf(stderr, "-s --repeatCoordinatesEveryNColumns : Repeat coordinates of each sequence at least every n columns. By default: %" PRIi64 "\n", repeat_coordinates_every_n_columns);
      |                                                                                                                                         ^~~~~~
taf_add_gap_bases.cpp:29:134: warning: spurious trailing '%' in format [-Wformat=]
   29 |     fprintf(stderr, "-s --repeatCoordinatesEveryNColumns : Repeat coordinates of each sequence at least every n columns. By default: %" PRIi64 "\n", repeat_coordinates_every_n_columns);
      |                                                                                                                                      ^
taf_add_gap_bases.cpp:29:21: warning: too many arguments for format [-Wformat-extra-args]
   29 |     fprintf(stderr, "-s --repeatCoordinatesEveryNColumns : Repeat coordinates of each sequence at least every n columns. By default: %" PRIi64 "\n", repeat_coordinates_every_n_columns);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taf_add_gap_bases.cpp: In function 'int taf_add_gap_bases_main(int, char**)':
taf_add_gap_bases.cpp:192:55: error: expected ')' before 'PRIi64'
  192 |     st_logInfo("Maximum maximum gap string length : %" PRIi64 "\n", maximum_gap_string_length);
      |               ~                                       ^~~~~~~
      |                                                       )
taf_add_gap_bases.cpp:192:56: note: 'PRIi64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
  192 |     st_logInfo("Maximum maximum gap string length : %" PRIi64 "\n", maximum_gap_string_length);
      |                                                        ^~~~~~
taf_add_gap_bases.cpp:193:54: error: expected ')' before 'PRIi64'
  193 |     st_logInfo("Repeat coordinates every n bases : %" PRIi64 "\n", repeat_coordinates_every_n_columns);
      |               ~                                      ^~~~~~~
      |                                                      )
taf_add_gap_bases.cpp:193:55: note: 'PRIi64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
  193 |     st_logInfo("Repeat coordinates every n bases : %" PRIi64 "\n", repeat_coordinates_every_n_columns);
      |                                                       ^~~~~~
taf_add_gap_bases.cpp:281:48: error: expected ')' before 'PRIi64'
  281 |     st_logInfo("taffy add-gap-bases is done, %" PRIi64 " seconds have elapsed\n", time(NULL) - startTime);
      |               ~                                ^~~~~~~
      |                                                )
taf_add_gap_bases.cpp:281:49: note: 'PRIi64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
  281 |     st_logInfo("taffy add-gap-bases is done, %" PRIi64 " seconds have elapsed\n", time(NULL) - startTime);
      |                                                 ^~~~~~
make: *** [taf_add_gap_bases.o] Error 1

Not sure what made this error occur, please check it.

**Comment by leon945945** [comment]
Error was resolved by referring to the [https://github.com/pytorch/pytorch/issues/35185](https://github.com/pytorch/pytorch/issues/35185)
Thanks.

**Comment by glennhickey** [comment]
@diekhans Do you know what could be causing this?  Is there something we need in the Makefile or an include to make sure that `PRIi64` is defined?
