### ISSUE TITLE
How to visualize a pangenome

### ISSUE THREAD

**Issue by leone93** [ComparativeGenomicsToolkit/cactus#1115]
Sorry guys, 
I would like to visualize my pangenome but it is not so straightforward to do as it seems from your tutorial.
Can you explain how did you load the .gbz file into sequenceTubeMap? (or another way to do that?)
Thanks

**Comment by glennhickey** [comment]
Please report your tube map issues here

https://github.com/vgteam/sequenceTubeMap/issues
