### ISSUE TITLE
cactus - No such file or directory: 'fasta_chunk' from version 2.6.0

### ISSUE THREAD

**Issue by kleinjoel** [ComparativeGenomicsToolkit/cactus#1117]
First of all thank you for this great work. 
I attempted to install a newer version of Cactus after experiencing successful runs with a previous version. However, I encountered an error after a few minutes, specifically, "No such file or directory: 'fasta_chunk'."

Upon investigating the issue, I discovered that the binary file "fasta_chunk" is missing from the bin folder in versions 2.6.0 and later (including the lowest version I checked, 2.6.0). However, the file is still included in versions 2.4.4 and earlier.

I am curious to understand why this file is no longer included in the newer versions of Cactus. Is there a specific reason behind its exclusion, or could this be an unintended omission? I appreciate any insights that might shed light on this matter.

whole error message: 	Traceback (most recent call last):
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/cactus/shared/common.py", line 908, in _runner
	    super(RoundedJob, self)._runner(*args, jobStore=jobStore,
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/toil/job.py", line 2743, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/toil/job.py", line 2660, in _run
	    return self.run(fileStore)
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/cactus/preprocessor/cactus_preprocessor.py", line 187, in run
	    inChunkList = runGetChunks(sequenceFiles=[inSequence], chunksDir=inChunkDirectory,
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/cactus/shared/common.py", line 262, in runGetChunks
	    chunks = cactus_call(work_dir=work_dir,
	  File "/home/WUR/klein048/.local/lib/python3.9/site-packages/cactus/shared/common.py", line 757, in cactus_call
	    process = subprocess.Popen(call, shell=shell, encoding="ascii",
	  File "/shared/legacyapps/python/3.9.4/lib/python3.9/subprocess.py", line 951, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/shared/legacyapps/python/3.9.4/lib/python3.9/subprocess.py", line 1821, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'fasta_chunk'

**Comment by glennhickey** [comment]
`fasta_chunk` is neither included in nor called by cactus anymore.  If you are seeing this error, it is because you have an older version of cactus installed in your virtualenv, but the newer version in your PATH.  

Please erase any older versions, and re-install the latest version exactly following the instructions in https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.6.5/BIN-INSTALL.md

**Comment by kleinjoel** [comment]
Dear Glennhickey,

Thank you for your prompt response regarding the fasta_chunk error. Your explanation makes a lot of sense.

I did follow the instructions in the BIN-INSTALL.md, when I downloaded the new version expecting it to create a new virtualenv either replacing the old one or being linked to the new version. However, it appears that this is not the case.

Considering the situation, I was wondering if it would be possible to create separate virtualenvs for each version of cactus, giving them unique names. This way, I could have multiple versions coexisting peacefully on the same machine without any conflicts.

Once again, I genuinely appreciate your support, thank you once more for your time and assistance.

**Comment by glennhickey** [comment]
Yes, you can name your virtualenvs anything you want (I personally always use something more desscriptive than `cactus_env`).  And as long as they are set up and used properly, then everything should work fine no matter how many you have.

**Comment by kleinjoel** [comment]
That works like a charm, thanks for you help!

**Comment by kleinjoel** [comment]
Solved closed the issue
