### ISSUE TITLE
Reference species is missing lots of sequences after converting HAL

### ISSUE THREAD

**Issue by emistasis** [ComparativeGenomicsToolkit/cactus#1120]
Hello!

I'm currently in the process of trying to align a single chromosome across multiple species. I'm having a hard time wrapping my head around an issue I'm having and would really appreciate some guidance. I'm also going to ping @dentearl since I don't know if this is a Cactus or a mafTools (or a me) issue!

As mentioned, I'm using Cactus to align a single chromosome for multiple species, where the input sequence for each species is either multiple scaffolds or a continuous chromosome. My reference species for the MAF is the human, and I'm using the soft-masked chromosome from the T2T assembly. The chromosome I'm trying to align happens to be really repetitive and usually isn't well-assembled. I think it's also important to mention that my main goals are to visualize the alignment on Geneious (which is why I'm trying to convert the HAL to a FASTA) and then overlay gene annotations from the human to the alignment in order to assess differences in the "alignability" of various gene features. 

Currently, my workflow has been to convert my HAL to a MAF (using `cactus-hal2maf`) and then convert the MAF to a FASTA (using [mafTools](https://github.com/dentearl/mafTools)-`mafToFastaStitcher`). However, it seems that in my FASTA alignment, the human sequence is missing ~13Kbp. My assumption was that since the human is the reference for the MAF, it shouldn't really lose any bases or get that rearranged - the chromosomes for the other species would be instead since they're aligned to the human. 

I've gone back and checked that the sequence length of the input FASTA as well as the chromosome size for the human in the HAL match each other and are the correct length.  After that, it seems that regardless of the parameters I use, I can't get the right length for the FASTA, and that's where I'm stuck - I'm not sure if it is due to the HAL being converted into MAF blocks or if I can't get that type of resolution or if there's some filtering step I'm overlooking.

I hope this makes sense, and please let me know if not so I can try to clarify. Thank you both for developing and maintaining these software! They've been really useful for my research.

**Comment by glennhickey** [comment]
`cactus-hal2maf` now filters out unaligned blocks (ie  blocks with the reference row and nothing else) due to criticisms from the genome browser team.  This probably explains your missing sequence.   

I guess we can make this an option.  In the meantime, if you can find `cactus_hal2maf.py` in your virtualenv and comment out these lines (348-352) with # characters

```
    if options.maxRefNFrac:
        cmd += ' | mafFilter -m - -N {}'.format(options.maxRefNFrac)
    # get rid of single-row (ie ref-only) blcks while we're filtering
    cmd += ' | mafFilter -m - -l 2'
```
it should fix it.

**Comment by emistasis** [comment]
Thank you for your response! I apologize that it took me so long to follow-up. I needed to work with my campus HPC to be able to assess and run my container with no privileges.

That said, by commenting those lines out, I did get the number of base pairs I was expecting. The issue that I've now noticed is that the human, which is my reference genome when running `cactus-hal2maf`, seems to have ~200,000 gaps inserted into it. Are those gaps present in the HAL alignment or are they introduced during the conversion? Moreover, do you have any suggestions on how to minimize these gaps? I would prefer just to have the alignment in relation to the complete chromosome without any gaps, but I'm struggling to understand if that's possible. Also, this is the command that I'm running to convert the alignment:

`cactus-hal2maf ./js ./cactus_redo_single.maf.gz --refGenome Homo_sapiens --noAncestors --chunkSize 1000000 --filterGapCausingDupes --dupeMode single`

Thanks so much again for your help.

**Comment by emistasis** [comment]
Yup, those insertions were what I was referring to. `--gapFill 0` fixed it. Thank you kindly!
