### ISSUE TITLE
"Official" Docker image for cactus?

### ISSUE THREAD

**Issue by evanbiederstedt** [ComparativeGenomicsToolkit/cactus#113]
Hi there cactus developers

Apologies if I've missed something, but is there an "official" Docker image hosted somewhere for cactus? 

Thank you for the help, Evan

**Comment by glennhickey** [comment]
The latest here is a good bet.
https://quay.io/repository/comparative-genomics-toolkit/cactus?tab=tags

You can use it with "cactus --binariesMode docker --latest"

**Comment by evanbiederstedt** [comment]
Thanks @glennhickey!

I'm back at the release/tag question---it looks like the last release here was 2011. 

I could just take the master branch and specify the lastest commit, but I should ask the crew: is there a "recent stable release" that would be best?

**Comment by evanbiederstedt** [comment]
Hi @glennhickey 

Also, could you put a link in the README for future use? I find it surprisingly tricky to find via Google 

`"quay, comparative-genomics-toolkit"`  or `"quay, cactus"` doesn't give me what I need. 

It's ok to dismiss this as me being fussy though :) Certainly not a high priority thing to do. 

Thank you for the help, Evan

**Comment by glennhickey** [comment]
The thing is, as far as I know, these Docker images are only usable via
cactus --binariesMode docker on a cactus installed via pip as described in
the readme.  Don't think you can run them with docker run.

**Comment by evanbiederstedt** [comment]
> The thing is, as far as I know, these Docker images are only usable via
cactus --binariesMode docker on a cactus installed via pip as described in
the readme.  Don't think you can run them with docker run.

Yes, that's roughly what I've found out :) It's not too difficult to create such a Dockerfile/image though (I think, I haven't tested this out extensively). 

Could I ask: Why were these Docker images created in such a way that users could run cactus via `docker run -it`? I'm trying to better understand the architecture here for doing:

> these Docker images are only usable via cactus --binariesMode docker on a cactus installed via pip as described in the readme

**Comment by nathanweeks** [comment]
FWIW, I proposed a complete, self-contained Docker image (which we export to a Singularity image and run on a single node of our HPC cluster) here: https://github.com/ComparativeGenomicsToolkit/cactus/issues/94

**Comment by evanbiederstedt** [comment]
Hi @nathanweeks 

Thanks! This is helpful!

I get the following when trying to build the image from the Dockerfile:

```
$ docker build .
Sending build context to Docker daemon  3.072kB
Step 1/17 : FROM ubuntu:16.04 AS builder
 ---> 56bab49eef2e
Step 2/17 : RUN apt-get update && apt-get install --no-install-recommends -y git gcc g++ build-essential python-dev zlib1g-dev libkyototycoon-dev libtokyocabinet-dev libkyotocabinet-dev libbz2-dev pkg-config python-pip python-setuptools python-wheel
 ---> Using cache
 ---> 9001857be554
Step 3/17 : ENV kyotoTycoonIncl -I/usr/include -DHAVE_KYOTO_TYCOON=1
 ---> Using cache
 ---> 2cd3feb3e625
Step 4/17 : ENV kyotoTycoonLib -L/usr/lib -Wl,-rpath,/usr/lib -lkyototycoon -lkyotocabinet -lz -lbz2 -lpthread -lm -lstdc++
 ---> Using cache
 ---> a045b9d49af8
Step 5/17 : RUN mkdir -p /home/cactus
 ---> Using cache
 ---> e49753607342
Step 6/17 : COPY . /home/cactus
 ---> 0b381144a7ab
Step 7/17 : RUN cd /home/cactus && make clean && rm -f /home/cactus/submodules/hdf5/bin/h5c++
 ---> Running in 7b6bc13d3146
make: *** No rule to make target 'clean'.  Stop.
The command '/bin/sh -c cd /home/cactus && make clean && rm -f /home/cactus/submodules/hdf5/bin/h5c++' returned a non-zero code: 2
```

**Comment by nathanweeks** [comment]
HI @evanbiederstedt , sorry for the poor documentation; that Dockerfile is meant to replace the Dockerfile in the cactus git repo. So you'd first need to `git clone https://github.com/ComparativeGenomicsToolkit/cactus.git`, overwrite the Dockerfile in the root of the  git working tree, and do the `docker build` from that directory.

**Comment by evanbiederstedt** [comment]
HI @nathanweeks 

Apologies for the delays here, and I appreciate the help.

I tried building the image after cloning the repo. I'm able to successfully do that, but I run into the following issue when running the image interactively:

```
% docker run -it 939b036cfa7e /bin/bash
root@b1b05a8780c8:/# which python
/usr/bin/python
root@b1b05a8780c8:/# pip
bash: pip: command not found
root@b1b05a8780c8:/# cactus
Traceback (most recent call last):
  File "/usr/local/bin/cactus", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by progressiveCactus
root@b1b05a8780c8:/# 
```

It looks like pip wasn't properly installed via `apt-get install python-pip`? I'll try to look more closely into this issue soon.

**Comment by nathanweeks** [comment]
Hi @evanbiederstedt , please see my recent update to the Dockerfile that takes into account the recent additional pytest dependency (pip should not be needed, as everything should already be in the final image): https://github.com/ComparativeGenomicsToolkit/cactus/issues/94#issuecomment-562208658

**Comment by evanbiederstedt** [comment]
Hi @nathanweeks 

Thanks! Sorry I missed the previous comment in that thread. 

I believe you're right---the updated Dockerfile does work. 

```
docker run -it beea75b1f815 /bin/bash
root@98c5e7f30709:/# cactus
usage: cactus [-h] [--logOff] [--logCritical] [--logError] [--logWarning]
              [--logInfo] [--logDebug] [--logLevel LOGLEVEL]
              [--logFile LOGFILE] [--rotatingLogging] [--workDir WORKDIR]
              .... 
              [--latest] [--containerImage CONTAINERIMAGE]
              [--binariesMode {docker,local,singularity}]
              jobStore seqFile outputHal
cactus: error: too few arguments
root@98c5e7f30709:/# exit
exit
```

Thank you for the help here. Also, could I ask you why you started using `FROM ubuntu:xenial-20191108 AS builder` instead of `ubuntu:16.04`?

**Comment by nathanweeks** [comment]
@evanbiederstedt : good to know!

I specified `ubuntu:xenial-20191108` for reproducibility (e.g., 16.04 at one point must have referred to `ubuntu:xenial-20151218.1` , and there have been updates to apt & other utilities in the base system since then)

**Comment by evanbiederstedt** [comment]
> I specified ubuntu:xenial-20191108 for reproducibility (e.g., 16.04 at one point must have referred to ubuntu:xenial-20151218.1 , and there have been updates to apt & other utilities in the base system since then)

Thanks, that makes sense. I noticed some issues with `16.04` but I didn't dig too deeply into the problems.

**Comment by evanbiederstedt** [comment]
For future users (and myself), here's the Dockerfile which clones the repo via the current master branch:

```
FROM ubuntu:xenial-20191108 AS builder

RUN apt-get update && apt-get install --no-install-recommends -y git gcc g++ build-essential python-dev zlib1g-dev libkyototycoon-dev libtokyocabinet-dev libkyotocabinet-dev libbz2-dev pkg-config python-pip python-setuptools python-wheel

ENV kyotoTycoonIncl -I/usr/include -DHAVE_KYOTO_TYCOON=1
ENV kyotoTycoonLib -L/usr/lib -Wl,-rpath,/usr/lib -lkyototycoon -lkyotocabinet -lz -lbz2 -lpthread -lm -lstdc++

## RUN mkdir -p /home/cactus
## COPY . /home/cactus

RUN git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive  /home/cactus  

RUN cd /home/cactus && make clean && rm -f /home/cactus/submodules/hdf5/bin/h5c++
RUN cd /home/cactus && make

RUN pip install --upgrade --prefix=/home/cactus/.local toil==3.20.0
# https://github.com/ComparativeGenomicsToolkit/cactus/pull/79
RUN cd /home/cactus && sed -i.bak 's/networkx>=2,<3/networkx==2.2/' setup.py && pip install --upgrade --prefix=/home/cactus/.local .

FROM ubuntu:xenial-20191108
RUN apt-get update && apt-get install --no-install-recommends -y kyototycoon libtokyocabinet9 python python-pytest zlib1g bzip2 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /home/cactus/bin/* /usr/local/bin/
COPY --from=builder /home/cactus/submodules/sonLib/bin/* /usr/local/bin/
COPY --from=builder /home/cactus/submodules/cactus2hal/bin/* /usr/local/bin/
COPY --from=builder /home/cactus/.local/bin/* /usr/local/bin/
# /usr/local/lib/python2.7/site-packages not in sys.path
COPY --from=builder /home/cactus/.local/lib/python2.7/site-packages/ /usr/local/lib/python2.7/dist-packages/

# https://github.com/ComparativeGenomicsToolkit/cactus/issues/102#issuecomment-540781259
RUN sed -i'' -n '/config.writeXML/d; p' /usr/l
```
