### ISSUE TITLE
Cactus graph map split fails on rgfa-split step 

### ISSUE THREAD

**Issue by IsaacDiaz026** [ComparativeGenomicsToolkit/cactus#1145]
I am trying to use graph map-split with the following command 

`cactus-graphmap-split jobstore test_seqfile.txt first_run.gfa first_run.paf --workDir /bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir --outDir /bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir  --reference PWN --binariesMode local --cleanWorkDir onSuccess`

and receive an error on the rgfa-split step 

`RuntimeError: Command ['rgfa-split', '-p', '/bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir/fc47df20b80d5e509bee86a2939e1e56/8320/c791/tmpy2q5q3in/mg.paf', '-b', '/bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir/fc47df20b80d5e509bee86a2939e1e56/8320/c791/tmpy2q5q3in/split_', '-Q', '2', '-a', '_AMBIGUOUS_', '-L', '/bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir/fc47df20b80d5e509bee86a2939e1e56/8320/c791/tmpy2q5q3in/split.log', '-n', '0.75', '-n', '0.5', '-n', '0.25', '-T', '100000', '-T', '1000000', '-g', '/bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir/fc47df20b80d5e509bee86a2939e1e56/8320/c791/tmpy2q5q3in/mg.gfa', '-G', '-r', 'id=PWN|', '-A', '5'] signaled SIGABRT: stderr=terminate called after throwing an instance of 'std::invalid_argument'
          what():  stol
`

The input paf to this command looks normal to me. All of the command arguments seem to be fine for this command. 

I am using version 2.6.2

**Comment by glennhickey** [comment]
Where is `first_run.gfa ` from?  It must be the output of `minigraph` or you will get errors like this.

**Comment by IsaacDiaz026** [comment]
I used the following command to get the gfa 

`cactus-minigraph jobstore test_seqfile.txt first_run.gfa --workDir /bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2023-03-15_pangenome_assembly/workdir --reference PWN --binariesMode local --defaultCores 4`

**Comment by glennhickey** [comment]
That seems about right.  Are you able to try running `cactus-pangenome` with the latest cactus release on this data?

**Comment by IsaacDiaz026** [comment]
I will try this and get back to you
