### ISSUE TITLE
Adjusting minigraph -j parameter within cactus-pangenome pipeline

### ISSUE THREAD

**Issue by IsaacDiaz026** [ComparativeGenomicsToolkit/cactus#1153]
How can I adjust minigraph parameters within the cactus-pangenome pipeline? 

I am seeing reduced performance of giraffe (with clipped graph) compared to mapping to a linear reference. I think it's because some regions cannot be surjected to the reference. I figured adjusting alignment sensitivity may help.

**Comment by glennhickey** [comment]
You can set the options here for bot hconstruction and mapping

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/cactus_progressive_config.xml#L328C3-L329C40
