### ISSUE TITLE
population genotype

### ISSUE THREAD

**Issue by pengyan19** [ComparativeGenomicsToolkit/cactus#1156]
Hi, when i used these codes to build the pangenome, but we didn't obtain .vg file in whole genome, only the chromosome .vg file.  how to change these code?

/public/software/singularity-ce-3.11.3/bin/singularity exec /public/software/singularity-ce-3.11.3/sif/cactus-v2.5.2.sif cactus-pangenome ./jobstore ./sample.txt --outDir /public/home/pengyan/bioproject2/22.c/03.chr-pangenome --outName ca --reference AFR --vcf --giraffe clip --gbz clip --mapCores 8 --consCores 8 --otherContig chrOther --permissiveContigFilter 0.05 --workDir work

**Comment by glennhickey** [comment]
There's no way to get a whole genome `.vg` directly from cactus-pangenome.  You can produce one yourself from the gfa or gbz (`vg convert`) or the chromosomal vg files (`vg combine`).

Note that if you want to use `vg` with your pangenome, the `.gbz` file will work with most tools except those that modify the graph.

**Comment by pengyan19** [comment]
Hi, i used the vg combine the file, but i get the errors as follows:


DiskIO::write(): Write failed
DiskIO::write(): You may have run out of temporary disk space at /tmp



code:
/public/home/pengyan/biosoft/soft/vg combine chr1.vg chr2.vg chr3.vg chr4.vg chr5.vg chr6.vg chr7.vg chr8.vg chr9.vg chr10.vg chr11.vg chr12.vg chr13.vg chr14.vg chr15.vg chr16.vg chr17.vg chr18.vg chr19.vg chr20.vg chr21.vg chr22.vg chr23.vg chr24.vg chr25.vg chr26.vg chr27.vg chr28.vg chr29.vg chr30.vg chr31.vg chrOther.vg&gt;merged.vg
~/biosoft/soft/vg mod -X 256 merged.vg &gt;merged.mod.vg
~/biosoft/soft/vg index merged.mod.vg -x caotan.xg -g caotan.gcsa -L



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ComparativeGenomicsToolkit/cactus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 凌晨3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ComparativeGenomicsToolkit/cactus] population genotype (Issue #1156)





 
There's no way to get a whole genome .vg directly from cactus-pangenome.  You can produce one yourself from the gfa or gbz (vg convert) or the chromosomal vg files (vg combine).
 
Note that if you want to use vg with your pangenome, the .gbz file will work with most tools except those that modify the graph.

**Comment by glennhickey** [comment]
GCSA index construction can indeed run out of space on graphs that are not specially preprocessed.  This is a very common issue.  You can read more about that here: https://github.com/vgteam/vg/wiki/Index-Construction#temporary-files

I don't think this is a minigraph-cactus issue, so am closing it.
