### ISSUE TITLE
Fail to run the example using docker

### ISSUE THREAD

**Issue by BKU-Technion** [ComparativeGenomicsToolkit/cactus#1160]
Hi, 
I am trying to run the example using the docker.
` docker run -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.6.7 cactus /data/jobStore /data/evolverMammals.txt /data/evolverMammals.hal`

and get  error below.
I found some related reports but not with the exact problem. 
Thanks.
Guy

> [2023-09-14T07:28:28+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
> [2023-09-14T07:28:28+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus /data/jobStore /data/evolverMammals.txt /data/evolverMammals.hal
> [2023-09-14T07:28:28+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: b7c7b2e6c50ad02e37aa2649440b12629b6447e0
> Traceback (most recent call last):
>   File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
>     sys.exit(main())
>   File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 403, in main
>     mc_tree, input_seq_map, og_candidates = parse_seqfile(options.seqFile, config_wrapper, root_name = options.root)
>   File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/progressive_decomposition.py", line 41, in parse_seqfile
>     seq_file = SeqFile(seqfile_path, root_name = root_name, defaultBranchLen=config_wrapper.getDefaultBranchLen(pangenome=pangenome))
>   File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/seqFile.py", line 68, in __init__
>     self.parseFile(path, root_name)
>   File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/seqFile.py", line 72, in parseFile
>     raise RuntimeError("File not found: %s" % path)
> RuntimeError: File not found: /data/evolverMammals.txt

**Comment by glennhickey** [comment]
You need to download the seqfile.  I've updated the example to reflect that in #1163
