### ISSUE TITLE
Failed to run example code with error in MergeChunks

### ISSUE THREAD

**Issue by BitaoQiu** [ComparativeGenomicsToolkit/cactus#1169]
Dear Cactus developers,

I used the pre-compiled Binaries Linux (and also Docker image), but failed to run the example code. Below is the log file, could you please provide guidance on what went wrong?

[preprocess-simHuman_chr6.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/12706698/preprocess-simHuman_chr6.log)

Best,
Bitao

**Comment by glennhickey** [comment]
This looks like a file system issue
```
	OSError: [Errno 18] Invalid cross-device link: '/gpfs/bwfor/home/fr/fr_fr/fr_bq1000/bin/cactus-bin-v2.6.7/jobstore/0/files/for-job/kind-LastzRepeatMaskJob/instance-f08n3u4y/file-f5cd018670074a8db11f04e7ef116311/simHuman_chr6_0.maskedQeury' -> '/scratch/fr_bq1000_o05i14/7da553ce554857f8be47b37976fa6c5a/afa8/8fb5/tmpx09ygp44.tmp'
```
You may be able to work around this by adding `--disableCaching`, otherwise you'll have to task on Toil's github for more details: https://github.com/DataBiosphere/toil/issues

**Comment by BitaoQiu** [comment]
Thank you for the quick reply. Adding --disableCaching does not help. However, after checking Toil's GitHub, I realise that this is because of writability issue (https://github.com/vgteam/toil-vg/issues/84)

I have now added --workDir ~/ and it works.

Best,
Bitao
