### ISSUE TITLE
Err No 8: Exec format error: 'cactus_sanitizeFastaHeaders'

### ISSUE THREAD

**Issue by Rahul-bio** [ComparativeGenomicsToolkit/cactus#1200]
Hi,
I have installed the latest release and created the virtual environment. But when I am running the test command, I am getting this error of cactus_sanitizeFastaHeaders. 
I am using a MacOS. Kindly help me sort it out.

**Comment by glennhickey** [comment]
The Cactus releases are Linux-only. It is possible to build from [source](https://github.com/ComparativeGenomicsToolkit/cactus#compiling-binaries-locally) on Mac, but we don't have any documentation specifically for it.  You need to get the dependencies out of Homebrew or something like that (as opposed to `apt`)
