### ISSUE TITLE
UnboundLocalError: local variable 'gpu' referenced before assignment

### ISSUE THREAD

**Issue by polchan** [ComparativeGenomicsToolkit/cactus#1213]
Hi! Glenn
I want to run jobs within Singularity image `cactus:v2.6.10-gpu`, and I use this code `cactus ./js ./Malus.txt ./Malus.hal --binariesMode singularity --gpu 8` , but  it reminds me an issue as below:

> Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 395, in main
    importSingularityImage(options)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 436, in importSingularityImage
    gpu = bool(options.gpu) if gpu in options else False
UnboundLocalError: local variable 'gpu' referenced before assignment

So, Can you help me solve this issue?
Thanks 

Bo-Cheng

**Comment by glennhickey** [comment]
Ugh, wish I'd read this before making the release today.  This is a typo: gpu should be in quotes after the if, that didn't get caught since we have no gpu tests and I never use Singularity. 

Thanks for raising it, I'll make yet another patch release as soon as possible with a fix.

**Comment by polchan** [comment]
> Ugh, wish I'd read this before making the release today. This is a typo: gpu should be in quotes after the if, that didn't get caught since we have no gpu tests and I never use Singularity.
> 
> Thanks for raising it, I'll make yet another patch release as soon as possible with a fix.

You are too humble!
 I'll look forward to the next release.
