### ISSUE TITLE
after build , no cactus-pangenome bin file

### ISSUE THREAD

**Issue by lixiang117423** [ComparativeGenomicsToolkit/cactus#1217]
I was going to try to build the cactus-pangenome bin file according to the tutorial https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/README.md#installing-manually-from-source, but there is no the cactus-pangenome file in the bin folder. Thanks.

**Comment by glennhickey** [comment]
You need to exactly follow all the instructions, including setting up the virtualenv (where `cactus-pangenome` will be found) to install cactus.
