### ISSUE TITLE
minigraph-cactus result gfa to 1.0 version

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#1236]
Dear developer:
I have successfully built the gfa file according to the requirements of Minigrah-Cactus, but since the version 1.1 is generated, we want to use panacus for visual analysis and convert it into 1.0 format (https://github.com/marschall-lab/panacus). 
The error is showed Skipping GFA W line: GFA format error: On pass 1: On line 5186766: [GFAParser] Skipping GFA W line: GFA format error: On pass 1: On line 5186766: Duplicate path test1#1#test85 exists in the graph translate, may I ask how to solve this problem.
Code:
vg convert -g test.full.gfa -fW --threads 10 > test.full.1.gfa

**Comment by glennhickey** [comment]
Panacus supports gfa 1.1 and should work (and has been tested) directly on mc output. 

As far as the GFAParser warning goes, you can usually ignore that safely -- it comes from a rGFA / w-line duplication of the path information.  Note that I can't reproduce this warning on the current version of mc/vg.

**Comment by ld9866** [comment]
Thank you for your prompt reply
We used the data test of E. coli and found that there was no problem, but our real data may be too large and encountered some problems. We will think about what the problem is.
