### ISSUE TITLE
How to use Minigraph-cactus pan genome to poplualtion analysis

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#1237]
Dear developer:
At present, we have built a graphical pan-genome using 27 genomes, and then we want to map a batch of population data into our pan-genome, which is very easy to obtain vcf variation information of individuals after obtaining gam files through vg Giraffe and converting them. I wonder if we can directly use bcftools for post-merge analysis as easily as GATK.

Besides, we want to do population level analysis only for SV greater than 50BP, how do I do this?
Best

**Comment by glennhickey** [comment]
You should be able to use bcftools to merge.  It helps if you run vg call with `-a` if you're using vg call.  You can use `bcftools norm -f` to left shift your variants which may help, and `truvari` has some functionality for merging SVs as well.

**Comment by ld9866** [comment]
Dear developer:
We want to translate the MC result (vcf) to biallelic type because we want to use the PanGenie to genotype our population, l want to ask how to do this step?
Best
