### ISSUE TITLE
Primate example

### ISSUE THREAD

**Issue by jonahcullen** [ComparativeGenomicsToolkit/cactus#1259]
Hello, I am just starting to get a handle on how this excellent software works and ran into a wall using singularity. I am thinking it is likely due to 

```
/usr/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
        : exit status 127
```

but was not sure if I missed something during installation. I followed the instructions [here](https://github.com/ComparativeGenomicsToolkit/cactus?tab=readme-ov-file#installing-manually-from-source) and then ran

```
cactus-pangenome \
	./js \
	./examples/evolverPrimates.txt \
	--binariesMode singularity \
	--logFile primates-pg.log \
	--outDir primates-pg \
	--outName primates-pg \
	--reference simChimp \
	--vcf \
	--giraffe \
	--gfa \
	--gbz \
	--viz \
	--logDebug
```

I was unable to copy/paste the entire log so I attached it - hopefully that was okay.
[primates-pg.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/13845669/primates-pg.log)

**Comment by glennhickey** [comment]
This is an error from singularity that does not seem (directly) related to Cactus. 
```	
RuntimeError: Command ['singularity', '--silent', 'exec', '-u', '-B', '/tmp/a4300c8843455c21b283273f4b720352/b497/c8cf/tmpvphhf04x:/mnt', '--pwd', '/mnt', '/scratch/pangen/cactus/js/cactus.img', 'cactus_sanitizeFastaHeaders', 'simGorilla.fa', 'simGorilla', '-p'] exited 255: stderr=FATAL:   while preparing image: while handling /scratch/pangen/cactus/js/cactus.img: while extracting image: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
	WARNING: group file doesn't exist in container, not updating
	WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
	WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
	WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
	WARNING: Skipping mount /usr/local/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
	WARNING: Skipping mount /usr/local/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
	WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
	/usr/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
	: exit status 127
```
For what it's worth, your command runs fine on Ubuntu with singularity version `singularity-ce version 3.10.3` and Cactus [v2.7.0](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.7.0).  Perhaps there's an issue with your singularity version or installation that is behind this.  

I recommend using the [release](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.7.0).  If you install the binaries, you don't need to use singularity. If you insist on using singularity, then you can try just opening a shell inside the Cactus container, and run cactus-pangenome from there (though you may just run into the same error).

**Comment by jonahcullen** [comment]
Thank you for your very quick response! I was using singularity version 3.11.0 and do not insist on using that. I will try using the binaries. Thanks again!

**Comment by jonahcullen** [comment]
Apologies I was able to get the binaries installed just fine but the primate example is still failing for me. It seems to start correctly, submit a job to the scheduler, which then failed and `cactus-pangenome` appears to get stuck. This is the command

```
cactus-pangenome \
	./js \
	./examples/evolverPrimates.txt \
	--batchSystem slurm \
	--consCores 4 \
	--consMemory 16Gi \
	--indexCores 4 \
	--mgCores 4 \
	--mapCores 4 \
	--workDir /scratch.global/mccuem_PANG \
	--batchLogsDir /scratch.global/mccuem_PANG/batch_logs \
	--logFile primates-pg.log \
	--outDir primates-pg \
	--outName primates-pg \
	--reference simChimp \
	--vcf \
	--giraffe \
	--gfa \
	--gbz \
	--viz \
	--logDebug
```

and the first job that was submitted and failed after 4 seconds

```
JobId=160852290 JobName=toil_job_1_pangenome_end_to_end_workflow
   UserId=cull0084(71979) GroupId=fried255(11930) MCS_label=N/A
   Priority=111876 Nice=0 Account=fried255 QOS=normal
   JobState=FAILED Reason=JobLaunchFailure Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:53
   RunTime=00:00:04 TimeLimit=00:01:00 TimeMin=N/A
   SubmitTime=2024-01-06T08:52:14 EligibleTime=2024-01-06T08:52:14
   AccrueTime=2024-01-06T08:52:14
   StartTime=2024-01-06T08:52:41 EndTime=2024-01-06T08:52:45 Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2024-01-06T08:52:41 Scheduler=Backfill
   Partition=agsmall AllocNode:Sid=ln0006:1635010
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=acn09
   BatchHost=acn09
   FedOrigin=mesabi FedViableSiblings=agate,mesabi FedActiveSiblings=agate
   NumNodes=1 NumCPUs=1 NumTasks=1 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=1,mem=2G,node=1
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=2G MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=(null)
   WorkDir=/scratch.global/mccuem_PANG/cactus-bin-v2.7.0
   StdErr=/scratch.global/mccuem_PANG/batch_logs/toil_7a08a424-dbfe-4a7e-80bb-9f7ec0eb16d8.1.160852290.err.log
   StdIn=/dev/null
   StdOut=/scratch.global/mccuem_PANG/batch_logs/toil_7a08a424-dbfe-4a7e-80bb-9f7ec0eb16d8.1.160852290.out.log
   Power=
```

I've also attached the log file where you can see it asks for the job status with `sacct` and then does not receive "an answer" apparently. I'm guessing this might be more of `Toil`/`slurm` issue but thought I would check in case this is something you've already seen.


Thanks again!
[primates-pg.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/13850124/primates-pg.log)

**Comment by glennhickey** [comment]
Yeah, that's more of a Toil thing -- you may have to raise your issue there.  One thing to check first is the contents in the files in ` /scratch.global/mccuem_PANG/batch_logs` (from `--batchLogsDir`).  You can just cat them all and look for errors -- if there was a `slurm` error it would most likely show up there.
