### ISSUE TITLE
msa_view seems to be missing from the cactus:v2.7.0 docker image

### ISSUE THREAD

**Issue by brantfaircloth** [ComparativeGenomicsToolkit/cactus#1262]
Good morning,

I hope you are all doing well. I'm working with a singularity container built from the cactus:v2.7.0 docker image and running  `halPhyloPTrain.py`, which did not complete because the `msa_view` binary seems to be missing from the docker image (although `msa_view` **is** in the pre-compiled binaries tarball).  It also seems, comparing the list of binaries included in the pre-compiled tarball to those in the docker image, that several other binaries are also (possibly) missing.

Thanks!
-b

**Comment by glennhickey** [comment]
Good catch, thanks.  Will be fixed in next release.
