### ISSUE TITLE
cactus-pangenome error : OSError: [Errno 7] Argument list too long: 'cactus_consolidated'

### ISSUE THREAD

**Issue by tanger-code** [ComparativeGenomicsToolkit/cactus#1276]
Hi.

I'm creating a pan-genome graph of thousands of bacterial genomes using command : `cactus-pangenome ./1668-js-9 ./seqfile.txt --outName KP --outDir 1668-kp-9 --reference GN202435 --giraffe --vcf  --viz --odgi --gbz --gfa --vcf --logFile 1668.log --workDir ./workDir-1668 --mgCores 80 --mapCores 80 --consCores 80 --indexCores 80 2> 1668.stderr`.
But there is an error in the last:
![image](https://github.com/ComparativeGenomicsToolkit/cactus/assets/74750242/a7f8664c-e9c8-4591-b8d4-c3a1288a2108)
What might be the cause of this error？ Is it because I use too much genome( about 1500)?

**Comment by glennhickey** [comment]
There are some known issues with regards to scaling about about 500 genomes.  We'll need to get this fixed, as we'll soon have more than that many human genomes in the HPRC, but I don't have a timeline yet.  For now you'll have to subsample or use a different tool.

**Comment by tanger-code** [comment]
> There are some known issues with regards to scaling about about 500 genomes. We'll need to get this fixed, as we'll soon have more than that many human genomes in the HPRC, but I don't have a timeline yet. For now you'll have to subsample or use a different tool.

Okay, thank you. I will try to subsample them later.

**Comment by fpichon** [comment]
Same error :/
