### ISSUE TITLE
InsufficientSystemResources Too much memory is requested 

### ISSUE THREAD

**Issue by IsaacDiaz026** [ComparativeGenomicsToolkit/cactus#1281]
Hello, 

I am trying to use the progressive cactus pipeline to align 11 plant genomes ~ 300Mb each. The pipeline seemed to work up until the job 'tile_alignments', and is requesting more memory than is allotted. 

When using --batchSystem slurm and submitting the command on the head node on my HPCC cluster like so cactus jobstore $SEQFILE Citrus_WGA --binariesMode local --restart --batchSystem slurm --consMemory 100Gi --consCores 8 

It requests more memory than I can provide and shows this message. 
[2024-01-29T11:08:40-0800] [MainThread] [W] [toil.batchSystems.singleMachine] Not enough memory! User limited to 1000000000000000 bytes but we only have 540812210176 bytes.

and also this 

toil.lib.misc.CalledProcessErrorStderr: Command '['sbatch', '-J', 'toil_job_1_tile_alignments', '--export=ALL,TOIL_RT_LOGGING_ADDRESS=10.102.10.7:57483,TOIL_RT_LOGGING_LEVEL=INFO,OMP_NUM_THREADS=1', '--mem=1514730', '--cpus-per-task=1', '-o', 'logdir/toil_220259e3-82e4-4200-bd70-cd7e2cb394a2.1.%j.out.log', '-e', 'logdir/toil_220259e3-82e4-4200-bd70-cd7e2cb394a2.1.%j.err.log', '--wrap=_toil_worker tile_alignments file:/bigdata/seymourlab/idiaz026/Citrus_non-coding_evolution/2024-01-18_WGAconsScoring/jobstore kind-tile_alignments/instance-_tucfv0x --context gASVzgAAAAAAAACMIXRvaWwuYmF0Y2hTeXN0ZW1zLmNsZWFudXBfc3VwcG9ydJSMFFdvcmtlckNsZWFudXBDb250ZXh0lJOUKYGUfZSMEXdvcmtlckNsZWFudXBJbmZvlIwldG9pbC5iYXRjaFN5c3RlbXMuYWJzdHJhY3RCYXRjaFN5c3RlbZSMEVdvcmtlckNsZWFudXBJbmZvlJOUKE5OjCQyMjAyNTllMy04MmU0LTQyMDAtYmQ3MC1jZDdlMmNiMzk0YTKUjAZhbHdheXOUdJSBlHNiLg==']' exit status 1: sbatch: error: Memory specification can not be satisfied
sbatch: error: Batch job submission failed: Requested node configuration is not available

I would like to avoid having to rerunning the entire pipeline, since the lastz alignments took several days. Doesn't this seem like an unreasonable amount of memory to request? How should I proceed?

**Comment by glennhickey** [comment]
The memory is estimated based on the file size.  I think you have millions of pairwise alignments going in, and it's coming up with this giant number.  I'd like to have an interface to override this and let you at least try running it and seeing if it runs out of memory, but that's not implemented yet.  

Have you RepeatMasked your input genomes?  Very highly repetitive regions that aren't softmasked are usually to blame for this type of thing.

**Comment by IsaacDiaz026** [comment]
repeat masking resolved this , thanks!
