### ISSUE TITLE
question about Cactus input tree nwk

### ISSUE THREAD

**Issue by bighawkin** [ComparativeGenomicsToolkit/cactus#1304]
input file need species list and nwk information. if the nwk is1 neccesarriy , if i don't have nwk file ,Is the result available?I have try to run whith no nwk file ,it is runing. I don't konw the result is available?

**Comment by bighawkin** [comment]
If my nwk file lacks branch lengths, would the results of this alignment run still be reasonable?  
Thank you！

**Comment by glennhickey** [comment]
See the [FAQ](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#frequently-asked-questions) please

**Comment by bighawkin** [comment]
thank you very much
