### ISSUE TITLE
no cactus executable when installing from source

### ISSUE THREAD

**Issue by benlynch47** [ComparativeGenomicsToolkit/cactus#131]
Is there a particular branch that should be used to compile from source? I was able to compile without errors, however it did not create a binary named "cactus". It successfully made 108 other executables in the bin directory. Any pointers would be appreciated.  Thanks.

**Comment by diekhans** [comment]
The cactus script is create when by setup.py when you run "pip install .".

However, IMHO it would be go if make created it.

**Comment by benlynch47** [comment]
Thanks @diekhans . That did it.
