### ISSUE TITLE
is there a chromosome length limit?

### ISSUE THREAD

**Issue by eead-csic-compbio** [ComparativeGenomicsToolkit/cactus#1312]
Hi, does minigraph-cactus support chromosomes of any length or is there a limit instead? 
Thanks

**Comment by glennhickey** [comment]
If you're chromosomes are under 2 gigabses I think it should work okay.  After that I'm not sure.  What size is your input?

**Comment by eead-csic-compbio** [comment]
All chrs are smaller than that, so it should be fine : 
chr1H_LR890096.1	516505932	18	80	81
chr2H_LR890097.1	665585731	522962293	80	81
chr3H_LR890098.1	621516506	1196867864	80	81
chr4H_LR890099.1	610333535	1826153345	80	81
chr5H_LR890100.1	588218686	2444116068	80	81
chr6H_LR890101.1	561794515	3039687506	80	81
chr7H_LR890102.1	632540561	3608504471	80	81
I was asking because we had to split them in two to be carry out GATK analyses, thanks!
