### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/cactus#132]
Good morning,
I'm trying to install the latest version of cactus in a UGE cluster environment. Docker is not supported, so I have to install it compiling the binaries. In the past, I managed to run cactus using the conda builtin package (conda install -n cactus -c bioconda cactus). This worked just fine, but I'd like to get the latest updated version in the hope that this will fix some of the bugs that I keep coming across (#123). 
The system has kyototycoon compiled and accessible, and I've installed HDF 1.10.6 locally. I've proceeded with the installation as follow:
```
# Load modules
module load anaconda
module load roslin/gcc/7.3.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/PATH/TO/apps/gcc/7.3.0/lib64
export LD_INLCUDE_PATH=$LD_LIBRARY_PATH:/PATH/TO/apps/gcc/7.3.0/include
LDFLAGS=-L/PATH/TO/apps/gcc/7.3.0/lib64/

# Prepare HDF5
mkdir HDF5
wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz
tar xvfz hdf5-1.10.6.tar.gz
prfx=`pwd`/HDF5
cd hdf5-*
./configure --enable-cxx --prefix $prfx
make && make install 
cd $prfx
export PATH=`pwd`/bin:$PATH
export h5prefix=-prefix=`pwd`

# Load kyototycoon
export PATH=/PATH/TO/apps/kyoto/tycoon/bin:$PATH
ttPrefix=/PATH/TO/apps/kyoto/20170410/
export kyotoTycoonIncl="-I${ttPrefix}/include -DHAVE_KYOTO_TYCOON=1"
export kyotoTycoonLib="-L${ttPrefix}/lib -Wl,-rpath,${ttPrefix}/lib -lkyototycoon -lkyotocabinet -lz -lbz2 -lpthread -lm -lstdc++"

# Create environment with python 2.7.15
conda create -y -n cactus2 python=2.7.15
source activate cactus2 
cd ..
pip install --upgrade toil[all]

# install cactus
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git
cd cactus
pip install --upgrade .

# compile deps
git submodule update --init
make -j 4
cd bin
export PATH=`pwd`:$PATH
cd ../examples
mkdir TMP; mkdir LOGS
cactus jobStore evolverMammals.txt mammals.hal --maxPreemptableServiceJobs 2 --maxServiceJobs 2 --maxCores 2 --logFile cactus.log --binariesMode local --workDir ./TMP --writeLogs LOGS/
```
Compilation of the dependencies ran without any particular issues. Same with the installation, no warnings/errors raised. However, when I try to run it I get the following issue:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
Using config from path /PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/site-packages/cactus/cactus_progressive_config.xml.
Traceback (most recent call last):
  File "/PATH/TO/Andrea/myanaconda/cactus2/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 474, in main
    runCactusProgressive(options)
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 489, in runCactusProgressive
    projWrapper.writeXml()
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/site-packages/cactus/progressive/projectWrapper.py", line 69, in writeXml
    self.configWrapper.writeXML(configPath)
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/site-packages/cactus/shared/configWrapper.py", line 35, in writeXML
    xmlString = ET.tostring(self.xmlRoot, encoding='unicode')
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/xml/etree/ElementTree.py", line 817, in write
    self._root, encoding, default_namespace
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/xml/etree/ElementTree.py", line 884, in _namespaces
    add_qname(tag)
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/xml/etree/ElementTree.py", line 868, in add_qname
    qnames[qname] = encode(qname)
  File "/PATH/TO/Andrea/myanaconda/cactus2/lib/python2.7/xml/etree/ElementTree.py", line 843, in encode
    return text.encode(encoding)
LookupError: unknown encoding: unicode
```

Is there a known fix for this? Am I using the wrong subversion of python? Or some module to update?

Thanks in advance
Andrea

**Comment by diekhans** [comment]
We have just converted cactus to python 3.6+.  There are
currently some rough edges in master, some were fixed today.

I don't know anything about the conda package, however if you have
kyototycoon and HDF5 installed, you should be able to get it build.

The instructions for compiling in the README.md should work,
although they do need a bit of improvement.  Let us know what
you find confusion.

**Comment by RenzoTale88** [comment]
Ok, so I'm trying to install it through both virtualenv and anaconda, but in both cases I get the following error:
```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI
toil depends on http-parser@ https://github.com/adamnovak/http-parser/archive/190a17839ba229c635b59d960579451a81fe73f3.zip#sha256=3d30c84a426627e468657c44de199daee9d3210a48e392d4ad2e7497c5010949 
```
I've also tried to install http-parser, but get the same issue. Any idea on how to proceed?
Thanks again
Andrea

**Comment by diekhans** [comment]
I haven't see the error you are getting, but it might be due to the way we
worked around the http_parser problems.

Try creating a new virtualenv and do

   pip install git+https://github.com/DataBiosphere/toil.git

if it fails, send the version of python and pip you are using.

**Comment by diekhans** [comment]
We have a developer here also getting:
  ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI

please stand by.

**Comment by RenzoTale88** [comment]
Hi sorry for the delay. I managed to install toil through compilation as suggested here:

https://toil.readthedocs.io/en/latest/gettingStarted/install.html#building-from-source

This worked without problems and now cactus run although as a stand alone job. I haven't found a way to make it work with gridEngine, but I suppose is a toil issue and not a cactus one.
Thanks again
Andrea

**Comment by diekhans** [comment]
Toil support is something we are struggling with now.  It has
turned out to be really difficult to support the various types
of HPC cluster.  Even if we support a given batch system, there
are all kinds of other issues that crop up.  NFS is very
problematic, as well as need both large and small machines.

We are looking into other solutions for paralleling the build.
In particular, breaking down the alignments into sub-problems
and run them independently on single, multi-core machines and
then combining the alignments.  We haven't worked a protocol
yet.

**Comment by RenzoTale88** [comment]
I understand the difficulties in interface with multiple HPC environments, and in my case is not a big problem. I can just submit a set of large single jobs, and make sure that the process resume at each iteration until it finishes. Thank you again for the help during the installation!

Andrea

**Comment by diekhans** [comment]
Due to various problems with the PY3 port, we have reverted master until these are fixed.

Please clean everything out and try again.
