### ISSUE TITLE
Question about ancestral genome length too short

### ISSUE THREAD

**Issue by qiqizhang01** [ComparativeGenomicsToolkit/cactus#1329]
Dear author,

We are currently utilizing Progressive Cactus to align 25 genomes from various species. However, when I used halStats to generate the ancestral genome output, I observed that the resulting ancestral sequence is too short. For instance, in the image provided, Anc05 is only approximately 68Mb in length, whereas the 16 species within its branch belong to the same family, with genome sizes ranging from 200-900Mb.

I have thoroughly reviewed the cactus logs from my run and no errors were reported. Is this outcome considered normal? Could it possibly be linked to the outgroup species (9) that I selected?

Below is the code I used:

cactus evolverjobs evolverjobs.txt evolverjobs.hal --realTimeLogging true

halStats evolverjobs.hal > evolverjobs_halStats.txt

Best regards, 

![WechatIMG1860](https://github.com/ComparativeGenomicsToolkit/cactus/assets/109807902/0076e939-477e-4036-81e3-2c4306bf21da)

**Comment by glennhickey** [comment]
I would use `halCoverage` rather than the ancestor sizes to check the alignment.  But I agree they do seem small.  Are these genomes hard masked? What's the branch length between them?
