### ISSUE TITLE
Python version 

### ISSUE THREAD

**Issue by ashlingcha** [ComparativeGenomicsToolkit/cactus#134]
Is cactus working now for python3 or is it in the middle of transitioning?

**Comment by diekhans** [comment]
We back out the changes in master because there were some problem not
caught by the tests.  We hope to get it going soon.

**Comment by ashlingcha** [comment]
I'm trying to compile from master right now and think the error is due to it needing to be in python3
`File "/tmp/easy_install-lnyCsk/more-itertools-8.2.0/more_itertools/more.py", line 480
    yield from iterable
             ^
SyntaxError: invalid syntax`

**Comment by diekhans** [comment]
This looks like some inconsistency in your python environment.
Try starting with a fresh PY2 virtualenv, make sure you are
picking up a PY2 pip, etc.

**Comment by ashlingcha** [comment]
So this file: File "/tmp/easy_install-lnyCsk/more-itertools-8.2.0/more_itertools/more.py" isn't from cactus?

**Comment by diekhans** [comment]
Not from cactus, that comes from the more-itertools package, not
sure what code brings it in.

**Comment by diekhans** [comment]
Cactus is now working on python 3.6+.

Please let us know if you have any problems
