### ISSUE TITLE
--restart did not fix failed job

### ISSUE THREAD

**Issue by scintilla9** [ComparativeGenomicsToolkit/cactus#1350]
Hi,

I'm using cactus to align few genomes, and I got error message "An invalid character was found in the first word of a fasta header".
So I changed the header accordingly, in this case, from `AADN05001177.1_Gallus_gallus_breed_Red_Jungle_fowl._inbred_line_UCD001_isolate_RJF_#256_Contig134.1._whole_genome_shotgun_sequence`  to `AADN05001177.1_Gallus_gallus_breed_Red_Jungle_fowl._inbred_line_UCD001_isolate_RJF_256_Contig134.1._whole_genome_shotgun_sequence`

However, when I run again with `--restart` the pipeline seems doesn't receive the change and still report that `AADN05001177.1_Gallus_gallus_breed_Red_Jungle_fowl._inbred_line_UCD001_isolate_RJF_#256_Contig134.1._whole_genome_shotgun_sequence` as invalid name.

I attach the log file below:
[stderr.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/14918567/stderr.log)

This there any way that I can fix this issue? or I should restart the whole process from the beginning (I prefer not to, since the process have been run for about 3 weeks)?

Any suggestion is appreciated.

**Comment by glennhickey** [comment]
No. Changes to input data and even options (except a few Toil-specific ones) will not be taken into account with `--restart`.  The good news is that it's failing at the very beginning of the pipeline, so you won't lose much rerunning from scratch.

**Comment by scintilla9** [comment]
Ok, I got it. Now I start a new run.
Thanks for clarifying.
