### ISSUE TITLE
 PermissionError In Preprocessing

### ISSUE THREAD

**Issue by mtvector** [ComparativeGenomicsToolkit/cactus#139]
Hi there,
I pulled the cactus and checked out py3 branch which appears to be working mostly, however invoking with `cactus /wynton/scratch/ms/cactusscratchsmall4 /wynton/group/ms/refdata2/cetaceans/genomelistsmall.txt /wynton/group/ms/refdata2/cetaceans/cactusout/ --binariesMode singularity --containerImage ~/utils/cactus.img `

Gives the error:

` PermissionError: [Errno 1] Operation not permitted: '/wynton/scratch/ms/cactusscratchsmall4/files/for-job/kind-RunCactusPreprocessorThenProgressiveDown/instance9u5a8c52/cleanup/file-u1tnckhr/stream' -> '/wynton/scratch/ms/tmp/tmpwfzi5hzq/job'`

Thanks for any insight on the root cause!
M

**Comment by diekhans** [comment]
Thanks for trying out the py3 branch.  It should work fine,
however there are still a few issues with Toil on Python 3
concerning Docker+AWS.  However, this doesn't appear to be the
issue you are having.


Operation not permitted (EPERM) means that you are unable to write or access a file.

From the message:
  '/wynton/scratch/ms/cactusscratchsmall4/files/for-job/kind-RunCactusPreprocessorThenProgressiveDown/instance9u5a8c52/cleanup/file-u1tnckhr/stream' -> '/wynton/scratch/ms/tmp/tmpwfzi5hzq/job'`

It looks like this might be toil attempting to create a symlink
in /wynton/scratch/ms/tmp/tmpwfzi5hzq/job. This could be an ownership, write permissions
or a read-only file system.

Please look at those directories.  Do you have more of stack trace?

**Comment by mtvector** [comment]
By more of a stack trace, do you mean the outputs with flags --debugWorker or --logDebug ?

It appears that the directories it writes have permissions 700... This shouldn't be a problem unless it's somehow running as a user other than me right? It clearly is able to write files and dirs, and everything appears to be owned by me. It's odd, I had cactus with py2 running fine using the same locations.

**Comment by diekhans** [comment]
--logDebug would help a lot. 

Toil/Cactus all run as the user that is submitting the jobs.

**Comment by mtvector** [comment]
I guess there are multiple errors going on. It's also trying to connect to the internet, but I'm not sure why since I've pointed it to everything local.

[CetaceanCactus.sh.o27829.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4182452/CetaceanCactus.sh.o27829.txt)

**Comment by diekhans** [comment]
ping toil people

**Comment by adamnovak** [comment]
Those Internet connection attempts are just the Boto module trying to talk to the AWS instance metadata service and get its credentials, on the off chance that your machine happens to be an AWS instance. If it fails, it concludes you are not an AWS instance. Boto does that when you import the module, and Toil automatically imports boto if it is installed.

If you want the messages to go away, you can unistall boto and boto3 (or not install Toil with the `aws` (or `google`?) extras).

**Comment by mtvector** [comment]
Thanks @adamnovak !

So that means the permissions is the only hold-up I guess

**Comment by DailyDreaming** [comment]
@mtvector Toil is currently tested for `python3.6`, but it appears that you're running `python3.8` with `miniconda`?  I'd recommend using `python3.6` so that we can work on one version and get it working before progressing and making sure it works on other versions (I also believe Mark has only tested cactus with `python3.6` as well).

The directories have permissions 700, but can you run: `stat -c "%U %G" /directory/path` for each of the directories to see who owns them?

**Comment by diekhans** [comment]
I have never seen this permissions issue with toil/cactus before.

Could it be something change on the cluster?  Can you please check the paths
on nodes too?

**Comment by mtvector** [comment]
I'll keep trying things... But the problem does persist on python 3.6 (see log). 

The dirs and all subdirs left behind in the created directories and in $TMP belong to me/my group. 
[CetaceanCactus.sh.o55612.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4184019/CetaceanCactus.sh.o55612.txt)
