### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by mfruzan** [ComparativeGenomicsToolkit/cactus#140]
Hi Guys,
 i get following error , i run amazon EC2 instance:

kind-PreprocessSequence/instanceZHyqbp    Unable to find image 'quay.io/comparative-genomics-toolkit/cactus:a542b9c4ca10af2c73803335bbbf7ccb8457efe1' locally
kind-PreprocessSequence/instanceZHyqbp    docker: Error response from daemon: manifest for quay.io/comparative-genomics-toolkit/cactus:a542b9c4ca10af2c73803335bbbf7ccb8457efe1 not found: manifest unknown: manifest unknown.

could you please help me fix this prob?

Thanks,
Mario

**Comment by diekhans** [comment]
cactus master was just updated, please try again

**Comment by mfruzan** [comment]
Thanks it worked!
