### ISSUE TITLE
unrecognized arguments: --maskAlpha

### ISSUE THREAD

**Issue by aaaniich** [ComparativeGenomicsToolkit/cactus#1447]
Hi, please advise, I am trying to do preprocessing as in HPRC and CPC on dna-brnn using cactus-preprocess. But I get this error: cactus-preprocess: error: unrecognised arguments: --maskAlpha. My command: cactus-preprocess jobstore prep.seqfile prep.pp.seqfile --maskAlpha --minLength 100000 --brnnCores 16 --logFile prep.pp.log

https://github.com/Shuhua-Group/Chinese-Pangenome-Consortium-Phase-I/blob/main/pipeline/protocol.md

**Comment by glennhickey** [comment]
If you want to run the same command line, you may have to roll back to the same cactus version.  Otherwise, the interface has changed a bit since then.  See `cactus-preprocess --help` 
```
 --maskMode MASKMODE   Masking mode, one of {"lastz", "brnn", "red", "none",
                        "config"}. Default="config".
  --maskAction MASKACTION
                        Masking action, one of {"softmask", "hardmask",
                        "clip"}. Default="softmask"
```
Note that `dna-brnn` is no longer a part of the pipeline by default, which is now usually run with a single invocation of `cactus-pangenome`.

**Comment by aaaniich** [comment]
> If you want to run the same command line, you may have to roll back to the same cactus version. Otherwise, the interface has changed a bit since then. See `cactus-preprocess --help`
> 
> ```
>  --maskMode MASKMODE   Masking mode, one of {"lastz", "brnn", "red", "none",
>                         "config"}. Default="config".
>   --maskAction MASKACTION
>                         Masking action, one of {"softmask", "hardmask",
>                         "clip"}. Default="softmask"
> ```
> 
> Note that `dna-brnn` is no longer a part of the pipeline by default, which is now usually run with a single invocation of `cactus-pangenome`.

Thank you so much for your reply! Sorry for the clarification, I didn't fully understand the last sentence, does dna-brnn automatically work when running cactus-pangenome or do you still have to pre-process the data with maskAction&?

**Comment by glennhickey** [comment]
No, you do not need to use dna-brnn.

**Comment by aaaniich** [comment]
> No, you do not need to use dna-brnn.

Thank you so much!
