### ISSUE TITLE
read input data (listed in seqfile) from local directory, not web location (url)?

### ISSUE THREAD

**Issue by bhdobrin** [ComparativeGenomicsToolkit/cactus#1456]
My input fasta files are not web-accessible without a login, and I do not have a means of hosting them myself at a web-accessible location.   I do not see a flag or option that would instruct the minigraph-cactus to read input file addresses (second column of the seqfile) as local directory locations. Is there such an option, or will the program interpret local addresses (provided without a url) as local?

**Comment by glennhickey** [comment]
yes, local paths are supported.

**Comment by bhdobrin** [comment]
Thanks.
