### ISSUE TITLE
failed to install cactus

### ISSUE THREAD

**Issue by zhanghaoipp** [ComparativeGenomicsToolkit/cactus#146]
I try to install in ubuntu14.04 and Centos7, but both are failed. I will be appreciate if you can help me about it, I really want to use this good software. I use anaconda as default, so I creat a environment for cactus with python3.6.7, then use the pip in conda for installation.
In ubuntu, in the cactus env, I install toil first (pip install --upgrade toil[all]) with two errors:
**ERROR: botocore 1.14.17 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
ERROR: cwltool 1.0.20190906054215 has requirement ruamel.yaml<=0.15.97,>=0.12.4, but you'll have ruamel-yaml 0.16.0 which is incompatible.**
I did not find any information to resove these problem in google. But it seems toil was installed.
Then I run pip install --upgrade .
it showed errors as:
**bac@bac-IPP:~/software/cactus$ pip install --upgrade .                                                                         master
Processing /home/bac/software/cactus
Requirement already satisfied, skipping upgrade: toil>=3.24 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from Cactus==1.0) (3.24.0)
Requirement already satisfied, skipping upgrade: decorator in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from Cactus==1.0) (4.4.1)
Requirement already satisfied, skipping upgrade: psutil in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from Cactus==1.0) (5.6.7)
Requirement already satisfied, skipping upgrade: networkx<3,>=2 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from Cactus==1.0) (2.4)
Collecting cython
  Downloading Cython-0.29.15-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 399 kB/s
Collecting pytest
  Downloading pytest-5.3.5-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 9.3 MB/s
Requirement already satisfied, skipping upgrade: addict<=2.2.0 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (2.2.0)
Requirement already satisfied, skipping upgrade: requests<3,>=2 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (2.22.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (1.14.0)
Requirement already satisfied, skipping upgrade: docker==2.5.1 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (2.5.1)
Requirement already satisfied, skipping upgrade: future in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (0.18.2)
Requirement already satisfied, skipping upgrade: dill==0.2.7.1 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (0.2.7.1)
Requirement already satisfied, skipping upgrade: pathlib2==2.3.2 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (2.3.2)
Requirement already satisfied, skipping upgrade: sphinx==1.7.5 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (1.7.5)
Requirement already satisfied, skipping upgrade: python-dateutil in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from toil>=3.24->Cactus==1.0) (2.8.1)
Collecting attrs>=17.4.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.5.0
  Downloading py-1.8.1-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 284 kB/s
Collecting wcwidth
  Downloading wcwidth-0.1.8-py2.py3-none-any.whl (17 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-1.5.0-py2.py3-none-any.whl (30 kB)
Requirement already satisfied, skipping upgrade: packaging in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from pytest->Cactus==1.0) (20.1)
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.2.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 297 kB/s
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from requests<3,>=2->toil>=3.24->Cactus==1.0) (2019.11.28)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from requests<3,>=2->toil>=3.24->Cactus==1.0) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from requests<3,>=2->toil>=3.24->Cactus==1.0) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from requests<3,>=2->toil>=3.24->Cactus==1.0) (1.25.8)
Requirement already satisfied, skipping upgrade: docker-pycreds>=0.2.1 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from docker==2.5.1->toil>=3.24->Cactus==1.0) (0.4.0)
Requirement already satisfied, skipping upgrade: websocket-client>=0.32.0 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from docker==2.5.1->toil>=3.24->Cactus==1.0) (0.57.0)
Requirement already satisfied, skipping upgrade: alabaster<0.8,>=0.7 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (0.7.12)
Requirement already satisfied, skipping upgrade: docutils>=0.11 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (0.16)
Requirement already satisfied, skipping upgrade: sphinxcontrib-websupport in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (1.2.0)
Requirement already satisfied, skipping upgrade: babel!=2.0,>=1.3 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (2.8.0)
Requirement already satisfied, skipping upgrade: Pygments>=2.0 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (2.5.2)
Requirement already satisfied, skipping upgrade: imagesize in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (1.2.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.3 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (2.11.1)
Requirement already satisfied, skipping upgrade: setuptools in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (45.2.0.post20200209)
Requirement already satisfied, skipping upgrade: snowballstemmer>=1.1 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from sphinx==1.7.5->toil>=3.24->Cactus==1.0) (2.0.0)
Collecting zipp>=0.5
  Downloading zipp-2.2.0-py36-none-any.whl (4.6 kB)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from packaging->pytest->Cactus==1.0) (2.4.6)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from babel!=2.0,>=1.3->sphinx==1.7.5->toil>=3.24->Cactus==1.0) (2019.3)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx==1.7.5->toil>=3.24->Cactus==1.0) (1.1.1)
Building wheels for collected packages: Cactus
  Building wheel for Cactus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bac/anaconda2/envs/cactus/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_3d8wnlc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_3d8wnlc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yrhmee9f
       cwd: /tmp/pip-req-build-_3d8wnlc/
  Complete output (122 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/cactus
  copying src/cactus/__init__.py -> build/lib/cactus
  creating build/lib/cactus/setup
  copying src/cactus/setup/__init__.py -> build/lib/cactus/setup
  creating build/lib/cactus/progressive
  copying src/cactus/progressive/schedule.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/__init__.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/scheduleTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/outgroup.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/multiCactusProject.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_createMultiCactusProject.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_constructFromIntermediates.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/outgroupTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_progressive.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_progressiveTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/multiCactusTreeTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/projectWrapper.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/seqFile.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/multiCactusTree.py -> build/lib/cactus/progressive
  creating build/lib/cactus/blast
  copying src/cactus/blast/upconvertCoordinates.py -> build/lib/cactus/blast
  copying src/cactus/blast/__init__.py -> build/lib/cactus/blast
  copying src/cactus/blast/blastParametersScript.py -> build/lib/cactus/blast
  copying src/cactus/blast/trimSequencesTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/mappingQualityRescoringAndFilteringTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/cactus_coverageTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/blast.py -> build/lib/cactus/blast
  copying src/cactus/blast/blastTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/trimSequences.py -> build/lib/cactus/blast
  copying src/cactus/blast/mappingQualityRescoringAndFiltering.py -> build/lib/cactus/blast
  copying src/cactus/blast/cactus_realignTest.py -> build/lib/cactus/blast
  creating build/lib/cactus/reference
  copying src/cactus/reference/cactus_referenceTest.py -> build/lib/cactus/reference
  copying src/cactus/reference/__init__.py -> build/lib/cactus/reference
  creating build/lib/cactus/shared
  copying src/cactus/shared/__init__.py -> build/lib/cactus/shared
  copying src/cactus/shared/commonTest.py -> build/lib/cactus/shared
  copying src/cactus/shared/configWrapper.py -> build/lib/cactus/shared
  copying src/cactus/shared/experimentWrapperTest.py -> build/lib/cactus/shared
  copying src/cactus/shared/test.py -> build/lib/cactus/shared
  copying src/cactus/shared/common.py -> build/lib/cactus/shared
  copying src/cactus/shared/version.py -> build/lib/cactus/shared
  copying src/cactus/shared/experimentWrapper.py -> build/lib/cactus/shared
  creating build/lib/cactus/hal
  copying src/cactus/hal/__init__.py -> build/lib/cactus/hal
  copying src/cactus/hal/cactus_halTest.py -> build/lib/cactus/hal
  creating build/lib/cactus/normalisation
  copying src/cactus/normalisation/__init__.py -> build/lib/cactus/normalisation
  copying src/cactus/normalisation/cactus_normalisationTest.py -> build/lib/cactus/normalisation
  creating build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/cactus_preprocessorTest.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/__init__.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/cactus_preprocessor.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/checkUniqueHeaders.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/preprocessorTest.py -> build/lib/cactus/preprocessor
  creating build/lib/cactus/api
  copying src/cactus/api/__init__.py -> build/lib/cactus/api
  creating build/lib/cactus/phylogeny
  copying src/cactus/phylogeny/__init__.py -> build/lib/cactus/phylogeny
  copying src/cactus/phylogeny/cactus_phylogenyTest.py -> build/lib/cactus/phylogeny
  creating build/lib/cactus/pipeline
  copying src/cactus/pipeline/__init__.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/cactus_workflowTest.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/cactus_evolverTest.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/ktserverToil.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/cactus_workflow.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/ktserverControl.py -> build/lib/cactus/pipeline
  creating build/lib/cactus/caf
  copying src/cactus/caf/__init__.py -> build/lib/cactus/caf
  creating build/lib/cactus/faces
  copying src/cactus/faces/cactus_fillAdjacenciesTest.py -> build/lib/cactus/faces
  copying src/cactus/faces/__init__.py -> build/lib/cactus/faces
  creating build/lib/cactus/bar
  copying src/cactus/bar/__init__.py -> build/lib/cactus/bar
  copying src/cactus/bar/cactus_barTest.py -> build/lib/cactus/bar
  creating build/lib/cactus/preprocessor/lastzRepeatMasking
  copying src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
  copying src/cactus/preprocessor/lastzRepeatMasking/__init__.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
  copying src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMaskTest.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
  running egg_info
  creating src/Cactus.egg-info
  writing src/Cactus.egg-info/PKG-INFO
  writing dependency_links to src/Cactus.egg-info/dependency_links.txt
  writing entry points to src/Cactus.egg-info/entry_points.txt
  writing requirements to src/Cactus.egg-info/requires.txt
  writing top-level names to src/Cactus.egg-info/top_level.txt
  writing manifest file 'src/Cactus.egg-info/SOURCES.txt'
  reading manifest file 'src/Cactus.egg-info/SOURCES.txt'
  writing manifest file 'src/Cactus.egg-info/SOURCES.txt'
  copying src/cactus/cactus_progressive_config.xml -> build/lib/cactus
  copying src/cactus/cactus_config.xml -> build/lib/cactus
  installing to build/bdist.linux-x86_64/wheel
  running install
  ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-_3d8wnlc/setup.py", line 49, in <module>
      'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-_3d8wnlc/setup.py", line 18, in run
      subprocess.run(["pip", "install", "submodules/sonLib"], check=True)
    File "/home/bac/anaconda2/envs/cactus/lib/python3.6/subprocess.py", line 418, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for Cactus
  Running setup.py clean for Cactus
Failed to build Cactus
Installing collected packages: cython, attrs, zipp, importlib-metadata, pluggy, py, wcwidth, more-itertools, pytest, Cactus
    Running setup.py install for Cactus ... error
    ERROR: Command errored out with exit status 1:
     command: /home/bac/anaconda2/envs/cactus/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_3d8wnlc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_3d8wnlc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o0w7c63k/install-record.txt --single-version-externally-managed --compile --install-headers /home/bac/anaconda2/envs/cactus/include/python3.6m/Cactus
         cwd: /tmp/pip-req-build-_3d8wnlc/
    Complete output (19 lines):
    running install
    ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_3d8wnlc/setup.py", line 49, in <module>
        'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
      File "/home/bac/anaconda2/envs/cactus/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/bac/anaconda2/envs/cactus/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-_3d8wnlc/setup.py", line 18, in run
        subprocess.run(["pip", "install", "submodules/sonLib"], check=True)
      File "/home/bac/anaconda2/envs/cactus/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/bac/anaconda2/envs/cactus/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_3d8wnlc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_3d8wnlc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o0w7c63k/install-record.txt --single-version-externally-managed --compile --install-headers /home/bac/anaconda2/envs/cactus/include/python3.6m/Cactus Check the logs for full command output.**

In Centos7, I tryed both python2.5 and python3.6 environment:
When I run 'pip install --upgrade toil[all]', I got one error:
**ERROR: botocore 1.14.17 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.**
Then after run 'pip install --upgrade .', it returned a much shorter error than ubuntu:
**(cactus) zhanghao@x86_64-conda_cos6-linux-gnu:~/software/cactus$ pip install --upgrade .
Processing /home/zhanghao/software/cactus
ERROR: Could not install packages due to an EnvironmentError: [('/home/zhanghao/software/cactus/.git/objects/pack/pack-4e9a2c1c795c6372c71afd7458c57a2f53714793.pack', '/tmp/pip-req-build-y_ebsq6b/.git/objects/pack/pack-4e9a2c1c795c6372c71afd7458c57a2f53714793.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-y_ebsq6b/.git/objects/pack/pack-4e9a2c1c795c6372c71afd7458c57a2f53714793.pack'"), ('/home/zhanghao/software/cactus/.git/objects/pack/pack-4e9a2c1c795c6372c71afd7458c57a2f53714793.idx', '/tmp/pip-req-build-y_ebsq6b/.git/objects/pack/pack-4e9a2c1c795c6372c71afd7458c57a2f53714793.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-y_ebsq6b/.git/objects/pack/pack-4e9a2c1c795c6372c71afd7458c57a2f53714793.idx'")]**

**Comment by diekhans** [comment]
hi @zhanghaoipp , this seems to be something with the condo pip not work like standard pip.
Can you try this with standard python 3.6?

Oh, and please attach log files rather than paste them in the window, it makes it much easier to read if they can just be downloaded.

**Comment by zhanghaoipp** [comment]
@diekhans thank you for your fast reply. I installed standard python3.6 in ubuntu14, because the default is 3.4. For the toil installation, it still returned an error:
ERROR: botocore 1.14.17 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
I still failed to install cactus, you can see the attached log file, it is strange that I pull the cacus master by git clone, but the folder submodules/sonLib in empty, I can see many files in the git website, I also try to download the zip file, it is also the same.
[install.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/4207688/install.log)

**Comment by zhanghaoipp** [comment]
It seems the folders in cactus/submodules are just symbolic link?

**Comment by diekhans** [comment]
the cactus/submodules are git submodules

you need to do

  git submodule update --init

to check them out.

**Comment by zhanghaoipp** [comment]
> the cactus/submodules are git submodules you need to do git submodule update --init to check them out. zhanghaoipp <notifications@github.com> writes:
> […](#)
> It seems the folders in cactus/submodules are just symbolic link? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#146 (comment)](https://github.com/ComparativeGenomicsToolkit/cactus/issues/146#issuecomment-586548174) It seems the folders in cactus/submodules are just symbolic link? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.*

It works fine now, also in conda. Thank you!

**Comment by diekhans** [comment]
good luck
