### ISSUE TITLE
A value this high likely means your data is too diverse to construct a useful pangenome graph from.

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#1475]
Dear developer:

I built a pan-genome of our different individuals using Minigraph-cactus, and he did a very good job of finding a lot of key variation information. 

But I was mistaken for ascension after adding individuals of several near-origin species. I would like to ask how we can solve this problem?

Best day!
Dong

Code：
docker run -it -v /home/test/nvmedata2/MC:/data quay.io/comparative-genomics-toolkit/cactus:v2.9.0-gpu cactus-pangenome ./js ./test.list --outDir test.result --outName test.result --reference reference --vcf --giraffe --gfa --gbz  --maxCores 96 --maxMemory 850G

WARNING: Sample Pop1 has mash distance 0.0210181 from the reference. A value this high likely means your data is too diverse to construct a useful pangenome graph from.

**Comment by glennhickey** [comment]
It gives that warning for anything over `0.02`.  You're not that far over, so it could be your data is fine.  You can check the coverage with `halCoverage` or `halStats` or `vg paths -Ev` to make sure.

**Comment by ld9866** [comment]
Thank you!
We deleted some distant individuals and everything worked out fine
