### ISSUE TITLE
same position error in vcf output file

### ISSUE THREAD

**Issue by shin0727** [ComparativeGenomicsToolkit/cactus#1477]
In order to construct the graphical genome for my datasets, i used following commands and then get the ${PREFIX}.vcf.gz output file
**commands :**
cactus-pangenome ./jobstorepath ./sequenceFile.tsv --outDir ${PREFIX1} --outName ${PREFIX1} --reference ${REF} --filter 9 --giraffe clip filter --vcf  --viz --odgi --chrom-vg clip filter --chrom-og --gbz clip filter full --gfa clip full --vcf --giraffe --gfa --gbz --chrom-vg --logFile ${PREFIX1}.log

but it contains 116,343 same position errors like below
![image](https://github.com/user-attachments/assets/cabb6cf7-a07a-4541-a545-e08cdd1df61f)

I want to know if it is error, and if it is not, i want to know why there variants are written in 2 rows?

**Comment by glennhickey** [comment]
I think this is the same problem as #1460, and is related to the fact that I added `bcftools norm` to the vcf exporter by default.  Apparently the left-shifting done by this tool can result in variants being put at the same position.  While the VCF should still be technically valid, some tools won't like it including, as the previous issue points out, PanGenie.  

I haven't had a chance to figure out how to merge these variants yet but hope to have a solution in the next release. 

In the meantime, you can revert to the old way of not normalizing by doing something like

```
sed src/cactus/cactus_progressive_config.xml -e 's/bcftoolsNorm="1"/bcftoolsNorm="0"/g' > config-nonorm.xml
```

Then running any cactus commands with `--configFile config-nonorm.xml`
