### ISSUE TITLE
 unable to write rGFA tags for path 

### ISSUE THREAD

**Issue by jinhua2024** [ComparativeGenomicsToolkit/cactus#1499]
Dear Minigraph-Cactus Development Team,

 I am a beginner in pan-genome analysis and am currently using the Minigraph-Cactus v2.9.1 pipeline for my research. Unfortunately, I have encountered an error that I cannot resolve on my own.
Here are the commands I used for the Cactus pangenome analysis:
singularity exec --bind /cactus_pangen/family_dsd_2:/cactus_pangen/family_dsd_2 /cactus_pangen/cactus:v2.9.1.sif cactus-pangenome /cactus_pangen/family_dsd_2/jobs /cactus_pangen/samples_family.txt --outDir /cactus_pangen/family_dsd_2/ --outName DSD_family_2 --reference ref_pig --workDir /cactus_pangen/workdir --logFile /cactus_pangen/family_dsd_2/run1.log --maxCores 80 --maxMemory 300G --vcf --gfa --gbz --odgi --xg --viz --draw --chrom-vg --chrom-og --collapse --permissiveContigFilter --giraffe --vcfwave

During the execution of the pipeline, I received the following error message:
"
Got exit code 1 (indicating failure) from job _toil_worker vg_to_gfa file:/assembly/cactus_pangen/family_dsd_2/jobs kind-vg_to_gfa/instance-1ovwy_yr.
Job failed with exit value 1: 'vg_to_gfa' kind-vg_to_gfa/instance-1ovwy_yr v1
...
RuntimeError: Command /usr/bin/time -f "CACTUS-LOGGED-MEMORY-IN-KB: %M" vg convert -f -Q ref_pig NC_010462.3.vg -B exited 134: stderr=terminate called after throwing an instance of 'std::runtime_error'
what():  error [gfa]: unable to write rGFA tags for path ref_pig#0#NC_010462.3[0-97459] because node 56959557 is traversed on its reverse strand.  rGFA only supports the forward strand.
"
The error appears to occur during the vg convert command, specifically related to the handling of the graph structure. I have tried increasing the available disk space for the job, but the issue persists.

Could you please provide guidance on how to resolve this error? Any insights or recommendations on how to troubleshoot this problem would be greatly appreciated.

Thank you for your assistance, and I look forward to your response.

Best regards,
jinhua

**Comment by glennhickey** [comment]
I'm not sure how this bug made it  into the release.  I just noticed it too, and fixed it [here](https://github.com/ComparativeGenomicsToolkit/cactus/pull/1498).  I'll make a patch release as soon as possible.  Until then, it looks like the `--collapse` option will *not* work.

**Comment by jinhua2024** [comment]
Thanks!!!!!

**Comment by glennhickey** [comment]
It's in [this release](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.9.2).  

The `--collapse` option remains fairly experimental.  I just noticed that it will slow down a new time of normalization (`vg paths -n`) by several hours in some cases for hprc graphs on chr9.  It shouldn't crash though, and if the slowdown is too much you can turn off pathnormalization by setting `pathNormalize="0"` in the configuration.  (`cat src/cactus/cactus_progressive_config.xml | sed -e 's/pathNormalize="1"/pathNormalize="0"/g' > config.xml` then use `--configFile config.xml`)
