### ISSUE TITLE
Could not install cactus. Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by iljungr** [ComparativeGenomicsToolkit/cactus#152]
[After writing this up, I learned that it had already been reported as issue #146. I did not find that when I searched because I searched for open issues and that issue was erroneously closed. I say, "erroneously", because the build instructions do not say that there is any need to do "git submodule update --init", so people like me and zhanghaoipp will continue to run into this. The installation instructions need to be updated before the issue can be closed.]

I am unable to install cactus. I am following the instructions here: https://github.com/ComparativeGenomicsToolkit/cactus

When I get to the step, "pip install --upgrade .", it fails with:
"ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found."

The submodules/sonLib directory is empty.

I've attached the complete output of the pip install command.

I'm doing this in the "cactus_env" virtual env, as suggested. I successfully installed toil (though it gave some error about botocore incompatibility with docutils).

I'm using python 3.6.0.
uname -a reports "Linux uger-c015.broadinstitute.org 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux"
hostnamectl reports CPE OS Name is "cpe:/o:redhat:enterprise_linux:7.6:GA:server"

[cactusInstall.out.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4246189/cactusInstall.out.txt)

**Comment by glennhickey** [comment]
You're right.  The documentation was out of date.  Should be fixed now -- sorry for the headache!
