### ISSUE TITLE
Cactus-pangenome

### ISSUE THREAD

**Issue by omakias** [ComparativeGenomicsToolkit/cactus#1527]
Hello,
I'm a bit confused, after installing the software I can't figure out how to add the cactus-pangenome I'd love to receive guidance or direction what am I missing

**Comment by glennhickey** [comment]
Which commands did you use to install the software?  What is the issue you are trying to solve, exactly?

**Comment by omakias** [comment]
I downloaded cactus precompile bins, and everything seems to be working properly..but I don't have the cactus-pangenome tool and I can't find a way to add/install it, This is a redhat 9 system

**Comment by glennhickey** [comment]
You need to follow the instructions in [BIN-INSTALL](https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.9.3/BIN-INSTALL.md) in order to install Cactus in a virtualenv.
