### ISSUE TITLE
Generating a Clipped/Filtered Graph from a {graph_name}.full.gbz file

### ISSUE THREAD

**Issue by EEEdyeah** [ComparativeGenomicsToolkit/cactus#1540]
Hello,

I have {graph_name}.full.gbz files generated from Cactus Minigraph to map short-read data. According to the tutorial, a filtered graph is more efficient for vg giraffe. Additionally, I noticed that Haplotype Sampling is a better option for vg giraffe, requiring a clipped .gbz graph and a .hapl file.

How can I generate the filtered/clipped version of the graph and haplotypes without having access to the original input files?

I tried the following steps but am not sure if they are correct: (I only have full.hal full.gbz. full.gfa files)
vg convert -g <(gunzip -c {graph_name}.full.gfa.gz) > {graph_name}.full.vg
cactus-graphmap-join --vg {graph_name}.full.vg --hal {graph_name}.full.hal --giraffe clip ...

Any suggestions or corrections to this approach would be greatly appreciated. :)

**Comment by zhangyixing3** [comment]
Hi, I think it will help you. https://github.com/ComparativeGenomicsToolkit/cactus/issues/1469

**Comment by EEEdyeah** [comment]
@zhangyixing3 Thanks! I was wondering, why do you use [vg clip] multiple times instead of putting all the parameters into a single command? Also, I noticed the first vg clip used -d 2, while the second one used -d 1. What would happen if I wanted to use -d 10 instead?

**Comment by zhangyixing3** [comment]
As a matter of fact, I learned these parameters from the test log file. The first `vg clip` is used to remove regions you don't want, while the second `vg clip` is used to remove tips from the GFA file. If you use `-d n` instead of `-d 2`, you will remove nodes that do not contain at least `n` samples, and this will simplify the GFA file.

**Comment by EEEdyeah** [comment]
@zhangyixing3 thanks！Maybe I should extract fasta files from full.gfa  and  put them into MC pipeline to reconstruct.

**Comment by EEEdyeah** [comment]
@glennhickey Thank you for your explanation! I will close this issue.
