### ISSUE TITLE
Minigraph-cactus contains a mixture of diploid and haploid genomes

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#1543]
Hello developer!
We built a pig pan-genome using Minigraph-cactus earlier, using similar parameters to humans and got very good results, but the current situation is that there are about 10 individuals with Pacbio HiFi sequencing data which makes it possible for us to try to build a haploid pig pan-genome. 

However, we don't know if it is possible to build a pangenome with 30 diploids +20 haploids, it seems to increase the diversity of genomic variation, but I don't know if it is possible, of course, it is more safe to use 40 diploid genomes, I would like to ask you what you think about this problem?
Best day!
Dong

**Comment by glennhickey** [comment]
Hi, there's nothing I can think of that prevents you from mixing haploid and diploid inputs (just make sure the diploid (and only diploid) inputs have the `.1`/`.2` suffixes on the input samples names).  We do this for human pangenomes where we include GRCh38 and CHM13 which are haploid with HPRC samples (which are diploid).

For graph construction, the haplotypes are treated pretty much independently.  So if any given haplotype is part of a diploid genome or not won't make much difference in the graph.  This is the same for most applications like, ex, `vg giraffe`.  It will make a difference in your final VCF, but only to the extent that you will have a mix of haploid and diploid genotypes. 

Hope this helps.

**Comment by ld9866** [comment]
Thank you for your help, we will carry out the test.

I have another question: Is it necessary to input the diploid genome and two haploid genomes of sample1 into the MC to build a pangenome, or is it sufficient to provide only two haploid genomes? Our current goal is to capture all genomic variations more comprehensively.

Best
Dong

**Comment by ld9866** [comment]
I see your logic, and I think I'll go ahead and test it carefully to see if the results match our expectations.
Thank you for your suggestions and answers.
Best day!
Dong
