### ISSUE TITLE
Should Cactus or Progressive Cactus  be used for genome alignment of different species. Can't we use Cactus

### ISSUE THREAD

**Issue by helloworldABCD1234** [ComparativeGenomicsToolkit/cactus#1546]
Can Cactus be used to compare genomes of different species, or can Progressive Cactus be used instead？

**Comment by glennhickey** [comment]
Yes, in general you want to use [progressive cactus](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md) for different species.
