### ISSUE TITLE
When comparing with Cactus, how to call the GPU? Why did I use the -- GPU 1 command and run it successfully, but it didn't show that the GPU was called？

### ISSUE THREAD

**Issue by helloworldABCD1234** [ComparativeGenomicsToolkit/cactus#1555]
When comparing with Cactus, how to call the GPU? Why did I use the -- GPU 1 command and run it successfully, but it didn't show that the GPU was called

**Comment by glennhickey** [comment]
If you see `run_kegalign` in your logs, then the [gpu](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#gpu-acceleration) was used.

**Comment by helloworldABCD1234** [comment]
> If you see `run_kegalign` in your logs, then the [gpu](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#gpu-acceleration) was used.

Really? May I ask what the basis for this statement is? Run_kegalign is a part of the KEGG tool used to align and map gene or protein sequences with the KEGG pathway, while Cactus is a software tool used for multi species genome alignment. The two belong to different toolsets and serve different purposes.

**Comment by helloworldABCD1234** [comment]
> If you see `run_kegalign` in your logs, then the [gpu](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#gpu-acceleration) was used.

I used Nvitop to check, but I didn't find any GPU being called. Although I used singularity -- nv and added -- GPU 1 after cactus, the running cactus still hasn't called GPU. What's going on?
