### ISSUE TITLE
Do developmental trees need to have internal nodes for comparison using Cactus? Do we need the initial root node? For example, does the developing tree below need a root? Can the last root be deleted?

### ISSUE THREAD

**Issue by helloworldABCD1234** [ComparativeGenomicsToolkit/cactus#1558]
Do developmental trees need to have internal nodes for comparison using Cactus? Do we need the initial root node? 
For example, does the developing tree below need a root? Can the last root be deleted?

(((((Human:0.006969, Chimp:0.009727)Anc10:0.025291,Rhesus:0.044568)Anc07:0.07,Tree_shrew:0.19)Anc03:0.03,(Kangaroo_rat:0.17,(Mouse:0.072818,Rat:0.081244)Anc08:0.11)Anc04:0.150342)Anc01:0.02326,((Dog:0.07,Cat:0.07)Anc05:0.087381,((Pig:0.06,Cow:0.06)Anc09:0.104728,Horse:0.05)Anc06:0.05)Anc02:0.04)root;

After removing the root, the phylogenetic tree becomes like this. The root at the end is gone

(((((Human:0.006969, Chimp:0.009727)Anc10:0.025291,Rhesus:0.044568)Anc07:0.07,Tree_shrew:0.19)Anc03:0.03,(Kangaroo_rat:0.17,(Mouse:0.072818,Rat:0.081244)Anc08:0.11)Anc04:0.150342)Anc01:0.02326,((Dog:0.07,Cat:0.07)Anc05:0.087381,((Pig:0.06,Cow:0.06)Anc09:0.104728,Horse:0.05)Anc06:0.05)Anc02:0.04);

**Comment by glennhickey** [comment]
You can find example trees here 

https://github.com/ComparativeGenomicsToolkit/cactus/tree/master/examples

and here

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#progressive-cactus-data

**Comment by helloworldABCD1234** [comment]
> You can find example trees here
> 
> https://github.com/ComparativeGenomicsToolkit/cactus/tree/master/examples
> 
> and here
> 
> https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#progressive-cactus-data

thanks
