### ISSUE TITLE
Error in installation : pip install --upgrade

### ISSUE THREAD

**Issue by evolgen** [ComparativeGenomicsToolkit/cactus#156]
Dear cactus developers,

I have been trying to install cactus to execute using the singularity mode. My local installation was not functioning properly, hence I tried to perform the pip based installation. I created a virtual_env, activated it and cloned the repository recursively.

I tried your installation guide as-is but have been facing problems at the pip install --upgrade step. I though it might be my python version but V3.6 too shows the same problem. 

ERROR: Could not install packages due to an EnvironmentError: [('/global/scratch2/Software/cactus/.git/objects/pack/pack-11dbe062dbe424f79491ec90ee
b48cce5dde5cca.idx', '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/objects/pack/pack-11dbe062dbe424f79491ec90eeb48cce5dde5cca.idx', "[Errno 13]
 Permission denied: '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/objects/pack/pack-11dbe062dbe424f79491ec90eeb48cce5dde5cca.idx'"), ('/global/
scratch2/Software/cactus/.git/objects/pack/pack-11dbe062dbe424f79491ec90eeb48cce5dde5cca.pack', '/global/scratch2/TMP/pip-req-build-pt3
e04z4/.git/objects/pack/pack-11dbe062dbe424f79491ec90eeb48cce5dde5cca.pack', "[Errno 13] Permission denied: '/global/scratch2/TMP/pip-req-build-pt3
e04z4/.git/objects/pack/pack-11dbe062dbe424f79491ec90eeb48cce5dde5cca.pack'"), ('/global/scratch2/Software/cactus/.git/modules/submodules/sonLib/ob
jects/pack/pack-a7c2db40f254131f119c6725e3b6b8fb68ea6b2f.pack', '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/modules/submodules/sonLib/objects
/pack/pack-a7c2db40f254131f119c6725e3b6b8fb68ea6b2f.pack', "[Errno 13] Permission denied: '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/modules
/submodules/sonLib/objects/pack/pack-a7c2db40f254131f119c6725e3b6b8fb68ea6b2f.pack'"), ('/global/scratch2/Software/cactus/.git/modules/submodules/s
onLib/objects/pack/pack-a7c2db40f254131f119c6725e3b6b8fb68ea6b2f.idx', '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/modules/submodules/sonLib/
objects/pack/pack-a7c2db40f254131f119c6725e3b6b8fb68ea6b2f.idx', "[Errno 13] Permission denied: '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/m
odules/submodules/sonLib/objects/pack/pack-a7c2db40f254131f119c6725e3b6b8fb68ea6b2f.idx'"), ('/global/scratch2/Software/cactus/.git/modules/submodu
les/cactus2hal/objects/pack/pack-dd13050d25c36c75a86feeab7286690f9b2e0ab6.pack', '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/modules/submodul
es/cactus2hal/objects/pack/pack-dd13050d25c36c75a86feeab7286690f9b2e0ab6.pack', "[Errno 13] Permission denied: '/global/scratch2/TMP/pip-req-build-
pt3e04z4/.git/modules/submodules/cactus2hal/objects/pack/pack-dd13050d25c36c75a86feeab7286690f9b2e0ab6.pack'"), ('/global/scratch2/Software/cactus/
.git/modules/submodules/cactus2hal/objects/pack/pack-dd13050d25c36c75a86feeab7286690f9b2e0ab6.idx', '/global/scratch2/TMP/pip-req-build-pt3e04z4/.g
it/modules/submodules/cactus2hal/objects/pack/pack-dd13050d25c36c75a86feeab7286690f9b2e0ab6.idx', "[Errno 13] Permission denied: '/global/scratch2/
TMP/pip-req-build-pt3e04z4/.git/modules/submodules/cactus2hal/objects/pack/pack-dd13050d25c36c75a86feeab7286690f9b2e0ab6.idx'"), ('/global/scratch2/Software/cactus/.git/module
s/submodules/pinchesAndCacti/objects/pack/pack-3eade9b7923419da063d9afbb02f2231302d7a0d.pack', '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/mo
dules/submodules/pinchesAndCacti/objects/pack/pack-3eade9b7923419da063d9afbb02f2231302d7a0d.pack', "[Errno 13] Permission denied: '/global/scratch2/TMP/pip-req-build-pt3e04z4/.git/modules/submodules/pinchesAndCacti/objects/pack/pack-3eade9b7923419da063d9afbb02f2231302d7a0d.pack'")]

I tried using different build and temporary directories and not using cache (--no-cache-dir) but it couldn't be solved. Could you please let me know what I am possibly doing wrong here?

Thanks in advance,
-Rohit

**Comment by petersudmant** [comment]
I  believe this  issue may be due an shutil bug that was recently fixed: 

https://github.com/python/cpython/commit/79efbb719383386051c72f2ee932eeca8e033e6b#diff-69f781dfa4a6697ad701fd742bc0d81e

I was able to reproduce the error and fix by modifying shutil by hand to fix the bug
