### ISSUE TITLE
hal2maf  --maximumBlockLengthToMerge

### ISSUE THREAD

**Issue by helloworldABCD1234** [ComparativeGenomicsToolkit/cactus#1563]
What is the appropriate setting for the "maximumBlockLengthToMerge" parameter of hal2maf when comparing 15 genomes?
What is the default value for the maximumBlockLengthToMerge parameter？

**Comment by glennhickey** [comment]
It takes the defaults from `taffy` which are currently recommended for all inputs. 

```
taffy norm -h
-m --maximumBlockLengthToMerge : Only merge together any two adjacent blocks if one or both is less than this many bases long, by default: 200
```
