### ISSUE TITLE
LAST_PYTHON2_SUPPORT tag doesn't work

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#158]
I guess there's no Docker image on quay associated with this commit:

```
 Error response from daemon: manifest for quay.io/comparative-genomics-toolkit/cactus:a542b9c4ca10af2c73803335bbbf7ccb8457efe1 not found.
```

**Comment by diekhans** [comment]
This was never pushed to quay, but can be if needed.

**Comment by glennhickey** [comment]
Yes, please!  I can't build it on my machine, and it looks like we're still not at the point where the master is working as well as this version -- so I'm reverting back to it all the time for debugging.

**Comment by glennhickey** [comment]
It would also be handy for users on older systems who want to run cactus but don't have python3.  Right now you can thankfully get away with just using `--latest` with this commit, but that surely won't always be the case.

**Comment by diekhans** [comment]
rebuilding now

**Comment by diekhans** [comment]
this might take a bit of, toil is pulling dependencies that now long work with py2, so I am going to have to do some version pinning

**Comment by glennhickey** [comment]
Perhaps just finding a commit around that time that has a matching docker
image and making a new tag would be easier?

**Comment by diekhans** [comment]
oh, cactus has never pinned a toil version, so going back to a previous commit will not help :-(

**Comment by glennhickey** [comment]
Can't we find the last Cactus commit before python3 that has a matching
Docker image, make a release/tag on that, and specify in the release notes
that it only works with toil 3.20?

**Comment by diekhans** [comment]
yes, toil 3.20 does install

**Comment by diekhans** [comment]
try  cactus branch python2-version

**Comment by glennhickey** [comment]
That branch is at commit [8813f5a014b07541b76b5bbdc9e8151697b6c0a7](https://github.com/ComparativeGenomicsToolkit/cactus/commit/8813f5a014b07541b76b5bbdc9e8151697b6c0a7).  There is no matching commit on quay: (can check by pasting in "Filter Tags" here: https://quay.io/repository/comparative-genomics-toolkit/cactus?tab=tags).  
So when I checkout that branch and run cactus, I get the error 
```
Unable to find image 'quay.io/comparative-genomics-toolkit/cactus:8813f5a014b07541b76b5bbdc9e8151697b6c0a7' locally
WARNING:toil.leader:z/K/jobEH_PgN    docker: Error response from daemon: manifest for quay.io/comparative-genomics-toolkit/cactus:8813f5a014b07541b76b5bbdc9e8151697b6c0a7 not found.
```
Surely there is an image on quay that corresponds to a recent python2.7 cactus commit though.  That's the one it would be handy to have a tag for.

**Comment by diekhans** [comment]
Oh crap, that is because I updated the doc ;-)

Please try again. We will have to spread toil version my word of mouth

**Comment by glennhickey** [comment]
That version's on quay.  Thanks.  I don't think the github release notes affect the commit, so that could be a way of publishing this and describing how to use it.

**Comment by diekhans** [comment]
Actually, we might not have an issue with Toil version.  It failed when building the docker, however if i just make a py2 venv and install the latest Toil, it works find.

**Comment by diekhans** [comment]
@glennhickey if you are happy, pls close this ticket

**Comment by glennhickey** [comment]
It won't work with the latest toil on full datasets due to the pickling error.   Would like to get a github release / note in the README before closing issue.

**Comment by diekhans** [comment]
ah yes, @glennhickey, the pickle thing is fatal.  See 

https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/python2-version-2020-02-26

**Comment by glennhickey** [comment]
Awesome, thanks!  I'm sure this will help many, myself included.
