### ISSUE TITLE
Unofficial kyoto installation

### ISSUE THREAD

**Issue by francicco** [ComparativeGenomicsToolkit/cactus#159]
Hi,

I'm trying to compile kyoto, can you help me with that?

I got this error when executing `KC_OPTIONS=--disable-lzo KT_OPTIONS=--disable-lua make`

```
ktutiltest.o:(.data.rel.ro+0x10): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x28): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x40): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x58): undefined reference to `typeinfo for kyotocabinet::Thread'
./libkyototycoon.so: undefined reference to `kyotocabinet::File::error() const'
./libkyototycoon.so: undefined reference to `kyotocabinet::DB::Visitor::NOP'
collect2: error: ld returned 1 exit status
make[1]: *** [ktutiltest] Error 1
```

Any help?
F

**Comment by glennhickey** [comment]
#148 changes Cactus's Makefile to build a custom kyoto.  It should end up in master sometime this week.  You can try it now by checking out the associated branch, "bring-back-kyoto-submodule"

**Comment by francicco** [comment]
Sorry @glennhickey, but I don't see how to change it.
F

**Comment by francicco** [comment]
I cloned the brach, modified the kyoto Makefile to link the lzo libs, but now I get this:

```
/usr/bin/ld: /home/tk19812/software/lzo-2.10/lib/liblzo2.a(lzo_crc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tk19812/software/lzo-2.10/lib/liblzo2.a(lzo1x_1.o): relocation R_X86_64_PC32 against symbol `memset@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value

```

F

**Comment by glennhickey** [comment]
Do you have root access?  If you are able to run this command (Taken from the [Dockerfile](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile)) the cactus Makefile should run through without any modifications.  
```
sudo apt-get install -y git gcc g++ build-essential python3 python3-dev zlib1g-dev wget valgrind libbz2-dev libhiredis-dev pkg-config libhdf5-dev liblzo2-dev libtokyocabinet-dev
```
The plan is to switch over kyototycoon to a static build in the very near future, which may also help with this issue.  I will make a note here when there's a PR for that.

**Comment by francicco** [comment]
I used the kyoto branch for CACUS and liked the kyoto libs. It worked. I'm struggling in other points of the make, [here](https://github.com/ComparativeGenomicsToolkit/cactus/issues/103)

**Comment by diekhans** [comment]
should be fixed by including our own copy of kyoto
