### ISSUE TITLE
Phylogenetics tree

### ISSUE THREAD

**Issue by mfruzan** [ComparativeGenomicsToolkit/cactus#163]
Hi,

How can we visualize a phylegentic tree from hal file format?

Thanks,
Mario

**Comment by glennhickey** [comment]
It's near the top of the `halStats` output in NEWICK format.  ex:
```
bin/halStats evolverMammals.hal 

hal v2.1
((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;

GenomeName, NumChildren, Length, NumSequences, NumTopSegments, NumBottomSegments
Anc0, 2, 545125, 9, 0, 14471
Anc1, 2, 569645, 6, 16862, 54019
simHuman_chr6, 0, 601863, 1, 53463, 0
mr, 2, 611571, 3, 52338, 55582
simMouse_chr6, 0, 636262, 1, 56172, 0
simRat_chr6, 0, 647215, 1, 55687, 0
Anc2, 2, 577109, 15, 17350, 57130
simCow_chr6, 0, 602619, 1, 56309, 0
simDog_chr6, 0, 593897, 1, 55990, 0
```
There are many tools to to visualize it, for example  pasting `((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;` into http://etetoolkit.org/treeview/ gives
![Screenshot from 2020-02-27 10-05-08](https://user-images.githubusercontent.com/901102/75456742-e86a0100-5948-11ea-8226-1a8a410e854d.png)
