### ISSUE TITLE
"Reissued any over long jobs" logs

### ISSUE THREAD

**Issue by francicco** [ComparativeGenomicsToolkit/cactus#181]
Hi @diekhans,

Cactus is running several hours now on a relatively small dataset using only one node of the cluster (28 cpus), and since some time, which I cannot really tell the analysis is stuck using only on cpu logging this message <Reissued any over long jobs>.

Is it normal or cactus is in a loop?

```
Issued job 'ProgressiveUp' kind-ProgressiveUp/instance9_ivrpf9 with job batch system ID: 71918 and cores: 1, disk: 2.0 G, and memory: 3.3 G
INFO:toil.worker:Redirecting logging to /tmp/toil-05ed381a-3c6d-402f-ae43-30effc1b74e8-f7a0c45e-deaf-44ec-b08f-27d9c18b7053/tmpbhiqqwu0/worker_log.txt
Job ended: 'ProgressiveUp' kind-ProgressiveUp/instance9_ivrpf9
Issued job 'ProgressiveOut' kind-ProgressiveOut/instanceuhee3gks with job batch system ID: 71919 and cores: 1, disk: 2.0 G, and memory: 3.3 G
INFO:toil.worker:Redirecting logging to /tmp/toil-05ed381a-3c6d-402f-ae43-30effc1b74e8-f7a0c45e-deaf-44ec-b08f-27d9c18b7053/tmpfmfioove/worker_log.txt
Job ended: 'ProgressiveOut' kind-ProgressiveOut/instanceuhee3gks
Issued job 'ProgressiveNext' kind-ProgressiveNext/instance5xbjg6wd with job batch system ID: 71920 and cores: 1, disk: 2.0 G, and memory: 3.3 G
INFO:toil.worker:Redirecting logging to /tmp/toil-05ed381a-3c6d-402f-ae43-30effc1b74e8-f7a0c45e-deaf-44ec-b08f-27d9c18b7053/tmpqokira4p/worker_log.txt
Job ended: 'ProgressiveNext' kind-ProgressiveNext/instance5xbjg6wd
Issued job 'ProgressiveDown' kind-ProgressiveDown/instanceo8t3ptll with job batch system ID: 71921 and cores: 1, disk: 2.0 G, and memory: 100.0 G
INFO:toil.worker:Redirecting logging to /tmp/toil-05ed381a-3c6d-402f-ae43-30effc1b74e8-f7a0c45e-deaf-44ec-b08f-27d9c18b7053/tmp_1a1tnhl/worker_log.txt
Job ended: 'ProgressiveDown' kind-ProgressiveDown/instanceo8t3ptll
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
```

Thanks,
F

**Comment by diekhans** [comment]
Do you see processes running?

> Is it normal or cactus is in a loop?

**Comment by diekhans** [comment]
The top command is a good way to look.

**Comment by francicco** [comment]
Hi @diekhans, 

I'm using htop and there's only one cpu running. Here's a screenshot

![Screen Shot 2020-03-20 at 14 30 27](https://user-images.githubusercontent.com/9006870/77173454-72743800-6ab7-11ea-8ed8-819205c5ac76.png)

F

**Comment by diekhans** [comment]
It is just in a long running, single process state.

I think the "Reissued any over long jobs" message is a
bit confusing, as it didn't seem to actually reissue jobs.

**Comment by glennhickey** [comment]
171 hours for a single `cactus_reference` invocation seems quite long for a "relatively small dataset".  Is your input repeat masked?

**Comment by francicco** [comment]
@glennhickey,
Yes it is
So, shell I keep it contninue?
F

**Comment by diekhans** [comment]
lets let it go another day and see what happens

**Comment by francicco** [comment]
okey!

**Comment by diekhans** [comment]
I looked at your the fasta files you have given me previously
and the fraction repeat masked for all your genomes is around 7%.


Is this to be expected for ants?  How did you repeat mask?

Mark

**Comment by francicco** [comment]
RepeatMasker Combined Database: Dfam_Consensus-20170127, RepBase-20170127
run with rmblastn version 2.2.27+

I did it few months ago, I can try to rerun it with a new database. These are ants by the way, and their genome is relatively small.

F

**Comment by diekhans** [comment]
RebBase is very bias toward mammals; I don't know about dfam.

I would suggest trying seedmasker (http://www.drive5.com/seedmasker/)
and see if it produces radically different results.  It looks for
over-represented kmers instead of annotating repeats.

If seedmasker covers a significantly larger part of the genome,
you might try it.

**Comment by francicco** [comment]
Hi @diekhans,

I tried to install seedmasker but I got a compilation error, meanwhile,
this is the repetitive element overview across ants, I did few months ago

![Screen Shot 2020-03-21 at 10 10 42](https://user-images.githubusercontent.com/9006870/77224337-78702480-6b5c-11ea-9696-d966ac1226ec.png)

The species in the alignment are Talp, Tpar, Tsim, Tbib, Timm and Veme.

I'm trying to re run repeatMasker with another DB but for some reason it's not working.

F

**Comment by diekhans** [comment]
It seems like seedmasker has not kept up with C++.

You might try WindowMasker
  https://academic.oup.com/bioinformatics/article/22/2/134/424703

**Comment by francicco** [comment]
Thanks

I'm also trying to use RepeatModeller, to find new repeats in ants. Apparently there's not much.
The run is still there...
F

**Comment by francicco** [comment]
WindowMasker it's not very intuitive to use...
F

**Comment by diekhans** [comment]
Who ever did the assemblies should be knowledgeable of the
repeat structure.

**Comment by diekhans** [comment]
I have never run in.  The description pages for the
ucsc browser tracks show how they run programs

They also have this very useful program maskOutFa
to take allow taking masking from multiple sources.

They also use TRF.

**Comment by francicco** [comment]
I assembled those assemblies :D
Now you are douting I did a good job. Actually I just published them! ;)
https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msaa076/5809148

F

**Comment by diekhans** [comment]
you are the world expert!

Repetitive DNA that can cause alignments to take forever is not
the same as transposon content.  Us mammal-centric people use
transposon annotation just because we always have.



Francesco Cicconardi <notifications@github.com> writes:
> I assembled those assemblies :D
> Now you are douting I did a good job. Actually I just published them! ;)
 https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msaa076/5809148

**Comment by francicco** [comment]
> you are the world expert!

No I'm not! :D

I'm gonna try to look for those regions, but keep in mind that I already aligned those genomes with cactus months ago. Now I'm repeating it just to check the pipeline and understand the performance over different clusters. So it should work.
F

**Comment by diekhans** [comment]
oh yes, I forgot you had previous aligned them.  Is this
system significantly slower that your old one?

**Comment by francicco** [comment]
If it doesn't go further yes.
F

**Comment by glennhickey** [comment]
Are you using `--configFile`.  There is a known regression #151  where this option doesn't work properly anymore.

Another regression was patched in #160 . Without this patch, the branch lengths in your tree are incorrectly fed to the lastz-masking preprocessor.  I don't think it's likely, but it in theory could affect the runtime. 

That's all I can think of in terms of *known* regressions since you last ran.  I'd asked about repeatmasking because self-alignments can lead to sequence graphs with few 3-connected components, which in turn blows up runtime of individual commands.  

Even just [trf](https://tandem.bu.edu/trf/trf.download.html) (as @diekhans mentioned)  may help if you're not already running something like it to softmask.  It's very easy to run.

Something's going terribly wrong for it to be running `cactus_reference` for 171 hours.  I did a human-chimp alignment the other day and that command never took more than 20min.  

It does remind me: I'd like to change the temporary filenames to be more informative so someone can use `top` to see which genomes are being aligned.  That could be useful here, for example.

**Comment by francicco** [comment]
Hi @glennhickey,

>Are you using --configFile. There is a known regression #151 where this option doesn't work properly anymore.

No I'm not.

The job is approaching the walltime. I'll resubmit the same job, resuming it. Let's see what happens.

Thanks a lot
F

**Comment by francicco** [comment]
Hi,

Cactus got stuck at the same point...

```
Job ended: 'CactusReferenceRecursion' kind-CactusReferenceRecursion/instanceg76whn6c
Issued job 'CactusReferenceWrapper' kind-CactusReferenceWrapper/instancererhoinc with job batch system ID: 5 and cores: 1, disk: 2.0 G, and memory: 1.1 G
INFO:toil.worker:Redirecting logging to /tmp/toil-05ed381a-3c6d-402f-ae43-30effc1b74e8-dc4088fa-b491-42ca-b84d-5d8df7945613/tmpopc58c8a/worker_log.txt
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
```

**Comment by glennhickey** [comment]
Would you be able to confirm if it works with https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/python2-version-2020-02-26 ?  It would help us determine if it's a regression or something else.

**Comment by francicco** [comment]
I'm actually using the Python 3.7.3! 
```
(cactus_env) [tk19812@bc4login3 cactus]$ python --version
Python 3.7.3
```
F

**Comment by glennhickey** [comment]
Two things:  If you could try it with the 2.7 release, it would be able to tell us if it's a regression or not.  If you want to try python 3,  please do a fresh clone of master, build from scratch, and follow the README directions exactly (which say `virtualenv -p python3.6 cactus_env`).  I'm worried there's something wrong with your `ktserver` build/installation, which would hopefully be corrected by a fresh build (and please uninstall any other versions of `ktesrver` from your system).

**Comment by francicco** [comment]
Ok, I'll give it a try. But I'm gonna do it immediately. Maybe tomorrow.
What do you want me to try first, Python2 or the reinstallation of everything?
Thanks a lot
F

**Comment by glennhickey** [comment]
I think the python2 would be most informative.   Also, if you can share all the inputs, I'll try as well, bit that won't be immediate either.

**Comment by francicco** [comment]
I think @diekhans should still have it, right?
I'll try with python2 first!
Thanks again
F

**Comment by diekhans** [comment]
I have most of the FASTAs; although there was at least one that
was different.

@francicco, can you please send me the md5 sums of the fasta files you
are using.  If we are going to try to reproduce this here, it would be good
to make sure we have exactly what you are using.

**Comment by ScientistJake** [comment]
Hi all,
I'm having the same problem.
```
Issued job 'CactusReferenceRecursion' kind-CactusReferenceRecursion/instancedjfje46u with job batch system ID: 9989 and cores: 1, disk: 2.0 G, and memory: 2.0 G
INFO:toil.worker:Redirecting logging to /tmp/toil-25f62921-be3d-4852-a666-583447d408ab-66349697c3404d1480ce796e071d683c/tmp82qd44x6/worker_log.txt
Job ended: 'CactusReferenceRecursion' kind-CactusReferenceRecursion/instancedjfje46u
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
Reissued any over long jobs
```
Been like that for a couple days now.

![Screen Shot 2020-03-30 at 2 16 36 PM](https://user-images.githubusercontent.com/19911333/77946933-1a94b880-7291-11ea-9546-2b8cd5766c29.png)

**Comment by glennhickey** [comment]
@joelarmstrong @benedictpaten Does this look familiar to either of you guys?  Where `cactus_reference` just runs forever?  I still don't know if it's a recent regression or something else.  
@diekhans have you been able to reproduce?  If not, can you share Francicco's data with me so I can try?

**Comment by francicco** [comment]
I was extremely busy these days I wasn't able to reinstall anything, but the runs are still running, same point.
I haven't sent the md5 to @diekhans, but if it's a bug should come up with the files he has
F

**Comment by diekhans** [comment]
@francicco go ahead and kill the jobs.  If you can take the time to verify that we have the same files, as the was a discrepancy last time, then you can have the alignment we build if we finish it.

**Comment by francicco** [comment]
The only difference is that Talp (the reference) is repeated twice. I'm doing that because I wanted to annotate the extra genes on the reference too, and since CAT does not add extra annotations on the reference, adding the same genome as non-reference I should get around the problem.

So, you can run the dataset you have. You should be able to find the same bug.
F

**Comment by ScientistJake** [comment]
Hey all,
I was going to test the python2 version but I'm struggling with the install:
```
pip install --upgrade .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /home/warnerj/cactuspy2/cactus
    ERROR: Command errored out with exit status 1:
     command: /home/warnerj/cactuspy2/cactus/cactus_env/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ecLbQf/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ecLbQf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-ecLbQf/pip-egg-info
         cwd: /tmp/pip-req-build-ecLbQf/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ecLbQf/setup.py", line 10, in <module>
        git_commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'], encoding="ascii").strip()
      File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'encoding'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by diekhans** [comment]
This appears to be that you are using the 3.* master of cactus,
as the subprocess.check_output call in setup.py is not part of the
of the branch python2-version

**Comment by ScientistJake** [comment]
@diekhans oh shoot you're right, I had cloned the 3.* cactus. I was trying to find a way to clone the 2.6 version because when I tried to install 2.6 I got an error about no get. See below:

```
$ tar xvzf python2-version-2020-02-26.tar.gz
$ cd python2-version-2020-02-26
$ virtualenv -p /usr/bin/python2.7 cactus_env
$ source cactus_env/bin/activate
$ pip install --upgrade toil[all]==3.20.0
$ pip install --upgrade .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /home/warnerj/cactuspy2/cactus-python2-version-2020-02-26
    ERROR: Command errored out with exit status 1:
     command: /home/warnerj/cactuspy2/cactus-python2-version-2020-02-26/cactus_env/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-D0vuxl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-D0vuxl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-D0vuxl/pip-egg-info
         cwd: /tmp/pip-req-build-D0vuxl/
    Complete output (8 lines):
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-D0vuxl/setup.py", line 8, in <module>
        git_commit = subprocess.check_output(['git', 'rev-parse', 'HEAD']).strip()
      File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by diekhans** [comment]
you need to be in the cactus directory for git to work

**Comment by glennhickey** [comment]
I was able to run this data through successfully, on a fresh install within a Ubuntu 18.04 docker image (master branch circa 2 days ago) using singleMachine and localBinaries.  I did it step by step though using `cactus-prepare` then executing all the resulting commands in a shell script.  I did it this way, because I was working on `cactus-prepare` for other reasons, and I figured if I could trigger the error using it, it would be easier to debug.  Each call had 90 cores and 200G RAM and 1.5T disk to work with, and it took about 2 days to run in series this way.  

I will try again with a single `cactus` command, but in theory the result should be no different.

**Comment by ScientistJake** [comment]
> you need to be in the cactus directory for git to work 
I was but since the python2-version-2020-02-26.tar.gz is not a repository I guess `pip install --upgrade .` doesn't work?

**Comment by ScientistJake** [comment]
Update:  I installed a fresh copy of cactus (see below for last commit). I used the Dockerfile as a guide to re-install dependencies and compile. Then I ran with `--binariesMode local` and it finished without errors.  

However, when I re-ran the same dataset using the default mode of docker compiled binaries it ran into the same issue as above:
```
INFO:toil.worker:Redirecting logging to /tmp/toil-300912db-7370-409b-80c5-c6af44cbddb6-66349697c3404d1480ce796e071d683c/tmpkqm9igis/worker_log.txt
Job ended: 'CactusReferenceRecursion' kind-CactusReferenceRecursion/instance4bjw4bo4
Reissued any over long jobs. 
```

So there's another datapoint.  Works fine with binariesMode local but not using the default docker mode.  This is the current version:  
```
git log
commit 4401b25651b42f432b4e268ab5dbf684ac143066 (HEAD -> master, origin/master, origin/HEAD)
Merge: 999b0e12 0e848fb5
Author: Glenn Hickey <glennhickey@users.noreply.github.com>
Date:   Tue Apr 7 18:34:21 2020 -0400

    Merge pull request #206 from ComparativeGenomicsToolkit/prepare
    
    Option to only decompose preprocessing in cactus-prepare
```

**Comment by glennhickey** [comment]
That's too weird.  One note: `--binariesMode` will now default to local if the local binaries are found.  In hindsight, it doesn't seem like I updated all sections of the README to reflect this, so I'll have to fix it.  I like to use the `--realTimeLogging` option, which spits out all the command lines run and makes it apparent if docker is used or not. 

But this also maybe explains why I was never able to reproduce this, as I've always been trying with `--binariesMode local`.  I will try with docker.  Thanks!

**Comment by glennhickey** [comment]
I think I have a way to reproduce.  In my instance it's getting stuck in this loop: https://github.com/ComparativeGenomicsToolkit/matchingAndOrdering/blob/master/impl/referenceProblem2.c#L847-L854.  I see there's an `assert` in there, but also that cactus gets compiled with `-DNDEBUG`.  I'm re-running with more logging and asserts on.  

I think in general, we should be building with asserts on.

**Comment by glennhickey** [comment]
Some progress.  In the case I'm looking at, 0-length branches in the tree seem to be causing `score` computed here to be `nan` as `pathLength` is 0.  

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/reference/impl/buildReference.c#L233-L238

This trips an assert, but goes uncaught when compiled without asserts.
