### ISSUE TITLE
Move file paths out of XML!

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#189]
There's a bit of technical debt (thanks in no small part to me!) that needs paying back with regards to all the various XML configuration files.  The main problem is that paths are being embedded inside them.  Often as toil IDs cast to strings.  And to make matters worse, XML files contain paths to other XML files.  

This has already cost me a ton of time just in trying to hack changes into the existing functionality, ex #178 #186.  Before any further changes, I think we need to at a minimum
* remove all paths out of the XML files and wrappers, and pass toil IDs around explicitly
Ideally we'd also
* Flatten everything into two structures
     * configuraiton : I tihnk this can stay unchanged as config.xml / ConfigWrapper
     * everything else : flatten experiment and project and everything in between into one structure.  and never pass around a path to this structure -- rely 100% on toil pickling to pass it from job to job as a parameter.  Let it produce strings of XML as needed on the fly by the various `cactus_` command lines.

**Comment by diekhans** [comment]
the only way to not create technical debt is to no do anything ;-)

I like your approach.

Feel free to ask me to help with any piece
