### ISSUE TITLE
Option for static build

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#190]
I'm trying to formalize the release process here: 

https://github.com/ComparativeGenomicsToolkit/cactus/wiki/Releases

which will include a binary release package.  It works well enough so far, but the binaries all depend on all the [runtime dependencies](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile#L18-L19) for dynamic linking, which defeats most of the purpose.  

So I'd like to add a `make static` (don't really care if it's the default mode and not an option) that just bakes everything into each binary.  It'll blow up the package size, but I don't think there's much choice.  @diekhans any help with this endeavor would be greatly appreciated!!!

**Comment by diekhans** [comment]
I will give it a go.

**Comment by diekhans** [comment]
branch will be issues/190/static-build

this will also address #188, as having a mix of standard and non-standard make variables makes it all harder.

**Comment by glennhickey** [comment]
Thanks!  #188 would also let us add something like `-march=nehalem` which would be a big help for the binary/docker release as well.

**Comment by glennhickey** [comment]
I guess if the size gets too out of control, we could change cactus and hal to have a single binary each, like `cactus_coverage` would become `cactus coverage` and `halStats` would be `hal stats`.  This would have drastic space savings even for the dynamic build and docker.  I don't think that would be too huge a refactor, especially if we make aliases or wrappers or whatever so `halStats` maps back to `hal stats`.

**Comment by diekhans** [comment]
linking with static HDF5 libraries does lead to huge executables.  However, for some reason, h5c++ always links with static HDF5, even if other libraries are shared.  So we have been living with huge executables for a long time.   I don't think we should worry about it.
