### ISSUE TITLE
kyoto tycoon linking error

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#203]
This happens on my desktop as well as a fresh Ubuntu 18.04 AWS instance:  When I build and run the latest master, I get linker errors if I don't add `cactus/lib` to the `LD_LIBRARY_PATH`.   I'm completely flummoxed as to why this happens to me but not gitlab.  

```
cactus_blast_chunkSequences: error while loading shared libraries: libkyototycoon.so.2: cannot open shared object file: No such file or directory
```

**Comment by diekhans** [comment]
this sounds like -rpath isn't getting set for kt stuff.  

the Dockerfile puts the library in /usr/local/lib, which is most likely in the default library search path.

I will take a  look

**Comment by glennhickey** [comment]
Thanks for taking a look.  

I'm still confused about gitlab, as it runs a local-binaries test, and it seems to go through.

Also, there's no reason I understand for the Dockerfile to be copying cactus/lib to user/local.  The only thing in there is the kyoto libraries, and those shoudl be statically linked, right?

**Comment by glennhickey** [comment]
This seems to be a deliberate change: https://github.com/ComparativeGenomicsToolkit/cactus/commit/67ef06a9b8541c0b0ca4d4d714dfed55b345cd1a

Is the idea that kyoto has reverted back to dynamic linking except for `make static`?

**Comment by diekhans** [comment]
I am working on it now.  kyoto is not static linked unless everything is static.  I am not sure what it did before. the make variables were standardized.

**Comment by diekhans** [comment]
although it might be better just to force Kyoto to be static, as that would allow copying around without LD_LIBRARY_PATH being set.

**Comment by glennhickey** [comment]
Yes please for kyto staying  static all the time.  It simplified things.  Especialyl since, if I understand, the full static build doesn't work on Ubuntu.

**Comment by diekhans** [comment]
Fixed, waiting on tests.  This wasn't even intentional.  sigh ..

**Comment by diekhans** [comment]
travis passes, but Kub seems backed up.  Free free to merge if you are in a hurry

**Comment by glennhickey** [comment]
Thanks!  No rush to merge before it goes through tests..  

I'm still confused at how the gitlab tests passed.  It's supposed to be running a local build for one of them, and wasn't setting LD_LIBRARY_PATH or copying /lib that I can seee.

**Comment by diekhans** [comment]
Docker was putting shared libraries in /usr/local/lib/ along with
kyoto configures add this to rpath by default.  Either one is sufficient
for them to automatically be picked up without LD_LIBRARY_PATH.  I assume
this is what is doing on.

This would be the desired behavior if building a standard package.
