### ISSUE TITLE
cactus docker doesn't have HAL python libraries

### ISSUE THREAD

**Issue by diekhans** [ComparativeGenomicsToolkit/cactus#225]
Might not be in binary distribution either

see https://github.com/ComparativeGenomicsToolkit/hal/issues/108#issuecomment-620814684

**Comment by glennhickey** [comment]
I'm going to guess this is a problem with the binary release as well.

**Comment by diekhans** [comment]
from: https://github.com/ComparativeGenomicsToolkit/hal/issues/108#issuecomment-620826169

> OK, that would be great. hal2assemblyHub.py also requires several UCSC "kent" utilities that aren't in the image (see https://github.com/harvardinformatics/hal/commit/a489622025155fba70675108fce2fcd65b2fc990 for a list I had grepped from the assemblyHub python library; note that the procedure for building from source may differ for ubuntu:18.04)

**Comment by nathanweeks** [comment]
Slightly off topic (but not sure it's worth filing a new issue for): in addition to missing the HAL python libraries, the cactus binary release includes a 41 MB .git directory that needn't be there.

**Comment by glennhickey** [comment]
should be resolved as of 1.1.0
