### ISSUE TITLE
Issue with pip install in virtual environment 

### ISSUE THREAD

**Issue by MilesLuca** [ComparativeGenomicsToolkit/cactus#227]
Dear cactus developers,

I have been trying to follow the installation guide through the virtual environment, but consistently run into the following error:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'toil-requirement.txt'

Any idea what might be going wrong?

Thanks!

**Comment by diekhans** [comment]
Are you trying to install from source or the binary tar file?
Can you give more information on the steps you are taking?

toil-requirement.txt is in the top-level directory of the cactus source tree.

**Comment by MilesLuca** [comment]
Hello,

Apologies and thanks for your patience.
I am trying to follow the set-up instructions on the main page, and simply following the commands step by step.

So I have created the virtual environment but when I try to run:

pip install --upgrade -r toil-requirement.txt

I get the error mentioned above.

**Comment by diekhans** [comment]
We need to improve the readme.  That should really come after
the cloning cactus, as it has the toil-requirement.txt in it.


Please get cactus first.

**Comment by glennhickey** [comment]
Oops, my bad.  I'd replaced the installation command to use that file, but
needed to move it after the git clone command.  Thanks for raising this
issue.  The installation instructions are fixed and simplified here:

https://github.com/ComparativeGenomicsToolkit/cactus/pull/228
