### ISSUE TITLE
Cactus using excessive memory 

### ISSUE THREAD

**Issue by drabe004** [ComparativeGenomicsToolkit/cactus#252]
We've been trying to run cactus and had a previous issue with cactus corrupting the .fasta file genome headers from NCBI. We resolved that issue running a sed command on all genomes to remove comments from the fasta header: sed -e '/>/s/ .*$//'

Now cactus runs, but it will run out of walltime on our largest node at around 5000 hours: 

[Error and debug files.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/4689766/Error.and.debug.files.zip)

Job Id: 21025103.mesabim1.msi.umn.edu
    Job_Name = Cactus5_fish
    Job_Owner = drabe004@ln1001.mangi.msi.umn.edu
    resources_used.cput = 3263:52:57
    resources_used.energy_used = 0
    resources_used.mem = 88106856kb
    resources_used.vmem = 101602432kb
    resources_used.walltime = 96:00:23
    job_state = C
    queue = amd2tb
    server = mesabihn1.msi.umn.edu
    Account_Name = mcgaughs
    Checkpoint = u
    ctime = Fri May 22 17:05:52 2020
    Error_Path = ln1001:/home/mcgaughs/drabe004/CF_genomes/Cactus5_fish_error2

    exec_host = cn1110/0-127
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = abe
    Mail_Users = drabe004@umn.edu
    mtime = Wed May 27 07:39:21 2020
    Output_Path = ln1001.mangi.msi.umn.edu:/panfs/roc/groups/14/mcgaughs/drabe
        004/CF_genomes/Cactus5_fish.o21025103
    Priority = 0
    qtime = Fri May 22 17:05:52 2020
    Rerunable = True
    Resource_List.nodes = 1:ppn=128
    Resource_List.mem = 2000gb
    Resource_List.walltime = 96:00:00
    Resource_List.nodect = 1
    session_id = 0
    Variable_List = PBS_O_QUEUE=amd2tb,PBS_O_HOME=/home/mcgaughs/drabe004,
        PBS_O_LOGNAME=drabe004,
        PBS_O_PATH=/usr/local/bin:/usr/local/sbin:/opt/msi/bin:/usr/share/Mod
        ules/bin:/opt/moab/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sb
        in:/opt/ibutils/bin:/opt/puppetlabs/bin,
        PBS_O_MAIL=/var/spool/mail/drabe004,PBS_O_SHELL=/bin/bash,
        PBS_O_LANG=en_US.UTF-8,
        PBS_O_SUBMIT_FILTER=/opt/msi/bin/torque-filter.py,
        PBS_O_WORKDIR=/panfs/roc/groups/14/mcgaughs/drabe004/CF_genomes,
        PBS_O_HOST=ln1001.mangi.msi.umn.edu,
        PBS_O_SERVER=mesabim1.msi.umn.edu
    euser = drabe004
    egroup = mcgaughs
    queue_type = E
    etime = Fri May 22 17:05:52 2020
    exit_status = -11
    submit_args = runCactusLocal_simple.sh
    start_time = Sat May 23 07:38:38 2020
    start_count = 1
    fault_tolerant = False
    comp_time = Wed May 27 07:39:21 2020
    job_radix = 0
    total_runtime = 1590583161.620812
    submit_host = ln1001.mangi.msi.umn.edu
    init_work_dir = /panfs/roc/groups/14/mcgaughs/drabe004/CF_genomes
    request_version = 1
    req_information.task_count.0 = 1
    req_information.lprocs.0 = 128
    req_information.total_memory.0 = 2097152000kb
    req_information.memory.0 = 2097152000kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = cn1110:ppn=128
    req_information.task_usage.0.task.0.cpu_list = 0-127
    req_information.task_usage.0.task.0.mem_list = 0-1
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 128
    req_information.task_usage.0.task.0.host = cn1110

**Comment by diekhans** [comment]
are your genomes repeat masked?

**Comment by drabe004** [comment]
HI Mark, 
Woops-- this time it was my blunder... I thought they were but in fact two were not. I'm re-running the 3 genomes that are not to be sure that this was the issue, but it likely is!
