### ISSUE TITLE
Cannot find the "cactus" and "cactus-prepare" executable after building from source

### ISSUE THREAD

**Issue by dbxmcf** [ComparativeGenomicsToolkit/cactus#264]
To whom it may concern:

I believe I have successfully built the cactus from source following the steps (not using the docker) on a ubuntu 16.04 os:

```
dbxmcf@dbxmcf-tcm710s:~ $ sudo apt-get update && apt-get install -y build-essential git python3 python3-dev python3-pip zlib1g-dev wget libbz2-d    ev pkg-config libhdf5-dev liblzo2-dev libtokyocabinet-dev
dbxmcf@dbxmcf-tcm710s:~ $ git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
dbxmcf@dbxmcf-tcm710s:~/cactus$ cd cactus
dbxmcf@dbxmcf-tcm710s:~/cactus$ make -j8
...lots of output...
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dbxmcf/cactus/submodules/cactus2hal'
mkdir -p bin
ln -f submodules/cactus2hal/bin/* bin/
make[1]: Leaving directory '/home/dbxmcf/cactus'
dbxmcf@dbxmcf-tcm710s:~/cactus$ ls bin/
blockVizBed                                  cPecanLibTests                 halSynteny
blockVizMaf                                  cPecanModifyHmm                halTestGen
blockVizTest                                 cPecanRealign                  halTopSegmentTest
blossom5                                     dbTestScript                   halTreeNIBackground.py
blossom_randGraph.py                         docker_test_script             halTreeNIConservation.py
cactus2hal.py                                findRegionsExclusivelyInGroup  halTreeNITurnover.py
...
dbxmcf@dbxmcf-tcm710s:~/cactus$ ls bin/cactus
ls: cannot access 'bin/cactus': No such file or directory
```
However, I cannot find the "cactus" or "cactus-prepare" script/executable in the ~/cactus/bin directory which appears in the docker image path /usr/local/bin/cactus, which is supposed to be used to run the example command:

`cactus <jobStorePath> <seqFile> <outputHal>`

Did I miss any steps in making and building of the cactus package? How are the executable scripts "cactus" or "cactus-prepare" generated and installed?

Thanks a lot for your help!

Roy

**Comment by glennhickey** [comment]
You need to install with pip.  Please refer to the instructions in the
README:
https://github.com/ComparativeGenomicsToolkit/cactus#build-from-source

**Comment by dbxmcf** [comment]
Thanks for your response, however the instructions just said:

"In the top level cactus directory. The binaries can then be built with

make -j $(nproc)
and added to the PATH with

export PATH=$(pwd)/bin:$PATH"

I tried using:

pip install --upgrade .

but the executable scripts are still not there,

Could you please be a bit more specific on what pip install command I should run after a successful make? Thanks a lot!

Roy

**Comment by dbxmcf** [comment]
Thanks, found them in miniconda3/bin eventually.
