### ISSUE TITLE
pkg-config for kyoto-*

### ISSUE THREAD

**Issue by muffato** [ComparativeGenomicsToolkit/cactus#27]
Hi again,

Sorry I've been spamming you with so many questions ! My next one is regarding kyoto-* and having to update `sonLib/include.mk`
Is there a reason why it has to be edited by hand rather than automatically detected with `pkg-config` (like _hiredis_) ? Here I'm using linuxbrew to install kyoto-* so they're installed in a location that's not hardcoded in the makefile, but pkg-config is configured correctly and I can use it to find all the paths that are needed.

If you don't have any objections, I can amend the makefile (with another `else` after the hard-coded paths, to make sure they still work) and make a pull-request

**Comment by muffato** [comment]
I've tried using pkg-config and it seems to work both in my linuxbrew environment and a standard Ubuntu install, meaning that the section
```
else ifneq ($(wildcard /usr/include/ktcommon.h),)
   # /usr install (Ubuntu)
```
(and the equivalent for kyoto-cabinet) could go away at the same time

However, I don't know on which branch of sonLib I should issue the pull-request

**Comment by muffato** [comment]
On which branch of sonLib should I create the pull-request ?

**Comment by joelarmstrong** [comment]
Hey Matthieu,

Sorry about that! I thought I replied to that weeks ago! The proper sonLib branch is `toil-split-records`.

**Comment by muffato** [comment]
This issue can be closed. See PR https://github.com/ComparativeGenomicsToolkit/sonLib/pull/4
