### ISSUE TITLE
Running step by step missing output file

### ISSUE THREAD

**Issue by lainnorton** [ComparativeGenomicsToolkit/cactus#270]
I used four species to try to run Cactus separately with each step. After Cactus-prepare, three Alignment rounds were produced, and I successfully completed the first round.

But the result after the second round of cactus-blast was missing the "Anc1.cigar.ig_coverage_1" file which needed for the next step cactus-align. 

I ran Cactus-blast again and confirmed the completion of this step in the log file. But the output is exactly the same as last time. 

May I ask how this situation should be resolved? The following is the error message while running Cactus-align:

node1 2020-07-09 21:39:36,383 MainThread INFO cactus.progressive.projectWrapper: Using config from path /public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/cactus/cactus_progressive_config.xml.
node1 2020-07-09 21:39:36,660 MainThread INFO toil.lib.bioio: xmlRoot = <multi_cactus inputSequences="output/xs_id.fa output/hhh_id.faoutput/hxx_id.fa output/human_id.fa" inputSequenceNames="xs hhh hxx human">
	<tree>(xs:89.82318742,(hhh:29.44154682,(hxx:6.650905,human:6.650905)Anc2:22.79064182)Anc1:60.3816406)Anc0;</tree>
	<cactus name="Anc0" experiment_path="/tmp/tmp6bbau6nm/progressiveAlignment/Anc0/Anc0_experiment.xml" />
	<cactus name="Anc1" experiment_path="/tmp/tmp6bbau6nm/progressiveAlignment/Anc1/Anc1_experiment.xml" />
	<cactus name="Anc2" experiment_path="/tmp/tmp6bbau6nm/progressiveAlignment/Anc2/Anc2_experiment.xml" />
</multi_cactus>
Traceback (most recent call last):
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/bin/cactus-align", line 8, in <module>
    sys.exit(main())
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/cactus/setup/cactus_align.py", line 122, in main
    runCactusAfterBlastOnly(options)
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/cactus/setup/cactus_align.py", line 254, in runCactusAfterBlastOnly
    workFlowArgs.ingroupCoverageIDs.append(toil.importFile(makeURL(get_input_path('.ig_coverage_{}'.format(i)))))
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1008, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName)
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/toil/jobStores/abstractJobStore.py", line 305, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink)
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 282, in _importFile
    self._copyOrLink(url, absPath)
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 275, in _copyOrLink
    atomic_copy(srcPath, destPath)
  File "/public/home/liyongxin/lihaorong/soft/cactus-bin-v1.0.0/cactus_env/lib/python3.8/site-packages/toil/lib/misc.py", line 238, inatomic_copy
    shutil.copyfile(src_path, dest_path_tmp)
  File "/public/home/liyongxin/lihaorong/soft/Python-3.8.3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/liyongxin/lihaorong/new_gene/lingzhang/cactus_by_step/output/Anc1.cigar.ig_coverage_1'

**Comment by glennhickey** [comment]
That is indeed curious.  Are you absolutely sure the cactus-blast job ran
through without error?  Are there any Anc1 files in that directory?

**Comment by lainnorton** [comment]
Thank you for your reply.

There is only one line of the log file with the "error" message, but the next two lines show successful rerunnning. In addition, both tests produced almost identical log files.
The output file contains "Anc1.cigar"， “Anc1.cigar.secondary”， “Anc1.cigar.og_fragment_0” and “Anc1.cigar.ig_coverage_0”, except "Anc1.cigar.ig_coverage_1".

But amazingly, just yesterday, after running "Cactus-Blast" again with about 1/6 of the amount of resources I had used in the previous two sessions, Cactus successfully exported the file "Anc1. Cigar. Ig_coverage_1 ". Previously I had used a full compute node, but this time I used only a fraction of the resources because others were using it.
The previous two log files were about 75Mb in size, and this one was 191Mb. But when I checked the last part of the log file, there was no significant difference between this one and the previous two, even the error I mentioned earlier was the same.

I am not sure whether this is due to our computing platform, as I have set some parameters about Cactus's use of resources. Here are the parameters I used in the previous two sessions:
cactus-blast lingzhang_4/4 output/seq.out.txt output/Anc1.cigar --root Anc1 --realTimeLogging --maxMemory 220G --maxCores 128 --maxPreemptableServiceJobs 128 --deadlockWait 600  --binariesMode local --maxLocalJobs 128

The following is the parameter used in the third (successful) attempt:
cactus-blast lingzhang_4/4 output/seq.out.txt output/Anc1.cigar --root Anc1 --realTimeLogging  --maxMemory 50G --maxCores 28 --maxPreemptableServiceJobs 28 --deadlockWait 600  --binariesMode local --maxLocalJobs 28

In order to avoid the recurrence of this situation, could you give me some suggestions on the use of parameters? Thank you very much and look forward to your reply.

**Comment by glennhickey** [comment]
I know that Toil's error messaging has improved, especially when halting due to lack of resources.  Upgrading to the latest Toil release (best done by upgrading to the latest master commit of Cactus), may help your logs be more readable in the future.  

The memory and disk requirements are dependent on your data, so unfortunately I can't suggest any exact numbers to you.
