### ISSUE TITLE
ERROR:toil.worker:Exiting the worker because of a failed job on host n212.cluster

### ISSUE THREAD

**Issue by PencilsSharpener** [ComparativeGenomicsToolkit/cactus#273]
Hi everyone, I met a problem when I used Precompiled Binaries way and evolverMammals.txt example to test whether I installed cactus sucessfully. 
I used: 
 `source /scratch/ping/lncRNA_conservation/cactus_env/bin/activate`
to enter virtualenv
and 
`cactus /scratch/ping/lncRNA_conservation/cactus_env/cactus/ /scratch/ping/lncRNA_conservation/software/evolverMammals.txt /scratch/ping/lncRNA_conservation/evolverMammals.hal --root mr`
to start, but there are errors mentioned in log file: 
`kind-LastzRepeatMaskJob/instanceh9vqa5bf    ERROR:toil.worker:Exiting the worker because of a failed job on host n212.cluster`, I don't what caused this issue since I installed cactus step by step. Thank you for your time!

[cactus.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/4950720/cactus.log)

**Comment by glennhickey** [comment]
I think this is the key part of the log:
```
cPecanLastz: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by cPecanLastz)
```
which leads me to believe our static binaries perhaps aren't as static as we think.  Can you please tell us which OS you are using.  Also, what is the output of `ldd --version`? 

@diekhans Any ideas?

**Comment by PencilsSharpener** [comment]
> I think this is the key part of the log:
> 
> ```
> cPecanLastz: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by cPecanLastz)
> ```
> 
> which leads me to believe our static binaries perhaps aren't as static as we think. Can you please tell us which OS you are using. Also, what is the output of `ldd --version`?
> 
> @diekhans Any ideas?

**Comment by PencilsSharpener** [comment]
> I think this is the key part of the log:
> 
> ```
> cPecanLastz: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by cPecanLastz)
> ```
> 
> which leads me to believe our static binaries perhaps aren't as static as we think. Can you please tell us which OS you are using. Also, what is the output of `ldd --version`?
> 
> @diekhans Any ideas?

my OS is:`CentOS release 6.3 (Final)` and ldd version is `ldd (GNU libc) 2.12 `
I don't know whether they affect static binaries.

**Comment by glennhickey** [comment]
This should be fixed in the latest release.
