### ISSUE TITLE
pairwise alignment input?

### ISSUE THREAD

**Issue by LipengKang** [ComparativeGenomicsToolkit/cactus#280]
Hi, catus team
I am trying Catus to instead multiz to reduce reference bias.

Two questions for me:
1. the guide tree is ambiguous of both topology and branch. how to determine the tree for  new  sequenced species annalysis?
2.Can I use piarwise alignment maf files as input for Catus? lastz is a little lazy for very big genomes. LAST is used for a substitution. I mean if LAST +Catus pipeline is feasible？

Thanks!
lipeng

**Comment by glennhickey** [comment]
As the manuscript shows, cactus is fairly robust to small changes in the
guide tree.  You still need to estimate one though with something like,
say, fasttree 2.

In theory you can feed pairwise alignments from any software into
cactus-align.  But they need to be converted to lastz cigar format and it's
a bit particular in how outgroups are specified.

**Comment by LipengKang** [comment]
ok, I got it. 
I see the old issue that talked about `Modify Cactus to use an aligner different from LASTZ`
(https://github.com/glennhickey/progressiveCactus/issues/94)
I am also trying to modify Cactus with LAST aligner for speed. Does the problem---a large drop in sensitivity for highly diverged genomes is still remaining three years ago?  Any test or try after that? By the way, are there some tools to convert MAF to lastz cigar?


Thanks for your advice!
lipeng

**Comment by cnk113** [comment]
Sorry to piggyback on this issue, but I'm trying to do something similar. I was wondering if cPecanLASTZ inherits all the parameters of LASTZ? Specifically ```--segments``` as I'm trying to feed in anchored segments using a different seeding, gap-free extension, and chaining strategy.

**Comment by glennhickey** [comment]
I don't know off hand -- you'd have to try.  cPecanLastz [is basically a fork of lastz 1.03.54](https://github.com/ComparativeGenomicsToolkit/cPecan/tree/master/externalTools/lastz-distrib-1.03.54), and I would expect the interface to be largely consistent with the current version of lastz.
