### ISSUE TITLE
"flat" guide tree for pangnome

### ISSUE THREAD

**Issue by egoltsman** [ComparativeGenomicsToolkit/cactus#311]
Hi,
Could you please explain how the progressive alignment does its magic when the guide tree is essentially flat as in the case of aligning unrelated individuals of the same species?   I've created a binary tree for a toy data set of  homologous 1mb slices from four fully assembled genomes:
(Ref,(Bd1_1,(Bd21_3,Bd30-1)));

It seems like cactus still attempts to reconstruct "ancestral" reference sequences, and these end up showing up in the final graph

```
 halStats graph.hal 

hal v2.1
(Ref:1,(Bd1_1:1,(Bd21_3:1,Bd30-1:1)Anc2:1)Anc1:1)Anc0;

GenomeName, NumChildren, Length, NumSequences, NumTopSegments, NumBottomSegments
Anc0, 2, 1235554, 9, 0, 2832
Ref, 0, 1241865, 1, 3032, 0
Anc1, 2, 1310375, 5, 4259, 5653
Bd1_1, 0, 1332815, 1, 6037, 0
Anc2, 2, 1292777, 4, 5713, 9621
Bd21_3, 0, 1238213, 1, 9399, 0
Bd30-1, 0, 1273027, 1, 9487, 0
```
If this is the expected behavior and if my tree is defined correctly,   how shoule I go about extracting variant info from such a graph.  After reading the manuscripts I am very excited about the hierarchical organization of the graph as it sounds like it should allow users to extract structural info at different resolution layes.  The HAL page gives some examples, but I can't get my head around interpreting the Anc genomes included in graph.
Thank you!

**Comment by glennhickey** [comment]
For the same species, the correct tree is usually a star unless you have compelling information otherwise.  Unfortunately, cactus as implemented does not scale well with the degree of a star tree, though it may work for chromosome level inputs.  

As mentioned in #236, we're busy working on a way around this.  It's still not quite ready yet though. 

Arbitrarily making a binary tree will enable cactus to compute the alignment with its default logic, but the ancestors themselves won't mean much.  You also stand a good chance of losing some alignments between assemblies that are distant in your tree if they are, for examples, insertions that aren't present in the samples in between.

**Comment by egoltsman** [comment]
I'm running on a 1mb slice of a 4-member pangenome, just to test the graph structure.  With a star tree it looks like it's still trying to reconstruct the Anc0 "ancestor" which shows up in the final graph.  I'm not sure what it's role is in the graph structure.   Does it capture the conserved "core" sequence, or does it make sense to remove it from the graph altogether?

**Comment by glennhickey** [comment]
There's no avoiding that root "Anc0" ancestor, as it's required by the output format.  You can safely remove it with the "--noAncestors" option of hal2vg when you're exporting it though.

**Comment by egoltsman** [comment]
Thanks.  Is it true then that any mutation analysis using the Hal tools (say, halSummarizeMutations) will only consider changes relative to the root ancestor?   Or is it possible to calculate them wrt specific branches/paths?   In a pangenome system you'd often want to account for variation against an arbitrary reference where the variants detected from the graph strucure (simply put, bubbles) and the reference path is used mainly to assign genotypes on a linear coordinate.   Vg tries to do this, and I've tried exporting the graph to vg and using their 'snarl' detection algorithm, but it produced mostly inaccurate calls on large variants.  So my plan was to take vg out of the equation and try native Hal tools, if any are suitable for this.

Thanks again

**Comment by glennhickey** [comment]
Yeah, those `mutations` tools will only go branch by branch, so you'd only get the relationship between each species and the ancestor.  `hal2maf` and `halLiftover` can span multiple branches, but I would still recommend `hal2vg` then `vg deconstruct -e` to view the rearrangements in VCF (using the latest hal2vg and vg releases).

**Comment by egoltsman** [comment]
The bigger reason I'm trying to understand the construction specifics is that I'd like to figure out a way to explore the graph's organizational hierarchy.  Going by the original B. Paten papers (2011, 2014), it seems like there should be a way of representing the alignment "tree" structure - the cactus tree itself.   As I understand, this tree is implemented in a separate data structure, but is it saved to disk in any way?  Having access to it, even, after the hal2vg export, could be very useful in cutting through the complexity of a cyclic graph, in cutting corners, if you will, when classifying large-scale variants.  Small local structures often need to be abstracted or ignored when looking for the big picture, and this is what the cactus tree can help with.   If the tree is not saved, is there perhaps an API that I could leverage in this regard?

**Comment by glennhickey** [comment]
I see.  `vg deconstruct -e` uses that structure but only at the top level.  For now, the only way to get the nesting/tree structure you refer to is `vg snarls` (whose output you can convert to JSON with `vg view -R`).

**Comment by egoltsman** [comment]
Thanks Glenn.  I'm back to where I started, I guess:  https://github.com/vgteam/vg/issues/2878
Do you know if there are plans to enhance vg to report structures (ultrabubbles?) at multiple tree levels?

**Comment by glennhickey** [comment]
[this](https://github.com/vgteam/vg/pull/2988) should resolve that issue by ensuring that you get a traversal through every snarl for every path in your graph.  

I agree the snarl hierarchy is under utilized by many `vg` tools.  This is something we're working on.  If you have any thoughts on an ideal file format for expressing this information, I would be curious to hear them.

**Comment by egoltsman** [comment]
Thanks Glenn. Unfortunately, I can't build vg from source (cmake not finding Protobuf), so I've been relying on the static binaries the vg folks make available with every "release".  I'll have to wait for the next release to try your fix.  I'll keep you posted.

**Comment by egoltsman** [comment]
Hi Glenn,
I finally managed to build from the "release" tarball  (
https://github.com/vgteam/vg/releases/tag/v1.27.0)  and I was about to try make a build from the latest master commit, but this statement on the download page threw me off: 

"Use this instead of Github's "Source Code" downloads; those will not build as they do not include code for bundled dependencies that the vg build process needs."

The main vg page is instructing users to do git clone --recursive https://github.com/vgteam/vg.git    - is this out of date?

**Comment by glennhickey** [comment]
The "Source Code" downloads referred to here are the last two "Assets" at the bottom of the Release page.  Github puts these links in every release and all we can do is warn people away from them.  This message only applies for downloading source tarballs for releases -- building from master or any other branch is done with git clone as described in the readme.

**Comment by glennhickey** [comment]
The latest cactus release introduces a "pangenome mode" https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v1.3.0
