### ISSUE TITLE
missing `containerImage` argument at cactus-prepare-toil

### ISSUE THREAD

**Issue by thiagogenez** [ComparativeGenomicsToolkit/cactus#347]
https://github.com/ComparativeGenomicsToolkit/cactus/blob/0d7bb81baa60d2b52e48136d350eb985704d38e7/src/cactus/progressive/cactus_prepare.py#L59

`cactus-prepare-toil` fails its execution when using `--binariesMode singularity` because `--containerImage` argument (needed [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/bbf691a265e5e7b6de7eb32471a8dd417acabe78/src/cactus/shared/common.py#L967)) is missing at the `main` function. 

I was wondering if `cactus-prepare-toil` allows the  singularity binary option

Cheers,

**Comment by glennhickey** [comment]
Thanks, that's a bug.  I did test `cactus-preapre-toil` with Singularity, but using a remote jobstore so it never hit this codepath.

**Comment by thiagogenez** [comment]
I was about to close this issue. Thanks @glennhickey
