### ISSUE TITLE
can't run cactus

### ISSUE THREAD

**Issue by WeiWei1112** [ComparativeGenomicsToolkit/cactus#35]
Hi,
I am trying to run cactus because it's required by another program called "Ragout" to assemble genome based on reference genomes. However, after I installed this program, I can't find the script progressiveCactus anywhere. Do you have any idea why?
Thanks,
Wei Wei

**Comment by shkao** [comment]
Hi Wei Wei,
do you need `progressiveCactus` or `runProgressiveCactus.sh`?

**Comment by WeiWei1112** [comment]
Hi shkao,
Thanks for quick reply! What's the difference between these two? I can find a script named "cactus_progressive.py" in the src directory but I can't find "runProgressiveCactus.sh" in bin directory. Do we use different versions of cactus?

Wei Wei

**Comment by shkao** [comment]
Hi Wei Wei,
After installing using:
```
git clone git://github.com/glennhickey/progressiveCactus.git
cd progressiveCactus
git pull
git submodule update --init
make
```
I have `progressiveCactus/bin/runProgressiveCactus.sh`, which is a wrapper to process arguments then pass to `src/progressiveCactus.py`, as the content of `runProgressiveCactus.sh`:
```
$ tail bin/runProgressiveCactus.sh
# need to go through this monkey business to make sure arguments with spaces
# don't get split when passing to python
options=""
for arg in "$@"
do
	 options="$options '${arg}'"
done

. ${envFile} && eval python ${binDir}/../src/progressiveCactus.py "$options"
exit
```

**Comment by WeiWei1112** [comment]
Hi Allen,
I installed the version of cactus from this site. The site you gave me "git://github.com/glennhickey/progressiveCactus.git" is the old github site. Do you mean I need to also install the old version in order to run?


Wei Wei

**Comment by joelarmstrong** [comment]
Hi Wei Wei,

The script from this repository will be called `cactus` rather than `progressiveCactus`. You can find more information here:

https://github.com/ComparativeGenomicsToolkit/cactus#running

If the `cactus` script isn't found, you may need to check that your PATH is pointing to where pip installs the script, or (easier) install the cactus package within a virtual environment.

**Comment by WeiWei1112** [comment]
Thanks Joel! I think that may be the reason.

Wei Wei

**Comment by diekhans** [comment]
seems user has been helped, but ticket not closed
