### ISSUE TITLE
Example run -> docker: Got permission denied

### ISSUE THREAD

**Issue by alptaciroglu** [ComparativeGenomicsToolkit/cactus#365]
I got this error after installing cactus via 'Build from Source' pipeline and running: 
`cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr`

Install the Cactus Python package and its dependencies part is pretty straightforward. 
Build the Cactus Binaries part: I built Dockerfile with `docker build -t cactuswf.`

After running the example, I get the following log

![image](https://user-images.githubusercontent.com/13270606/100888444-2e9b5480-34c7-11eb-8a8b-d699c6362f8e.png)

**Comment by glennhickey** [comment]
Assuming the [release](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v1.2.3) binaries and docker images are not working (were you one of the people whose cpu was too old?).

Your best bet is to build from source following the instructions [here](https://github.com/ComparativeGenomicsToolkit/cactus#build-from-source), especially `export PATH=$(pwd)/bin:$PATH`.  You can then add `--binariesMode local` commands to Cactus to make sure it is using the binaries you built and not Docker.

If you really want to make your own Docker image for some reason, I suggest just opening a shell inside it with something like `docker run -it --rm cactuswf bash`, and running cactus there.   From the look of it, you don't have Docker set up properly though (you can test quickly with `docker run hello-world`).  Sometimes `sudo usermod -aG docker $USER` will fix this.

**Comment by alptaciroglu** [comment]
Sorry for the late reply and thanks for your help. It turns out I had to be enlisted to docker users in the server I am running Cactus on. That is now resolved. 

I moved forward yay, but I am experiencing "No space left on device" error which I will try to solve from other issues. Closing this
