### ISSUE TITLE
didn't find cactus after installing using binary version

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [ComparativeGenomicsToolkit/cactus#367]
Hi Glenn,
I followed the instructions from this link:
https://github.com/ComparativeGenomicsToolkit/cactus/blob/v1.2.3/BIN-INSTALL.md
There seemed no errors during installation, yet I didn't find cactus under bin (see attached), any idea or insights?
<img width="1124" alt="Screen Shot 2020-12-03 at 10 37 29 AM" src="https://user-images.githubusercontent.com/9053403/100956613-c9417500-3553-11eb-8ff0-6812395a89bc.png">

thanks for your help.
Zhenzhen

**Comment by glennhickey** [comment]
The `cactus` binary is installed within `venv` and added to your `PATH` by this portion of the instructions
```
virtualenv -p python3.6 venv
source venv/bin/activate
pip install -U setuptools pip
pip install -U -r ./toil-requirement.txt
pip install -U .
```

**Comment by zhenzhenyang-psu** [comment]
I see. now I find it under my cactus_env/bin/, thanks for your reply:)
