### ISSUE TITLE
RuntimeError when using cactus_bar

### ISSUE THREAD

**Issue by chuanxinyu** [ComparativeGenomicsToolkit/cactus#384]
I meet some errors when I running the example in examples/evolverMammals.txt step by step:

## Preprocessor
cactus-preprocess jobstore_step/0 ./examples_step/evolverMammals.txt steps-output/evovlerMammals.txt --inputNames simHuman_chr6 simCow_chr6 simDog_chr6 --realTimeLogging --logInfo --retryCount 0 
cactus-preprocess jobstore_step/1 ./examples_step/evolverMammals.txt steps-output/evovlerMammals.txt --inputNames simMouse_chr6 simRat_chr6 --realTimeLogging --logInfo --retryCount 0 
### Round 0
cactus-blast jobstore_step/2 steps-output/evovlerMammals.txt steps-output/Anc2.cigar --root Anc2 --realTimeLogging --logInfo --retryCount 0 
cactus-align jobstore_step/3 steps-output/evovlerMammals.txt steps-output/Anc2.cigar steps-output/Anc2.hal --root Anc2 --realTimeLogging --logInfo --retryCount 0 --maxCores 2 --database kyoto_tycoon
hal2fasta steps-output/Anc2.hal Anc2 --hdf5InMemory > steps-output/Anc2.fa

The error appeared in Round 0:

raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['cactus_bar', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="10.1.1.10" port="18807" />\n\t\t</st_kv_database_conf>\n\t', '--maximumLength', '1000000.0', '--spanningTrees', '5', '--gapGamma', '0.0', '--matchGamma', '0.2', '--splitMatrixBiggerThanThis', '3000', '--anchorMatrixBiggerThanThis', '500', '--repeatMaskMatrixBiggerThanThis', '500', '--diagonalExpansion', '20', '--constraintDiagonalTrim', '14', '--minimumDegree', '2', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--pruneOutStubAlignments', '--alignAmbiguityCharacters', '--useProgressiveMerging', '--largeEndSize', '5000', '--minimumSizeToRescue', '100', '--minimumCoverageToRescue', '0.5', '--minimumNumberOfSpecies', '1', '--partialOrderAlignmentBandConstant', '10', '--partialOrderAlignmentBandFraction', '0.01'] exited 1: stdout=

Is there any question in GPU or memory? It still have same question when I change memory to 500Gb. (The full err out in the link)
[example_Alignment_Round0.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/5735132/example_Alignment_Round0.txt)

**Comment by glennhickey** [comment]
The `cactus_bar` binary on your system is older than the `cactus` python package.  If you're pulling from master (which I don't recommend), you need to rebuild.  Otherwise, use the latest release.

**Comment by chuanxinyu** [comment]
I used the cactus-bin-v1.2.3 in&nbsp;https://github.com/ComparativeGenomicsToolkit/cactus/releases&nbsp;and Python v3.6.5, which version of soft should&nbsp;I change? Otherwise, would you give me the link of latest release?
thanks&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ComparativeGenomicsToolkit/cactus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 晚上9:29
收件人:&nbsp;"ComparativeGenomicsToolkit/cactus"<cactus@noreply.github.com&gt;;
抄送:&nbsp;"Chuanxin Yu"<1048476258@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ComparativeGenomicsToolkit/cactus] RuntimeError when using cactus_bar (#384)



 The cactus_bar binary on your system is older than the cactus python package.If you're pulling from master (which I don't recommend), you need to rebuild.Otherwise, use the latest release.

**Comment by glennhickey** [comment]
That `--partialOrderAlignmentBandConstant` option message from your error message is not in any cactus release.
