### ISSUE TITLE
use results from previous step in another computer

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [ComparativeGenomicsToolkit/cactus#385]
Hello Glenn,
I have 4 genomes I would like to run cactus for. I was stuck in the blast stage due to insufficient RAM. I was wondering whether it is okay to use results up to this stage (repeatMasker is done) and pick it up from a different cluster where there is sufficient RAM.
Do you think current cactus would support this?
thanks,
Shenzhen

**Comment by glennhickey** [comment]
Yes, this should work.  You can copy the jobstore over, run [step-by-step](https://github.com/ComparativeGenomicsToolkit/cactus#running-step-by-step)

**Comment by zhenzhenyang-psu** [comment]
thanks, that's terrific!
