### ISSUE TITLE
 question about the running speed

### ISSUE THREAD

**Issue by CrawlingSponge** [ComparativeGenomicsToolkit/cactus#386]
Hello, i have a question about the running speed of cactus. 
When i run the cactus, nomatter how i changed the parameters, like "maxCores 100", the running threads always keep 8, just like the default, while we have 128 processors, which i run other programs always with no limits. Could you tell me how to solve this? Thank you very much!
![微信图片_20201227121912](https://user-images.githubusercontent.com/22827591/103163804-ef4df280-483d-11eb-8613-b8219563f5e4.png)

**Comment by glennhickey** [comment]
The lastz jobs are made by splitting the input sequences into chunks and aligning each chunk.  The number of parallel jobs is limited to the number of chunks, which depends on the input sequence length.  You could theoretically reduce the chunk size to run more jobs.  [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/cactus_progressive_config.xml#L16) for the preprocessor and [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/cactus_progressive_config.xml#L87) for the blast phase, but I'm not sure there'd be much benefit overall.

**Comment by biozhangzhou** [comment]
So what should we set to accelerate the processs? Such as --maxCores --defaultCores ?

**Comment by CrawlingSponge** [comment]
> The lastz jobs are made by splitting the input sequences into chunks and aligning each chunk. The number of parallel jobs is limited to the number of chunks, which depends on the input sequence length. You could theoretically reduce the chunk size to run more jobs. [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/cactus_progressive_config.xml#L16) for the preprocessor and [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/cactus_progressive_config.xml#L87) for the blast phase, but I'm not sure there'd be much benefit overal
