### ISSUE TITLE
The same RuntimeError when using cactus_bar

### ISSUE THREAD

**Issue by chuanxinyu** [ComparativeGenomicsToolkit/cactus#387]
I used the cactus-bin-v1.2.3 in https://github.com/ComparativeGenomicsToolkit/cactus/releases and Python v3.6.5. I meet the same errors when I running the example in examples/evolverMammals.txt step by step:
Round 0
cactus-blast jobstore_step/2 steps-output/evovlerMammals.txt steps-output/Anc2.cigar --root Anc2 --realTimeLogging --logInfo --retryCount 0
cactus-align jobstore_step/3 steps-output/evovlerMammals.txt steps-output/Anc2.cigar steps-output/Anc2.hal --root Anc2 --realTimeLogging --logInfo --retryCount 0 --maxCores 2 --database kyoto_tycoon
hal2fasta steps-output/Anc2.hal Anc2 --hdf5InMemory > steps-output/Anc2.fa

The error appeared in Round 0:

raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
RuntimeError: Command ['cactus_bar', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="10.1.1.10" port="18807" />\n\t\t</st_kv_database_conf>\n\t', '--maximumLength', '1000000.0', '--spanningTrees', '5', '--gapGamma', '0.0', '--matchGamma', '0.2', '--splitMatrixBiggerThanThis', '3000', '--anchorMatrixBiggerThanThis', '500', '--repeatMaskMatrixBiggerThanThis', '500', '--diagonalExpansion', '20', '--constraintDiagonalTrim', '14', '--minimumDegree', '2', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--pruneOutStubAlignments', '--alignAmbiguityCharacters', '--useProgressiveMerging', '--largeEndSize', '5000', '--minimumSizeToRescue', '100', '--minimumCoverageToRescue', '0.5', '--minimumNumberOfSpecies', '1', '--partialOrderAlignmentBandConstant', '10', '--partialOrderAlignmentBandFraction', '0.01'] exited 1: stdout=

glennhickey commented: the cactus_bar binary on your system is older than the cactus python package. If you're pulling from master (which I don't recommend), you need to rebuild. Otherwise, use the latest release.

Which version of soft should I change?

**Comment by glennhickey** [comment]
From your error message, you are clearly running a Cactus from github that is more recent than the latest release.  I suggest: delete your virtual environment, erase any copies of cactus you cloned from github, and re-install the latest release using the instructions included.
