### ISSUE TITLE
cannot find cPickle 

### ISSUE THREAD

**Issue by ShwethaMurali** [ComparativeGenomicsToolkit/cactus#39]
Hi there, I installed cactus, but when I do "cactus -h" from the command line, I get a module not found error. After doing some digging, I am finding that cPickle is not available for python3. 
Is the virtual environment in cactus_env supposed to be running python3 or python 2.7 ? I am confused.

**Comment by joelarmstrong** [comment]
Hi Shwetha,

Right now (and for the near future) Cactus only works on Python 2.7 because its dependencies require it.

**Comment by jguhlin** [comment]
Could you add the python version dependency to the README?

**Comment by joelarmstrong** [comment]
Sure! Just added a bit to the README to mention this.

**Comment by diekhans** [comment]
cactus is now py 3.6+
