### ISSUE TITLE
Is NEWICK tree required?

### ISSUE THREAD

**Issue by ardy20** [ComparativeGenomicsToolkit/cactus#390]
Dear Sir/Madam

Is addition of NEWICK tree to seqFile input file necessary? Could you please provide a link how to prepare NEWICK tree?

As far as I know, for preparation of a NEWICK tree an alignment is required! If this is the correct, what does the Cactus do on top of other genome aligners?

Regards
Ardy

**Comment by glennhickey** [comment]
The tree is not strictly necessary.  However Cactus will not be able to align very many inputs without one (how many depends on the length and amount of ram your have).  I invite you to read [the paper](https://doi.org/10.1038/s41586-020-2871-y) for more details on this and your other questions.  One other note is that the next release will provide a "pangenome" option to align many closely related samples (ie from the same species) without a tree.

**Comment by glennhickey** [comment]
Cactus can now align similar genomes without a tree using its "pangenome mode" https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v1.3.0
