### ISSUE TITLE
hal2assemblyHub.py error: ModuleNotFoundError: No module named 'hal'

### ISSUE THREAD

**Issue by ybukhman** [ComparativeGenomicsToolkit/cactus#399]
Hi,

I get an error when trying to generate an assembly hub from a HAL file. Command:
`hal2assemblyHub.py mAcoRus1.1_vs_mm10.hal mAcoRus1.1_vs_mm10_hub --lod  --alignability --gcContent --cladeExclusiveRegions --maxThreads 20 |& tee hal2assemblyHub.out`

Error:
>  Traceback (most recent call last):
>    File "/isitools/cactus-bin-v1.2.3/bin/hal2assemblyHub.py", line 28, in <module>
>      from hal.assemblyHub.prepareLodFiles import *
>  ModuleNotFoundError: No module named 'hal'
> 

I am using precompiled cactus release 1.2.3. Cactus itself, halValidate and halStats work fine.

Thanks!

Yury

**Comment by diekhans** [comment]
See README.md instructions for setting the python path:
    The parent directory of hal/ should be in your PYTHONPATH in order to use any of the Python functionality

sorry this is a bit of a hack.

**Comment by ybukhman** [comment]
Modifying PYTHONPATH fixed this issue for me. Thanks a lot, @diekhans!
