### ISSUE TITLE
restart with new tree root

### ISSUE THREAD

**Issue by biozhangzhou** [ComparativeGenomicsToolkit/cactus#405]
Hello, everyone.
Is there any way to restart a job which have ran without a tree root(no --root parament) ?
It's a pretty big job, so I don't wanna to restart it in all.

**Comment by glennhickey** [comment]
No, unfortunately not.  Only changes to Toil-related parameters (ex --maxCores) will have any effect when running with `--restart`

**Comment by biozhangzhou** [comment]
thanks.
