### ISSUE TITLE
DeadlockException Error when Running Cactus

### ISSUE THREAD

**Issue by jerricamae** [ComparativeGenomicsToolkit/cactus#41]
Hi,

I'm trying to run cactus with docker on a machine, but whenever I do, the DeadlockException gets raised, and I cannot figure out a way to fix it. I have tried increasing the disk space, the memory, and the number of cores used using --defaultDisk, --defaultMemory, and --defaultCores. I have also tried lowering the number of service jobs run at once using --maxServiceJobs. The program also uses only 2G of memory when 64G is available on the machine, and I specify more memory can be allocated. I would greatly appreciate any guidance on this issue. Thank you.

**Comment by joelarmstrong** [comment]
Hi Jerrica,

Sorry to hear that. This *should* only occur when your machine/cluster doesn't have enough resources to run the database and worker processes simultaneously. Do you have the full log anywhere? Also, what inputs are you using (large genomes? small genomes?), and what batch system?

Thanks!

**Comment by jerricamae** [comment]
So I'm running it with the evolverMammals examples. I have attached the output log. I'm running it on an interactive node. Let me know if there is anymore information you need.

[Cactus_Out_Log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/2401766/Cactus_Out_Log.txt)

**Comment by jguhlin** [comment]
Been having the same issue, both with singularity and with local binaries. 144 core machine with 1Tb ram. Got it further along by setting the workDir manually (our /tmp is nearly full) but it still ends like this:

Tried altering deadlockWait to 180, and maxServiceJobs to various numbers, with no luck. Turned on logDebug to generate this file in case it's any help. Also running on the example dataset.

[cactus-logdebug.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/2413697/cactus-logdebug.log)

**Comment by joelarmstrong** [comment]
How weird... it looks like more or less nothing is happening on the toil side for 3 minutes, which is causing toil to think the workflow is deadlocked. But I can't see any obvious reason why toil is just sitting around without launching the service.

Maybe this is something that cropped up with a newer toil version--the deadlock code has given us similar problems before. I'll have to take a closer look to see if I can replicate.

**Comment by jguhlin** [comment]
Somehow... it's working now. It may have been a patch (from github) or something I did to Kyoto....

**Comment by jerricamae** [comment]
It's also working for me as well, though I don't know why

**Comment by joelarmstrong** [comment]
How weird... A few days ago, I tried to reproduce it as best I could and didn't run into the same issue. From the logs it appears to be a toil issue.

One thing to consider, if this happens again, is to try reducing `--maxCores` to something *less* than the total amount of cores you have available. Toil can end up spawning a Python thread per core to launch jobs with, so on large systems (like 144 cores!) I've seen it exhaust resources like the number of open file descriptors and/or processes. The thread-per-core thing is dumb, but hard to change now as it works "well enough" for most of us.

**Comment by jerricamae** [comment]
I got the problem to resolve by using:

cactus_args="--binariesMode local --batchSystem  torque  --maxCores 360 tmpdir Carnivore_PON_Regions/Ter_Carnivore_cactus.txt out"

cactus  $cactus_args 
while [ -d tmpdir ] 
do 
  cactus $cactus_args  --restart
done

It's not the prettiest method, but it got through any deadlock exceptions.

**Comment by lparsons** [comment]
I'm running into this issue trying to get Cacus to run on the evolverMammals example data. Using the singularity binaries and toil 3.14.0 installed via conda/bioconda. Using:
```
cactus cactus_evolverMammals_jobStorePath cactus/examples/evolverMammals.txt evolverMammals.hal --binariesMode singularity --batchSystem slurm
```

I've tried running again with `--restart`, but ran into the same `DeadlockException`.

**Comment by abmudd** [comment]
Hello @jerricamae @joelarmstrong @jguhlin @lparsons,

To follow up on this thread, I ran into the DeadlockException error a few days ago with jobs terminating at stage CactusReferenceWrapper. For context, cactus is installed as a module on the system, so all cactus installation files are separate from my regular `PATH`, `PYTHONPATH`, etc., and this installation of cactus had been running otherwise successfully for the past few months. After some investigation, I realized that I had accidentally added my regular `PYTHONPATH` directories into my bash profile and did not clear this out before running cactus. When I clear out my regular `PYTHONPATH` and then run cactus, I no longer get the DeadlockException. I'm not sure  what python library could be causing an issue, but if anyone has this error in the future, try clearing out all PATHs (`PKG_CONFIG_PATH`, `LD_LIBRARY_PATH`, `LIBRARY_PATH`, `INCLUDE_PATH`, `MANPATH`, `PATH`, and `PYTHONPATH`) so that you are only exporting the cactus installation directories prior to running.

**Comment by lassancejm** [comment]
@lparsons : did you move past this error? historically, I was totally able to run the test sample with local binaries, Slurm and toil 3.19. Yet, now I seem unable to go beyond this error. I may have nothing to do with that, but I think this error begun after our cluster administrator upgraded to Slurm 18.08.6.  
 
```
INFO:toil.leader:Job ended successfully: 'CactusReferenceRecursion3' D/g/jobtclkOy
INFO:toil.leader:Issued job 'CactusSetReferenceCoordinatesUpWrapper' 9/b/job_k0DAC with job batch system ID: 235 and cores: 1, disk: 2.0 G, and memory: 500.0 M
INFO:toil.leader:Issued job 'CactusSetReferenceCoordinatesUpWrapper' u/9/jobvmVuUP with job batch system ID: 236 and cores: 1, disk: 2.0 G, and memory: 500.0 M
INFO:toil.leader:Issued job 'CactusSetReferenceCoordinatesUpWrapper' w/D/job5rZfUX with job batch system ID: 237 and cores: 1, disk: 2.0 G, and memory: 500.0 M
INFO:toil.leader:Job ended successfully: 'CactusSetReferenceCoordinatesUpWrapper' 9/b/job_k0DAC
INFO:toil.leader:Job ended successfully: 'CactusSetReferenceCoordinatesUpWrapper' u/9/jobvmVuUP
INFO:toil.leader:Job ended successfully: 'CactusSetReferenceCoordinatesUpWrapper' w/D/job5rZfUX
INFO:toil.leader:Issued job 'CactusReferenceRecursion3' D/g/jobtclkOy with job batch system ID: 238 and cores: 1, disk: 2.0 G, and memory: 3.4 G
INFO:toil.leader:Job ended successfully: 'CactusReferenceRecursion3' D/g/jobtclkOy
INFO:toil.leader:Issued job 'CactusReferenceRecursion2' N/q/jobSPalGi with job batch system ID: 239 and cores: 1, disk: 2.0 G, and memory: 2.0 G
INFO:toil.leader:Job ended successfully: 'CactusReferenceRecursion2' N/q/jobSPalGi
INFO:toil.leader:Issued job 'CactusReferenceRecursion' i/r/job3wKebC with job batch system ID: 240 and cores: 1, disk: 2.0 G, and memory: 2.0 G
INFO:toil.leader:Reissued any over long jobs
Traceback (most recent call last):
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/bin/cactus", line 10, in <module>
    sys.exit(main())
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 520, in main
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/common.py", line 773, in start
    return self._runMainLoop(rootJobGraph)
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/common.py", line 1046, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/leader.py", line 211, in run
    self.innerLoop()
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/leader.py", line 556, in innerLoop
    self.checkForDeadlocks()
  File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/leader.py", line 588, in checkForDeadlocks
    raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException
```

**Comment by lparsons** [comment]
@lassancejm I've gotten past this problem on the example dataset, but I'm now running into it on some real data. I've been able to get past this with the exact same data on a different cluster, but I'm beginning to suspect the problem is that some jobs get stuck in the queue for a while and cactus seems to always be "behind" is submitting jobs. At some point, it checks for the deadlock situation and while there are jobs left to be submitted (that cactus "says" it submitted, but toil hasn't submitted yet), it detects that no jobs are in the slurm queue and throws this exception. Just a theory, but it seems to be happening with enough regularity that I'm hoping to confirm. I'm going to submit an issue to this effect to try and document it.

**Comment by ashlingcha** [comment]
> I got the problem to resolve by using:
> 
> cactus_args="--binariesMode local --batchSystem torque --maxCores 360 tmpdir Carnivore_PON_Regions/Ter_Carnivore_cactus.txt out"
> 
> cactus $cactus_args
> while [ -d tmpdir ]
> do
> cactus $cactus_args --restart
> done
> 
> It's not the prettiest method, but it got through any deadlock exceptions.

I tried this method and it resolved issues for the evolverMammals.txt but when I try to do it for 2 mammalian genomes to error comes up again - does anyone know why this may be the case?
