### ISSUE TITLE
Installation issues due to missing library

### ISSUE THREAD

**Issue by saoirseguita** [ComparativeGenomicsToolkit/cactus#411]
I am following along with the build from source installation guidelines for Progressive Cactus and have encountered an error at the following step: 

  pip install --upgrade -r toil-requirement.txt

The error message pertains to the installation of both http-parser and pyyaml, and in short, reads: 

  /usr/bin/ld: cannot find -lpython3.6m

I am using Python3.6.8. I think this problem may be fixed by adding extra lines to either the makefile or include.mk to install the library too, but I'm not sure. I also can't tell where the toil requirements are being pulled from. Is this a known issue?

**Comment by glennhickey** [comment]
You need the dependencies installed on your system.  You can use the [Dockerfile as a guide](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile#L4) on how to install them with `apt` on Ubuntu.

**Comment by saoirseguita** [comment]
I just tried installing within a conda environment instead of a python virtual environment. I am no longer receiving this error. 

All the best! 

Saoirse.
