### ISSUE TITLE
Unable to use hal modules

### ISSUE THREAD

**Issue by stlomo** [ComparativeGenomicsToolkit/cactus#421]
Greetings

I am using cactus precompiled binaries in local mode succesfully producing an hal output, however when I try to convert or operate on the output using hal2maf or hal2assembly I receive the error message "no module named hal". 
inside the virtual environment made sure to  export PYTHONPATH=$/path/to/cactus/lib:$PYTHONPATH as well as for the submodules folder but I`m still unable to run the commandsand keep getting the following message

Traceback (most recent call last):
  File "hal2mafMP.py", line 21, in <module>
    from hal.stats.halStats import runParallelShellCommands
ModuleNotFoundError: No module named 'hal'

What am i missing here?

Thank you in advance for your help

**Comment by glennhickey** [comment]
This is a problem with your PYTHONPATH.  It must be set with `export PYTHONPATH=$(pwd)/lib` from the release directory. So when you do `ls $PYTHONPATH` you see
```
ls $PYTHONPATH
hal
```

**Comment by stlomo** [comment]
Solved, there was an issue in my conda environment occurring when trying to export PYTHONPATH

thank you
