### ISSUE TITLE
Minor issue with `--defaultMemory` in `cactus-prepare`

### ISSUE THREAD

**Issue by brantfaircloth** [ComparativeGenomicsToolkit/cactus#426]
Good morning,

I'm using a singularity image built from the docker container of `cactus_v1.3.0-gpu`, although the same error appears for me in `cactus-v1.2.3`.

When running `cactus-prepare` with the `--maxMemory` option, the script returns commands to run `preprocess`, `blast`, and `align` that look like:
```
cactus-preprocess jobstore/0 seqFile.txt steps-output/seqFile.txt --inputNames mm10 --workDir $WORK_DIR/tmpdir --configFile steps-output/config-prepared.xml --maxCores 48 --maxMemory 185.0 G
```
However, when run, these throw an error, e.g.:
```
cactus-preprocess: error: unrecognized arguments: G
```
The error results because it looks like the formatted string returned from `bytes2human` is adding a space between the decimal value and the units.  Changing the default format argument for `bytes2human`  to `fmt='%(value).1f%(symbol)s'` appears to fix the error.

-b

**Comment by glennhickey** [comment]
Good catch, thanks.  You're exactly right.
