### ISSUE TITLE
RuntimerError 

### ISSUE THREAD

**Issue by wyj-lzu** [ComparativeGenomicsToolkit/cactus#447]
Hi, thanks for a good program. But I meet an error when I run "cactus jobStore evolverMammals.txt evolverMammals.hal --root mr".
Like this : 
  RuntimeError: Command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '1549:1379', '-v', '/tmp/node-f6e537c8-993f-4acd-adf3-e7499e68faa4-cd4552b89e175889fa01e9985b2b2e9d/tmpxjynhmix/3f38da0a-b37e-4806-8f95-e8e3fe2b8dd8:/data', '--entrypoint', '/opt/cactus/wrapper.sh', '--name', '38f9d7fa-b460-4a5d-8534-1fc88bcd9a76', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:dec2b4591b8cb0ce4d38c1ead2664c498c05743c', 'cactus_blast_chunkSequences', 'INFO', '3000000', '0', 't5_ecb2jr/tmp_U4JjQgq0tl', 'tmp5fjv2qt5.tmp'] exited 126: stdout=
	[2021-03-27T09:47:47+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host GenekServer-2
How can I fix it?

**Comment by wyj-lzu** [comment]
I fixed it, thanks

**Comment by ekinda** [comment]
Hello @wyj-lzu , how did you fix the issue? I have the same problem when I try to run the same command. It only happens on a server and not on my local machine.

**Comment by ekinda** [comment]
The issue was that local cactus binary path was not exported to $PATH variable and thus docker was called. 
It would be nice to add in the setup guide that .bashrc (or equivalent) has to be edited for a permanent fix.
