### ISSUE TITLE
LastzRepeatMaskJob fail with BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by leleory** [ComparativeGenomicsToolkit/cactus#462]
Hi Cactus team,

I built Cactus from source on a server. The test run with evolverMammals.txt worked fine, but when I started a test with subsets of two mammalian genomes I got errors in the LastzRepeatMaskJob stages.
Example:
Issued job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/o/instance-y1s1cuex with job batch system ID: 179 and cores:
 1, disk: 2.0 G, and memory: 4.0 G
Could not start job 179: Traceback (most recent call last):
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/toil/batchSystems/singleMachine
.py", line 396, in _startChild
    env=dict(os.environ, **environment))
  File "/opt/apps/python/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/apps/python/3.6.9/lib/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable

Is there a solution to this problem?

Thank you,
Lel

Log file is attached:
[cactus_lastzrepmask_error.log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/6333710/cactus_lastzrepmask_error.log.txt)

**Comment by adamnovak** [comment]
It looks like we are asking the OS to start a process for us and the OS is complaining it can't because we have run out of something.

It looks like this happens shortly after trying to start a few hundred other jobs. Are you sure you aren't hitting some kind of per-user total process limit on your system? What does `ulimit -a` say?

**Comment by leleory** [comment]
There was only this test running on the server, so there were no other jobs taking up resources. Here is the result of ulimit -a:

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2067175
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 49152
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by leleory** [comment]
When I re-run the cactus-preprocess jobs with:
cactus-preprocess jobstore/0 pafr_sscr.txt steps-output/pafr_sscr.txt --inputNames phaafr1 susscr11 --logFile pafr_sscr.log --logLevel DEBUG --retryCount 0 --maxCores 32 --maxMemory 400.0G
cactus starts to repair the jobs and then issues them. It appears to issue over a thousand jobs in one go and these then almost all fail with [Errno 11]. Only around 30 jobs survive and run to completion, so I can progress with 30 jobs per re-start. 
Is it correct to assume that cactus-preprocess submits all the failed jobs in one go without taking into account the avaialable cores, or does it submits new jobs because the previous ones were failing?
Is there a way I can tell cactus how many concurrent jobs can be run on the system? Does the maxCores param is used for this? 
Thanks,
Lel

**Comment by glennhickey** [comment]
Cactus can *submit* millions of jobs at a time, but it will only ever attempt to *run* at most the number specified by `--maxCores`.  When you run `top` do you really see hundreds of cactus processes executing at once?

**Comment by adamnovak** [comment]
Hm. 1024 processes/threads is a pretty low limit, but Glenn is right that we shouldn't be launching more than ~32 jobs at a time. And the actual `Launched job 37 as child 75403` lines in the log don't seem to me to contradict that.

Is Cactus maybe starting a bunch of binaries that immediately fork out to one thread per core, and not limiting them to job requirements? If 32 processes start and each sees a 32 core system and starts 32 threads, there goes your entire 1024 `ulimit`.

**Comment by leleory** [comment]
Just re-started cactus-preprocess twice and I saw once over a hundred and second time over 70 jobs, like (from ps -eo args):
/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/bin/python /mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/bin/_toil_worker LastzRepeatMaskJob file:/groups2/suids/cactus/warthog_pig/jobstore/0 kind-LastzRepeatMaskJob/instance-eud10r7g

Not sure why so many as the maxCores is set to 32. These jobs then almost immediately fail and only a few stays on. 
Is it possible to slow down job submission in single_machine mode?

**Comment by leleory** [comment]
Looking into the toil/batchSystems/singleMachine.py script it states:
"If running in debug-worker mode, jobs are run immediately as they are sent
    to the batch system, in the sending thread, and the daddy thread is not
    run. But the queues are still used."
This may be the reason why I see so many jobs spawn at the same time...

**Comment by leleory** [comment]
Interesting, when running cactus-preprocess with --logLevel ERROR I got error messages on STDERR which do not show up in the log file (--logFile). These reads:
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 2067175 max
[2021-04-19T20:23:11+0100] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code -11 (indicating failure) from job _toil_worker LastzRepeatMaskJob file:/groups2/suids/cactus/warthog_pig/jobstore/0 kind-LastzRepeatMaskJob/B/instance-uo4wxdhg.

So the problem is as  @adamnovak suggested was that the 1024 thread limit was reached due to openBLAS spawning too many threads by default. See here:
#https://github.com/bcgsc/mavis/issues/185

Setting OMP_NUM_THREADS to 1 solves the probelm.
export OMP_NUM_THREADS=1

Thanks,
Lel

**Comment by glennhickey** [comment]
No idea which part of `cactus-preprocess` would be using numpy, but glad you found a fix!  Maybe it's happening inside Biopython...

**Comment by leleory** [comment]
numpy is certainly there in the error message (in any case the pipeline is running OK now):
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 2067175 max
Traceback (most recent call last):
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/bin/_toil_worker", line 5, in <module>
    from toil.worker import main
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/toil/__init__.py", line 27, in 
<module>
    from docker.errors import ImageNotFound
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/docker/__init__.py", line 2, in
 <module>
    from .api import APIClient
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/docker/api/__init__.py", line 2
, in <module>
    from .client import APIClient
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/docker/api/client.py", line 8, 
in <module>
    import websocket
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/websocket/__init__.py", line 21
, in <module>
    from ._abnf import *
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/websocket/_abnf.py", line 37, i
n <module>
    import numpy
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/numpy/__init__.py", line 140, i
n <module>
    from . import core
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/numpy/core/__init__.py", line 2
2, in <module>
    from . import multiarray
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/numpy/core/multiarray.py", line
 12, in <module>
    from . import overrides
  File "/mnt/ris-fas1a/linux_users2/leory2/src/cactusenv/lib/python3.6/site-packages/numpy/core/overrides.py", line 
7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
