### ISSUE TITLE
Using Cactus with protein sequences

### ISSUE THREAD

**Issue by stlomo** [ComparativeGenomicsToolkit/cactus#468]
Hello everyone

This may sound like an impossible task but is there any way to implement different substitution matrices beside the JC model used by Cactus in order to use it for alignment of very long protein sequences (treating them as small genomes)

**Comment by glennhickey** [comment]
No, but there are [many other aligners out there that can work on protein sequences](https://en.wikipedia.org/wiki/List_of_sequence_alignment_software#Multiple_sequence_alignment)
