### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dukecomeback** [ComparativeGenomicsToolkit/cactus#525]
Hi,

I'm trying to install cactus from source, and the process drop out at:
```
/home/k_d239/miniconda3/lib//libicuuc.so.58：undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/k_d239/miniconda3/lib//libicuuc.so.58：undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
```
I'll appreciate it if anyone could give any suggestions. Thank you.

         Sincerely,

**Comment by glennhickey** [comment]
I can't help you with your miniconda environment, but have you thought about just using the binary release? 
https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.0.1

**Comment by dukecomeback** [comment]
Thank you very much, it's very helpful!
