### ISSUE TITLE
running on grid engine, unable to run jobs, system does not allow memory specification change

### ISSUE THREAD

**Issue by matt-shenton** [ComparativeGenomicsToolkit/cactus#529]
Hi there,

I am trying to run the pipeline on a grid engine system.

Seems like the memory specification cannot be changed by toil:

`cactus-graphmap ./jobstore evolverPrimates.txt primates.gfa primates.paf --outputFasta primates.gfa.fa --realTimeLogging --binariesMode local --batchSystem grid_engine`
(submitted in a shell script with qsub)

`[2021-06-29T12:00:28+0900] [MainThread] [I] [toil.leader] Issued job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1o3reeln with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Unable to run job: List access specifier of attribute "l_hard" in "M.default" does not allow modification but value of element "h_vmem" was changed from "4G" to "2097152K".
Exiting.`

Is there a way to just use the system default, or otherwise get round this problem? Many thanks for your help.
Matt

**Comment by glennhickey** [comment]
Not too sure what's going on.  Could you please post this as an issue here: https://github.com/DataBiosphere/toil ?

**Comment by matt-shenton** [comment]
Thanks a lot for looking into it. I opened an issue there at 

https://github.com/DataBiosphere/toil/issues/3689
