### ISSUE TITLE
AssertionError on running hal2assemblyHub.py 

### ISSUE THREAD

**Issue by mglgnn** [ComparativeGenomicsToolkit/cactus#531]
Hi everyone,
I am trying to fix the following issue. I suppose there is something I am doing wrong. What I want is the creation of an assembly hub.
On running the following (the image for Cactus has been already loded):
`sudo docker run -v $(pwd):/data --rm -it f40caa9dcf7f47eabb654cecd532f62b613e3b497d6ae2a5a913e43b0a77832f hal2assemblyHub.py /data/jobStore /data/evolverMammals.hal /data/out`

I receive the following error, something relating toil:
Traceback (most recent call last):
  File "/usr/local/bin/hal2assemblyHub.py", line 452, in <module>
    main()
  File "/usr/local/bin/hal2assemblyHub.py", line 446, in main
    checkOptions(parser, options)
  File "/usr/local/bin/hal2assemblyHub.py", line 422, in checkOptions
    assert False
AssertionError

I assume the jobstore parameter can be any empty directory as for Cactus itself.

Thanks a lot for the usual support.
Best,
Giovanna

**Comment by glennhickey** [comment]
Please try the latest release https://github.com/ComparativeGenomicsToolkit/cactus/releases

**Comment by mglgnn** [comment]
Thanks a lot Glenn. The latest release fixed the issue.
