### ISSUE TITLE
LD_RUN_PATH, LDFLAGS ignored by Makefile

### ISSUE THREAD

**Issue by michaelgreenburg** [ComparativeGenomicsToolkit/cactus#56]
Is there a way to pass `-Wl,--enable-new-dtags,-rpath,/some/path` to the linker when using the included Makefile? I have GCC installed in a non-standard location and would like the ability to embed a RUNPATH in the libraries and binaries, but exporting LD_RUN_PATH and/or LDFLAGS has no effect. I could just `patchelf` everything after running `make`, but presumably there's a better way. I don't consider setting LD_LIBRARY_PATH as a real solution, just a great way to mess up other software's functionality. Is there another flag that I can use, or a modification to the Makefile that I should try?

**Comment by diekhans** [comment]
LDFLAGS should now work
