### ISSUE TITLE
Error running cactus-align

### ISSUE THREAD

**Issue by jhoshizaki** [ComparativeGenomicsToolkit/cactus#561]
Hi,

I am running cactus-align and according to the log, it fails while running cactus_consolidated (after "ran extended flowers ready for bar" and before running cactus bar). It says "Got exit code 1 (indicating failure) from job _toil_worker"... Exit reason: none.  What might have caused this error?

...
[2021-08-04T17:45:27+0100] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): Ran extended flowers ready for bar, 1 seconds have elapsed
[2021-08-04T17:45:27+0100] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusConsolidated file:/WGA/cactus$
[2021-08-04T17:45:27+0100] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusConsolidated' kind-CactusConsolidated/instance-at8e0luz
Exit reason: None
[2021-08-04T17:45:27+0100] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusConsolidated' kind-CactusConsolidated/instance-at8e0luz
...

Thanks!

**Comment by glennhickey** [comment]
Can you share the rest of the log?  There's usually a more informative error message floating around somewhere.

**Comment by jhoshizaki** [comment]
Thanks Glenn for your time. Here is the whole log:
[cactus.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/6962576/cactus.txt)

**Comment by glennhickey** [comment]
Your error is
```
RuntimeError: Command ['cactus_consolidated', '--sequences', '3D7 /tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpucvetdbp.tmp IT /tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpraqo1q_m.tmp KE /tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpw1_q_lo3.tmp _MINIGRAPH_ /tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpdj7rwynq.tmp', '--speciesTree', '(3D7:1.0,IT:1.0,KE:1.0,_MINIGRAPH_:1.0)Anc0;', '--logLevel', 'INFO', '--alignments', '/tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpyj8u0h6b.tmp', '--params', '/tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpzwgdb6zl.tmp', '--outputFile', '/tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpgclogrdh.tmp', '--outputHalFastaFile', '/tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpw5pr5ymz.tmp', '--outputReferenceFile', '/tmp/c0b47176cb1858fc877fc70b20bab504/f227/b90f/tmpbvr_kex0.tmp', '--referenceEvent', 'Anc0', '--threads', '22']
signaled SIGILL: stdout=, stderr=None
```
Which usually means your CPU isn't new enough to run Cactus.  There's some more information on the [releases](https://github.com/ComparativeGenomicsToolkit/cactus/releases) page about hardware requirements, as well as a link to download the "legacy" binaries that *may* run on older systems.
