### ISSUE TITLE
Cactus Run to Stop，No error is reported in the log file

### ISSUE THREAD

**Issue by zhangyuxin1012** [ComparativeGenomicsToolkit/cactus#563]
When running Cactus with Docker, there is a strange phenomenon that sometimes it fails .
However, the error message cannot be found in the log file. The task has been stopped. I don't know what causes this phenomenon.  This is the end of the log file 
![image](https://user-images.githubusercontent.com/85481560/128793103-086c88b8-93e2-4ff6-a88c-ee7daa4e84b7.png)

**Comment by panpandzf** [comment]
Dear Zhang
Hello, I encountered the same problem as you, did you solve it?
best
