### ISSUE TITLE
cactus_consolidated advice requested

### ISSUE THREAD

**Issue by larryns** [ComparativeGenomicsToolkit/cactus#610]
Hi,

I've been running cactus on four mammalian genomes as:

```
cactus \
    ./jobStore \
    ./mammals.txt \
    ./mammals.hal \
   --binariesMode local \
   --batchSystem single_machine \
   --maxCores 94 \
   --maxMemory 700G \
   --workDir "./work" \
   --realTimeLogging
```

I've installed cactus with python3.8 from source as instructed in the README on this page. Cactus has been running for 8 days, but of those 8, cactus_consolidated has been running for 3 days and is still running. The log says 1 job running and 1 issued and waiting to run. For the first 12 hours or so, cactus_consolidated ran at 40% CPU, but now it's only using one core (CPU usage = 1.5%). The memory usage right now is about 220GB, but never eclipsed 340GB. The machine has 96 cores, 784GB of RAM, and no GPU.

My question is: is this normal that cactus_consolidated should take this long and use so little of the resources? Am I doing something wrong, or is there something I can improve here to make it faster or at least use the resources more efficiently? Would getting a smaller box with a GPU help (I'm using AWS on-demand EC-2 instances)?

Thanks very much for any advice/help.
-Larry.

**Comment by glennhickey** [comment]
3 days is a bit longer than I'd expect `cactus_consolidated` to run, especially with the latest version of cactus, but it is normal for it to run for stretches using only one thread.  It can't use the GPU, so if you want it to use resources more efficiently, I guess you'd want something with fewer cores and less memory. 

What's your input here?  One thing that's important for it to run smoothly is masking the input sequences with RepeatMasker.

**Comment by larryns** [comment]
Hi Glenn,

Thanks for the feedback. I should have mentioned: it's 4 mammalian genomes (3 reference with only somatic chromosomes, random chromosomes removed for human, mouse, cat, and 1 de novo assembly), all were softmasked with repeat masker.

It's approaching 4 days and still using a single core. Any further thoughts? Otherwise, I'll just let it keep going.

Thanks again.
Larry.

**Comment by larryns** [comment]
Yes, I am. What file should I check?

**Comment by glennhickey** [comment]
That tells us it's stuck in the "reference" phase.  The next message should be `cactus_consolidated(Anc2): Ran cactus make reference bottom up coordinates, xxxxx seconds have elapsed.`  I don't think I've ever seen it take anywhere near this long here...  

@benedictpaten do you have any ideas what might be going on?

**Comment by larryns** [comment]
So it's going on 5 days, so I think something is definitely wrong.

1. Should I let it abort the job?
2. If yes, is there a way to restart just the cactus consolidated part in a debug mode so I can trace it? I'm not sure if it's written in C or python or something else, but either way, I can use a debugger.

Thanks!
Larry.

**Comment by glennhickey** [comment]
Yeah, looking like you're just wasting money at this point.  Sorry!

The Cactus release binaries don't contain any debug symbols, so you won't have much luck using them to debug.  If you've built your own, then you can try attaching gdb to it (-p) as it's running now.  Otherwise, your best bet is to note the exact `cactus_consolidated` command being run, and collect all the input files from the command -- pretty much everything but the newick tree is a file, I think, and they should all have nonsense names and be in your tmp/work directory.  Make sure you copy every file while it's being run, as they will disappear as soon as the command finishes or aborts.  Once you've copied them, you can rerun  `cactus_consolidated` directly on them in the debugger, adjusting their paths to reflect wherever you put them.

**Comment by larryns** [comment]
Okay thanks for the advice. I'll look into this and probably get back to you over the next coming days with what I've found.

**Comment by larryns** [comment]
I wanted to give an update on this problem, and I've tried a few things.

1. I thought maybe there was an issue with my local installation so I tried the same process using the Docker image. After 8 days I killed the job because it looks like the problem exists with the Docker image too.
2. I removed the optimization compiler flag (-O3), and re-ran just the cactus_consolidated part. It still takes 2-3 days to run though. The problem as far as I can tell is in `flower_addEnd` in `cactusFlower.c`, and the `while` loop. In some cases `i` actually increases during the loop so the loop never terminates. That's not supposed to happen right?

I'm still trying to work this out. It's getting expensive, and each debug attempt takes a few days, but if I can get this working, it'd be a huge addition to my gene annotation pipeline.

Please let me know if I'm missing something here or you have some other insight.

Thanks!

**Comment by glennhickey** [comment]
The only way I can see `i` increasing in that loop is if the stack is getting corrupted by a bug somewhere else.  Unfortunately, errors like that are very difficult to pinpoint even when I can reproduce locally.  Unfortunately, I don't really have much to offer you in the way of helpful advice, though if ever you can share the input / command line I'd be happy to take a crack at it.

I will also ping @benedictpaten again to see if he has any thoughts of how that function could go wrong.

**Comment by glennhickey** [comment]
Also, if you still have it in gdb, do you mind posting a few stack traces?

**Comment by larryns** [comment]
Hi Glenn,

Yeah, that's what I figured: the memory was getting corrupted in some memory that is accessed either in the end_getName or swap function calls. I've added a few checks in the code to try to narrow down the problem. The issue is that every time I make a code change, it takes 2-3 days to run again. 

Unfortunately, I don't still have gdb running, but the next time it gets to the problem area, I'll attach and send you a stack trace, along with the modified code I've made.

Also, the alignment I was doing was 3 mammalian species (Felis catus, Homo sapiens, and Mus musculus) with a de novo assembly. The 3 species were the softmasked versions downloaded from UCSC: felCat9.fa.masked, hg38.fa.masked, and mm39.fa.masked). I then went through the fasta files and extracted just the somatic, sex, and mitochondrial chromosomes (I removed the random and decoy chromosomes). Unfortunately, I can't share the de novo assembly because it's confidential, but I'm running an alignment with just the 3 published mammalian genomes, to see if I run into the same problem. If I do, I can share all that with you. I can also share the Newick files with the phylogenetic tree for both the 3-mammalian, and 4-mammalian trees. Let me know if you would like to see that.

I'll let you know as I progress, but it will be a bit slow going. Thanks for your help.

-Larry.

**Comment by larryns** [comment]
So it looks like the problem persists with the reference genome. Here's the species tree:

```
(Felis_catus_FELIDAE_CARNIVORA:82.12274875,(Homo_sapiens_HOMINIDAE_PRIMATES:74.1
8967294,Mus_musculus_MURIDAE_RODENTIA:74.18968263):7.933063);

*Felis_catus_FELIDAE_CARNIVORA /genomes/felCat9.fa.chr
*Homo_sapiens_HOMINIDAE_PRIMATES /genomes/hg38.fa.chr
*Mus_musculus_MURIDAE_RODENTIA /genomes/mm39.fa.chr
```

The fasta files were downloaded from ucsc as the softmasked version and all the random and decoy chromosomes removed. The fasta files only have the somatic chromosomes, sex chromosomes and mitochondrial chromosome.

Here's my cactus command line:
```
docker run \
	-v $(pwd):/data \
	-v /data_disk2/public/genomes:/genomes \
	--rm \
	-it quay.io/comparative-genomics-toolkit/cactus:v2.0.4 \
	cactus \
		/data/jobStore \
		/data/mammals3.txt \
		/data/mammals3.hal \
		--binariesMode local \
		--restart \
		--maxCores 90 \
		--workDir /data/work \
		--realTimeLogging
```

**Comment by glennhickey** [comment]
OK, I've set this going somewhere with 256G RAM and 44 cores.  These are the commands I'm running
```
# install cactus
wget https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v2.0.4/cactus-bin-v2.0.4.tar.gz
tar zxf cactus-bin-v2.0.4.tar.gz
cd cactus-bin-v2.0.4
virtualenv -p python3.6 venv
source venv/bin/activate
pip install -U setuptools pip
pip install -U -r ./toil-requirement.txt
pip install -U .
export PATH=$(pwd)/bin:$PATH
export PYTHONPATH=$(pwd)/lib:$PYTHONPATH
cd ..

# download data
wget https://hgdownload.cse.ucsc.edu/goldenPath/felCat9/bigZips/felCat9.fa.gz
wget https://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
wget https://hgdownload.cse.ucsc.edu/goldenPath/mm39/bigZips/mm39.fa.gz
gzip -d *.gz

# extract chromosomes
samtools faidx felCat9.fa
samtools faidx hg38.fa
samtools faidx mm39.fa
rm -f felCat9.fa.chr
for i in `grep -v random felCat9.fa.fai | grep -v chrUn | awk '{print $1}'`; do samtools faidx felCat9.fa $i >> felCat9.fa.chr; done
rm -f hg38.fa.chr
for i in `grep -v random hg38.fa.fai | grep -v chrUn | grep -v alt | awk '{print $1}'`; do samtools faidx hg38.fa $i >> hg38.fa.chr; done
rm -rf mm39.fa.chr
for i in `grep -v random mm39.fa.fai | grep -v chrUn | awk '{print $1}'`; do samtools faidx mm39.fa $i >> mm39.fa.chr; done

# make input
printf "(Felis_catus_FELIDAE_CARNIVORA:82.12274875,(Homo_sapiens_HOMINIDAE_PRIMATES:74.18967294,Mus_musculus_MURIDAE_RODENTIA:74.18968263):7.933063);\n" > mammals3.txt
printf "*Felis_catus_FELIDAE_CARNIVORA $(pwd)/felCat9.fa.chr\n" >> mammals3.txt
printf "*Homo_sapiens_HOMINIDAE_PRIMATES $(pwd)/hg38.fa.chr\n" >> mammals3.txt
printf "*Mus_musculus_MURIDAE_RODENTIA $(pwd)/mm39.fa.chr\n" >> mammals3.txt

# run cactus step by step to make debugging faster
cactus-prepare ./mammals3.txt --outDir ./m3 --defaultCores 44 > COMMANDS
cat COMMANDS

## Preprocessor
cactus-preprocess ./jobstore/0 ./mammals3.txt ./m3/mammals3.txt --inputNames Felis_catus_FELIDAE_CARNIVORA Homo_sapiens_HOMINIDAE_PRIMATES Mus_musculus_MURIDAE_RODENTIA --realTimeLogging --logInfo --retryCount 0 --maxCores 44

## Alignment

### Round 0
cactus-blast ./jobstore/1 ./m3/mammals3.txt ./m3/Anc1.cigar --root Anc1 --realTimeLogging --logInfo --retryCount 0 --maxCores 44
cactus-align ./jobstore/2 ./m3/mammals3.txt ./m3/Anc1.cigar ./m3/Anc1.hal --root Anc1 --realTimeLogging --logInfo --retryCount 0 --maxCores 44 
hal2fasta ./m3/Anc1.hal Anc1 --hdf5InMemory > ./m3/Anc1.fa

### Round 1
cactus-blast ./jobstore/3 ./m3/mammals3.txt ./m3/Anc0.cigar --root Anc0 --realTimeLogging --logInfo --retryCount 0 --maxCores 44
cactus-align ./jobstore/4 ./m3/mammals3.txt ./m3/Anc0.cigar ./m3/out.hal --root Anc0 --realTimeLogging --logInfo --retryCount 0 --maxCores 44 
hal2fasta ./m3/out.hal Anc0 --hdf5InMemory > ./m3/Anc0.fa

## HAL merging
halAppendSubtree ./m3/out.hal ./m3/Anc1.hal Anc1 Anc1 --merge --hdf5InMemory

```

**Comment by larryns** [comment]
So not exactly. I downloaded the softmasked files:
hg38.fa.masked.gz
mm39.fa.masked.gz
felCat9.fa.masked.gz

Don't know if that makes a difference.

**Comment by glennhickey** [comment]
That could very well explain it.  I could imagine an issue (possibly arising in v2.0 when we switched base aligners which my handle Ns differently) where **hard**masking is tripping it up.  We generally only run and test on **soft**masked genomes.  

I'll let my run go through it'll almost certainly work, then try to reproduce on the hardmasked inputs.  

But I strongly suggest you use softmasked sequences for Cactus!  For reference:

this is softmasked (masked regions lowercase)
https://hgdownload.cse.ucsc.edu/goldenPath/felCat9/bigZips/felCat9.fa.gz

this is hardmasked (masked regions Ns)
https://hgdownload.cse.ucsc.edu/goldenPath/felCat9/bigZips/felCat9.fa.masked.gz

**Comment by larryns** [comment]
Apologies, I was looking at the wrong directory. I did use the **softmasked** ones: felCat9.fa.gz, hg38.fa.gz, mm39.fa.gz. Sorry for the confusion.

**Comment by glennhickey** [comment]
The commands I posted above *did* reproduce the issue.  Pretty weird bug, and I haven't had a chance to pinpoint it yet.  One thing that did seem to fix it was correcting the branch lengths in your input tree (Cactus expects these written in terms of expected substitutions per site) -- it ran through in 10 hours when using more realistic values.  So could be some kind of numerical bug getting triggered by the giant branches, but I don't really know -- I may just add a sanity check to abort with an error at startup in the face of giant branches if I can't figure it out would be better than running forever. 

```
gdb) run  --sequences "Felis_catus_FELIDAE_CARNIVORA /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpg2t2e7_d.tmp Homo_sapiens_HOMINIDAE_PRIMATES /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpojmu66ok.tmp Mus_musculus_MURIDAE_RODENTIA /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvt1i796a.tmp" --speciesTree "(Felis_catus_FELIDAE_CARNIVORA:0.2,(Homo_sapiens_HOMINIDAE_PRIMATES:0.15,Mus_musculus_MURIDAE_RODENTIA:0.35)Anc1:0.02)Anc0;" --logLevel INFO --alignments /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvpemfrr0.tmp --params /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpzqinrtwz.tmp --outputFile /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpfqpvse7q.tmp --outputHalFastaFile /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmp0843lna7.tmp --outputReferenceFile /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmp069ogpc0.tmp --outgroupEvents Felis_catus_FELIDAE_CARNIVORA --referenceEvent Anc1 --secondaryAlignments /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmprb47b20j.tmp --threads 64
Starting program: /work/cactus/bin/cactus_consolidated --sequences "Felis_catus_FELIDAE_CARNIVORA /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpg2t2e7_d.tmp Homo_sapiens_HOMINIDAE_PRIMATES /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpojmu66ok.tmp Mus_musculus_MURIDAE_RODENTIA /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvt1i796a.tmp" --speciesTree "(Felis_catus_FELIDAE_CARNIVORA:0.2,(Homo_sapiens_HOMINIDAE_PRIMATES:0.15,Mus_musculus_MURIDAE_RODENTIA:0.35)Anc1:0.02)Anc0;" --logLevel INFO --alignments /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvpemfrr0.tmp --params /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpzqinrtwz.tmp --outputFile /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpfqpvse7q.tmp --outputHalFastaFile /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmp0843lna7.tmp --outputReferenceFile /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmp069ogpc0.tmp --outgroupEvents Felis_catus_FELIDAE_CARNIVORA --referenceEvent Anc1 --secondaryAlignments /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmprb47b20j.tmp --threads 64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Params file: /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpzqinrtwz.tmp
Output file string : /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpfqpvse7q.tmp
Output hal fasta file string : /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmp0843lna7.tmp
Output reference fasta file string : /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmp069ogpc0.tmp
Sequence files and events: Felis_catus_FELIDAE_CARNIVORA /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpg2t2e7_d.tmp Homo_sapiens_HOMINIDAE_PRIMATES /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpojmu66ok.tmp Mus_musculus_MURIDAE_RODENTIA /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvt1i796a.tmp
Alignments file: /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvpemfrr0.tmp
Secondary alignments file: /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmprb47b20j.tmp
Constraint alignments file: (null)
Species tree: (Felis_catus_FELIDAE_CARNIVORA:0.2,(Homo_sapiens_HOMINIDAE_PRIMATES:0.15,Mus_musculus_MURIDAE_RODENTIA:0.35)Anc1:0.02)Anc0;
Outgroup events: Felis_catus_FELIDAE_CARNIVORA
Reference event: Anc1
Loaded the parameters files, 0 seconds have elapsed
Set up the cactus disk, 0 seconds have elapsed
Constructed the first flower
Going to build the event tree with newick string: (Felis_catus_FELIDAE_CARNIVORA:0.2,(Homo_sapiens_HOMINIDAE_PRIMATES:0.15,Mus_musculus_MURIDAE_RODENTIA:0.35)Anc1:0.02)Anc0;
Parsed the tree
Constructed the basic event tree
Assigning sequence /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpg2t2e7_d.tmp to Felis_catus_FELIDAE_CARNIVORA
Processing file: /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpg2t2e7_d.tmp
The file /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpg2t2e7_d.tmp is specified incomplete, the sequences will not be attached
Assigning sequence /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpojmu66ok.tmp to Homo_sapiens_HOMINIDAE_PRIMATES
Processing file: /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpojmu66ok.tmp
The file /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpojmu66ok.tmp is specified incomplete, the sequences will not be attached
Assigning sequence /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvt1i796a.tmp to Mus_musculus_MURIDAE_RODENTIA
Processing file: /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvt1i796a.tmp
The file /work/work/3d64c26de3045309861c0b4e860d87bb/2e21/703c/tmpvt1i796a.tmp is specified incomplete, the sequences will not be attached
Constructed the initial flower with 57934 sequences and 6 events with string: ((Felis_catus_FELIDAE_CARNIVORA:0.2,(Homo_sapiens_HOMINIDAE_PRIMATES:0.15,Mus_musculus_MURIDAE_RODENTIA:0.35)Anc1:0.02)Anc0:9.22337e+18)ROOT:9.22337e+18;
Established the first Flower in the hierarchy, 56 seconds have elapsed
Converted alignment coordinates, 264 seconds have elapsed
Stripped the unique IDs, 264 seconds have elapsed
Starting annealing round with a minimum chain length of 64 and an alignment trim of 3
There were 95686099 blocks in the sequence graph, representing 3427147883 total aligned bases
Block degree stats: min 1, avg 3.691379, median 2, max 1087452
Block support stats: min 0.000000, avg 1.126153, median 1.000000, max 6.000000
Starting melting round with a minimum chain length of 2
A melting round is destroying 8533111 blocks with an average degree of 5.317839 from chains with length less than 2. Total aligned bases lost: 45377709
Starting melting round with a minimum chain length of 4
A melting round is destroying 9759329 blocks with an average degree of 3.687207 from chains with length less than 4. Total aligned bases l
ost: 77570241
Starting melting round with a minimum chain length of 8
A melting round is destroying 16795687 blocks with an average degree of 2.659982 from chains with length less than 8. Total aligned bases lost: 221211437
A melting round is destroying 11390372 blocks with an average degree of 2.663327 from chains with length less than 64. Total aligned bases lost: 281951493
Destroying 15006372 recoverable blocks
The blocks covered 485500514 columns for a total of 1055450250 aligned bases
Destroying 359561 recoverable blocks
The blocks covered 9750848 columns for a total of 31662415 aligned bases
Destroying 28219 recoverable blocks
The blocks covered 739062 columns for a total of 2395577 aligned bases
Destroying 1430 recoverable blocks
The blocks covered 35079 columns for a total of 133476 aligned bases
Destroying 342 recoverable blocks
The blocks covered 8772 columns for a total of 26269 aligned bases
Pinch graph component with 263435 nodes and 288063 edges is being split up by breaking 13127 edges to reduce size to less than 877 max, but found 347 pointless edges
Attaching the sequence to the cactus root 347330, header chr1 with length 248956422 and 33607494 total bases aligned and 0 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347396, header chr2 with length 242193529 and 36066765 total bases aligned and 223193 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347420, header chr3 with length 198295559 and 30450308 total bases aligned and 188528 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347426, header chr4 with length 190214555 and 25769809 total bases aligned and 360306 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347432, header chr5 with length 181538259 and 27355200 total bases aligned and 696918 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347438, header chr6 with length 170805979 and 23871648 total bases aligned and 2463097 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347600, header chrX with length 169476592 and 21636558 total bases aligned and 403826 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347444, header chr7 with length 159345973 and 21899570 total bases aligned and 563045 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347576, header chr7 with length 144995196 and 19721466 total bases aligned and 688939 bases aligned to other chromosome threads
Attaching the sequence to the cactus root 347606, header chrY with length 91455967 and 8115146 total bases aligned and 596850 bases aligned to other chromosome threads
Ran cactus caf, 16258 seconds have elapsed
Ran extended flowers ready for bar, 16602 seconds have elapsed
Ran cactus bar (use poa:1), 27788 seconds have elapsed
There are 9 layers in the flowers hierarchy
In the 0 layer there are 1 flowers in the flowers hierarchy
[Detaching after vfork from child process 60110]
[Detaching after vfork from child process 60112]
In the 1 layer there are 18907439 flowers in the flowers hierarchy
In the 2 layer there are 24828778 flowers in the flowers hierarchy
In the 3 layer there are 2721199 flowers in the flowers hierarchy
In the 4 layer there are 150138 flowers in the flowers hierarchy
In the 5 layer there are 13624 flowers in the flowers hierarchy
In the 6 layer there are 1875 flowers in the flowers hierarchy
In the 7 layer there are 265 flowers in the flowers hierarchy
In the 8 layer there are 25 flowers in the flowers hierarchy
Ran cactus make reference, 30393 seconds have elapsed
Ran cactus make reference bottom up coordinates, 32687 seconds have elapsed
Ran cactus make reference top down coordinates, 32863 seconds have elapsed
Ran cactus to hal stage, 33425 seconds have elapsed
Dumped sequences for hal file, 33450 seconds have elapsed
Dumped reference sequences, 33455 seconds have elapsed
[Detaching after vfork from child process 60114]
[Detaching after vfork from child process 60116]
Cactus consolidated is done!, 33456 seconds have elapsed
```

**Comment by larryns** [comment]
Thanks for the feedback. Do you have any recommendations on generating the input tree? I got my data from "Inferring the mammal tree: Species-level sets of phylogenies for questions in ecology, evolution, and conservation", PLoS Bio., 2019. Then creating a consensus tree using the ape R package. How would you ordinarily come up with a tree?

Thanks!

**Comment by glennhickey** [comment]
You can take a look in the Cactus [paper](https://doi.org/10.1038/s41586-020-2871-y) which I thnk used Phast.  Most of the data referred to in that paper should be [here](https://cglgenomics.ucsc.edu/data/cactus/). raxml may be another tool to look at.

Branch length estimation is tricky, as it depends on a representative alignment of neutrally evolving sites.  Luckily, Cactus is fairly robust to errors, so long as the values are in the right ballpark. 

I'd like to have a push-button genome tree generator to use upstream of Cactus one day, as it's a common issue.

**Comment by larryns** [comment]
Doesn't phylofit require a multiple alignment to begin with? So then I'd need to do two multiple alignments? One to get the branch lengths for Cactus, and the Cactus itself. Is that right?

**Comment by diekhans** [comment]
Approximate branch lengths are fine for the cactus guide tree.
Inaccuracies will not dramatically change the alignment.  We
have never run the alignment a second time with the phylofit
results.

**Comment by larryns** [comment]
Thanks for the feedback. What I meant was, isn't cactus doing in effect a multiple alignment? So, I'm really computing two multiple alignments of genomes? First one with phylofit to get a guide tree, and then a second with cactus to get the final multiple alignment. I'd like to make sure I'm understanding the process fully. 

Btw, I ended up using the branch lengths in the phylogenetic tree from the 100 vertebrate alignment at UCSC. Giving that a shot now.

**Comment by diekhans** [comment]
Yes, cactus is doing a multiple alignment. phylofit takes an existing
multiple alignment as input, it doesn't do the alignment itself.
Hence the approach of estimating the branch length for cactus and
using phylofit to compute more accurate tree for other analysis.

100 vertebrate is a great starting point.

**Comment by larryns** [comment]
Great, thank you very much @diekhans and @glennhickey. I'll report back how my latest attempt goes once it's done.

**Comment by larryns** [comment]
So I ran cactus again using the docker image with the branch lengths from the 100 vertebrates from UCSC. It looks like cactus_consolidated completed this time, but then I got this problem:

```
2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] 2022-01-05 21:00:11.569441: Successfully ran: "cactus_consolidated --sequences 'felCat9 /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpltj7ak_m.tmp hg38 /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpxb_pom6c.tmp mm39 /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpbo1ritlv.tmp myoLuc2 /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmp5grr3t31.tmp' --speciesTree '((hg38:0.15,mm39:0.36)Anc1:0.02,(felCat9:0.15,myoLuc2:0.19)Anc2:0.037)Anc0;' --logLevel INFO --alignments /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpdwgtacsc.tmp --params /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpze19602_.tmp --outputFile /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpa5e8kblo.tmp --outputHalFastaFile /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpxe4jrhdl.tmp --outputReferenceFile /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpm8511gjn.tmp --outgroupEvents 'felCat9 myoLuc2' --referenceEvent Anc1 --secondaryAlignments /data/work/4af0230c53885849986acf85ef9d5987/ae26/4421/tmpv8zal_7q.tmp --threads 96" in 95439.5087 seconds
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Elapsed (wall clock) time (h:mm:ss or m:ss): 26:30:39
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Average shared text size (kbytes): 0
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Average unshared data size (kbytes): 0
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Average stack size (kbytes): 0
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Average total size (kbytes): 0
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Maximum resident set size (kbytes): 241363060
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): Average resident set size (kbytes): 0
[2022-01-05T21:00:11+0000] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1):[2022-01-05T21:00:43+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064e outdirMin requirement, otherwise, consider increasing t[2022-01-05T21:00:43+0000] [MainThread] [I] [toil.leader] Issued job 'CactusBlastPhase' kind-CactusBlastPhase/instance-7yl4zcdz with job batch system ID: 135093 and cores: 1, disk: 2.0 Gi, and memory: 3.3 Girequested).us_consolidated(Anc1):[2022-01-05T21:00:43+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 14015615163306400] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1):[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 1401561516330640
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 14015615163306400] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1):[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 1401561516330646
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
[2022-01-05T21:00:44+0000] [Thread-1  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 51010 known to batch system 140156151633064
```

That went on for a long time, and then I just killed the process. I then tried restarting, but it looks like it's running cactus_consolidated all over again. Any idea what's going on?

**Comment by glennhickey** [comment]
No idea, other than you seem to be cursed.  Pinging @adamnovak who may have some context for this warning message.

**Comment by larryns** [comment]
Hahahahaha, well thanks for confirming. For a minute there I thought I was just paranoid. :)

I'll just re-run and see if it was just a fluke. Thanks for your help.

**Comment by glennhickey** [comment]
I just ran into the `[toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group` loop.  It can be reproduced by adding `--realTimeLogging` to this [new test](https://github.com/ComparativeGenomicsToolkit/cactus/pull/637/commits/79dddeb3deed4ff3b8e401631745535e0be05cda)

The work-around is this case is to not use the `--realTimeLogging` flag (sigh).  From what I can tell, this seems to be an issue when running cactus via `docker run` (as opposed to inside docker or with docker binaries)

**Comment by larryns** [comment]
So my curse is contagious. I'm trying to re-run cactus with the steps you outlined above in your post: https://github.com/ComparativeGenomicsToolkit/cactus/issues/610#issuecomment-998851966

That should work right? The only issue I have is even with maxCores set to maximum on the machine, CPU usage never seems to go beyond 50% like it did with ```docker run```. Is that expected and anything I can do to make it use more cores?

Thanks again for your help.

**Comment by adamnovak** [comment]
Toil will get stuck when things launched under the single machine batch system leave behind zombie child processes, and the `init` process (PID 1) doesn't do anything to reap them when it inherits them (for example, because it's whatever the leading process is in a Docker container and not a real `init` daemon).

This came up as https://github.com/DataBiosphere/toil/issues/3965, and we fixed that particular manifestation in https://github.com/DataBiosphere/toil/pull/3980 and we will be providing a real `init` in the Toil appliance containers in https://github.com/DataBiosphere/toil/pull/3974. But if you're using Toil inside other Docker containers you're going to run into this problem unless/until we change the single machine batch system to just tolerate an accumulation of orphan zombie children, or until you put a proper `init` in your container.

**Comment by glennhickey** [comment]
OK, I think this is all fixed.  Thanks for your help and patience
* Reference running too slow: #643 #647.
* Endless loop after consolidated:  #645
