### ISSUE TITLE
Can I change the guidance tree for the hal file?

### ISSUE THREAD

**Issue by lningyawen** [ComparativeGenomicsToolkit/cactus#614]
Hello,

I have used cactus to finish alignment and get the result hal file. But I now get a more accurate guide tree, so is there any way to change the guide tree in the existing hal file without starting the calculation all over again?

Thank you
Yawen

**Comment by glennhickey** [comment]
Your options for updating alignments are limited to what's here:
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/updating-alignments.md

This is something we're going to make simpler to run soon I hope, but in general there's no easy way to change the tree without some re-alignment.

**Comment by lningyawen** [comment]
Sorry for getting back to you late, I'm going to use cactus to calculate it again. 

Thank you!
