### ISSUE TITLE
replacing toil 5.4.0 with 5.5.0 in install of binary version

### ISSUE THREAD

**Issue by eta000** [ComparativeGenomicsToolkit/cactus#644]
Hi. I had to replace 5.4.0 with 5.5.0 in an install of the binary version of cactus for an install on a national machine in Norway. It does pass all tests. However, I would like to have your opinion on the reliability of results coming out of this install since we are serving the national academic community.

Regards

**Comment by glennhickey** [comment]
I think if it passes the tests, it should be fine.  Any incompatibility I could think of would cause a crash right away from something like a name change.  Can't imagine the results being affected.  The next Cactus release will use Toil 5.6.0 FWIW.
