### ISSUE TITLE
how to decode the sequence name from HAL directly

### ISSUE THREAD

**Issue by Secretloong** [ComparativeGenomicsToolkit/cactus#658]
Hello!

I want to extract the non-bias alignments from HAL results (no MAF, reference-bias). When I decode the raw HAL results with HDF5 api, I could understand your binary decoding for sequences and the indexing for alignments. But I don't understand how to get the```SEQNAME_ARRAY```. could you share your method which convert the sequence name (like chromosome_1) to ```SEQNAME_ARRAY```, or just give a clue to your raw code in github?

Many Thanks!

**Comment by glennhickey** [comment]
You need to use the [C++ HAL API](https://github.com/ComparativeGenomicsToolkit/hal/tree/master/api) if you want to parse HAL files yourself.  The sequence code mostly lives in this part: [hd5Sequence.cpp](https://github.com/ComparativeGenomicsToolkit/hal/blob/master/api/hdf5_impl/hdf5Sequence.cpp)

Bypassing the HAL API and using the HDF5 API is possible in theory, but would amount to tons of work (the equivalent of rewriting most of the HAL API).

**Comment by Secretloong** [comment]
Thanks! But I'm not familiar with C++. 

I would try to decode HAL results by Python. And I found it's hard to extract the sequence name form HAL by Python or HDF5 tools. But the order of the coding of sequence names in HAL is the same as the input genome  FASTA files. So I will try to decode the alignment index along the scaffolds/chromosomes in input files.

I am also interested in your pan-genome strategy for Cactus results. But for hundreds of genomes, it's hard to run, so slowly.

**Comment by diekhans** [comment]
Hi Qi,

They HAL library provides a lot of support for accessing the
data structures.  I suspect it would be less work to learn some
C/C++ than to reproduce the functionality in Python.  It will also
be quite slow in python.

**Comment by Secretloong** [comment]
Thanks Mark, you're right. I'll try to learn some C++ code based on HAL/Cactus.



> Hi Qi, They HAL library provides a lot of support for accessing the data structures. I suspect it would be less work to learn some C/C++ than to reproduce the functionality in Python. It will also be quite slow in python.
