### ISSUE TITLE
Alignment failing due to preprocessing error

### ISSUE THREAD

**Issue by ndtvchris** [ComparativeGenomicsToolkit/cactus#662]
I've been trying to use Cactus to align some genomes for a small school project, but I've run into an issue I'm not sure how to solve. When trying to align, even when using the example listed in the README, I keep seeing an error stating that the preprocessing step is failing, and it fails the entire process. Attached are some of the error messages I've received. I'd greatly appreciate any guidance!

Sincerely,
Christopher Nguyen
[cactus error message.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/8045240/cactus.error.message.txt)

**Comment by glennhickey** [comment]
The precompiled binaries only work on Linux. For Mac, you need to [build from source](https://github.com/ComparativeGenomicsToolkit/cactus#build-from-source)

**Comment by glennhickey** [comment]
Compatibility summary:
Release binaries: X86 Linux only
Docker images: X86 Linux or X86 Mac (I think)
Build from source: X86 Linux or X86 Mac

ARM is currently not supported at all, for either for Linux or Mac.  ARM support will be added soon but I don't have an exact timeline as it's stuck in a branch with a bunch of other changes.
