### ISSUE TITLE
Insufficient resources using Docker image

### ISSUE THREAD

**Issue by ndtvchris** [ComparativeGenomicsToolkit/cactus#664]
Hello,

When I try to use Cactus via the Docker image I get an error telling me there's not enough storage for the process. Would I have to mount another volume in order to use the --workDir flag? Or is there another work-around to this? Attached is a picture.

I apologize for asking such questions. I am very new to this whole process, and trying to use this for what I thought was a simple school project. 

Sincerely,
Chris
<img width="566" alt="Screen Shot 2022-02-15 at 8 45 53 AM" src="https://user-images.githubusercontent.com/96163621/154117862-4447a3d4-48bc-4c41-a734-9839fcba7544.png">

**Comment by glennhickey** [comment]
Cactus wants about 4G RAM for even tiny tests.  [It doesn't actually need it](https://github.com/ComparativeGenomicsToolkit/cactus#system-requirements), but it's just the way some of the minimum job requirements are set up.  

This can be worked around by hacking the code a bit, but you're best to find a system with more memory.
