### ISSUE TITLE
SLURM `sacct` calls swamping slurms job database

### ISSUE THREAD

**Issue by lparsons** [ComparativeGenomicsToolkit/cactus#67]
I'm running into an issue trying to run Cactus on our SLURM cluster. The cactus process running on the submit node seems to start about one thousand (1000) `sacct` processes, which crashed our SLURM db. I'm not sure if this part of a toil configuration or specific to how cactus is using toil. There appear to be many `sacct` processes for the same job number, which seems odd.

I seem to be able to reduce this by setting `--parasolMaxBatches`. However, I still seem to run into the issue.

**Comment by lparsons** [comment]
I was able to resolve this issue. It was due to the fact that on our cluster, `sacct` calls that included the `-S` or `--start-time` parameter were extremely slow. I'm not sure if this is a bug in our version of slurm (16.08) or due to some other reason. However, I patched the [arguments used in toil](https://github.com/DataBiosphere/toil/blob/6ead236325e5a63749d724675d6d4791ba16c476/src/toil/batchSystems/slurm.py#L95-L100) to remove the `-S` and was able to resume running cactus.
```python
            args = ['sacct',
                    '-n', # no header
                    '-j', str(slurmJobID), # job
                    '--format', 'State,ExitCode', # specify output columns
                    '-P', # separate columns with pipes
                    '-S', '1970-01-01'] # override start time limit
```

**Comment by amizeranschi** [comment]
Thanks for posting this. I noticed that the SGE equivalent (`qacct -j <jobID>`) was taking a long time as well, on the cluster that I'm using. As Cactus used this to [retrieve the job resource usage and exit code](https://github.com/DataBiosphere/toil/blob/6ead236325e5a63749d724675d6d4791ba16c476/src/toil/batchSystems/gridengine.py#L77), it was likely slowing down Toil jobs overall. 

After the admin [rotated the SGE job logs](http://blog.frank-mich.com/sgeogs-clean-your-logs/), this has been fixed.
