### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by Aannaw** [ComparativeGenomicsToolkit/cactus#676]
Hello
I am using cactus to construct the  pangenome  graph of two genomes.  I intended to refer to the [https://github.com/ComparativeGenomicsToolkit/cactus/blob/mg-base/doc/pangenome.md#evolver-primates-preprocessing-and-naming](url)  to run. But many  commands and options is not found, like cactus-minigraph command and --reference parameter.  I am using cactus v2.0.4. So finally I apply the command ` "cactus ./jobstore Ma6-Mp5.txt  Ma6-Mp5.hal --maxCores 20 --maxMemory 60G" 
` according to [README.md](https://github.com/ComparativeGenomicsToolkit/cactus/tree/mg-base#readme). I can not set the reference parameters on the command . I only set that in the txt file:
Mp5.0 1.Mp5.softmask.fa
Ma6     1.Ma6.softmask.fa
Is this appropriate? 
Thanks!

**Comment by glennhickey** [comment]
Hi,  that README indeed uses Cactus commands that have not yet been released.  I only shared it in another issue as a reference for the naming scheme, but warned (I think) that not all commands will work in the current release.

**Comment by Aannaw** [comment]
Thanks for your prompt reply.
I am also through another issue.  It is appropriate with determining the reference in the seqfile.txt according to the convention of SAMPLE.HAPLOTYPE but not --reference parameter? Because next I would use vg to align and then call variants. Will it influence the following steps?
Thanks!

**Comment by glennhickey** [comment]
The reference should
* be just `SAMPLE` in the seqfile
* be flagged with the `--reference` option for all commands (that have a reference option). 

All other genomes should be `SAMPLE.HAPLOTYPE` in the seqfile.

**Comment by Aannaw** [comment]
Hi
But I can not use the --reference option. I try it with `cactus-v2.0.5` and `cactus-v2.0.4`. They both is "cactus: error: unrecognized arguments: --reference"
My command is cactus` ./jobstore Ma6-Mp5.txt  Ma6-Mp5.hal --reference` according to ReadMe.
![cactus](https://user-images.githubusercontent.com/82857778/156088923-cb2c7373-da56-4434-a9c9-f4efd7652fca.png)

**Comment by glennhickey** [comment]
Please refer to the documentation https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md
