### ISSUE TITLE
cactus-prepare: error: unrecognized arguments: --seqFileOnly

### ISSUE THREAD

**Issue by zhanghaoipp** [ComparativeGenomicsToolkit/cactus#687]
I try the Minigraph-Cactus Pangenome Pipeline in docker (quay.io/comparative-genomics-toolkit/cactus:v2.0.5) according to the page https://github.com/ComparativeGenomicsToolkit/cactus/blob/mg-base/doc/pangenome.md
 
1. $ docker run -v $(pwd):/data --rm  -it quay.io/comparative-genomics-toolkit/cactus:v2.0.5 bash
2. $ tail -n +2 examples/evolverPrimates.txt | sed -e 's/^simHuman/simHuman.0/g' -e 's/^simGorilla/simGorilla.0/g' -e 's/^simOrang/simOrang.0/g' > evolverPrimates.pg.txt
**3. $ cactus-prepare ./evolverPrimates.pg.txt --outDir primates-pg --seqFileOnly**
**It showed "cactus-prepare: error: unrecognized arguments: --seqFileOnly"**

There is not this parameter in docker version?

**Comment by glennhickey** [comment]
That's true, that parameter won't be available until the next release!
