### ISSUE TITLE
Error running cactus-align with a not-so-old CPU

### ISSUE THREAD

**Issue by lhui2010** [ComparativeGenomicsToolkit/cactus#688]
Hello, 

I'm meeting a similar problem with #561 when running cactus on example data.

I followed the guideline in BIN-INSTALL.md and met no problem. And the test runs no problem with on test server with Intel(R) Xeon(R) CPU E5-2620 v3 (Year 2014). But it halts with the same command on our computing server equipped with AMD EPYC 7H12.

The command I used

```
cactus jobStore evolverMammals.txt evolverMammals.hal --root mr
```

The error I received

```
        RuntimeError: Command ['cactus_consolidated', '--sequences', 'simCow_chr6 /tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmp6uyci3df.tmp simDog_chr6 /tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmp8_vk04oj.tmp simHuman_chr6
/tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmp08fsca8t.tmp simMouse_chr6 /tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmpkt4jskbd.tmp simRat_chr6 /tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmphdbqz9g6.tmp', '--speciesTree',
 '((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;', '--logLevel', 'INFO', '--alignments', '/tmp/c1594ed5c61a53b0992b43720300e0a
2/4f55/97d4/tmpbokuz8w1.tmp', '--params', '/tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmpzk87xf7v.tmp', '--outputFile', '/tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmpcc0trhvh.tmp', '--outputHalFastaFile', '/tmp/c1594ed5c61a53
b0992b43720300e0a2/4f55/97d4/tmpt0yoz7wh.tmp', '--outputReferenceFile', '/tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmpvl12y96p.tmp', '--outgroupEvents', 'simHuman_chr6 simDog_chr6 simCow_chr6', '--referenceEvent', 'mr', '--seconda
ryAlignments', '/tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmp7ew99n9w.tmp', '--threads', '256'] signaled SIGSEGV: stdout=, stderr=Params file: /tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmpzk87xf7v.tmp
```

I checked extensions of AMD EPYC 7H12 and it supports AVX2 and I don't think it's too old as it was first released in [2019](https://www.servethehome.com/amd-epyc-7h12-review-the-supercomputer-epyc/#:~:text=In%202020%2C%20perhaps%20the%20best,were%20very%20hard%20to%20get.). Is there something else went wrong? Or just because AMD CPU was not supported by cactus? 

I understand switching to the legacy version is an option, but we are interested in pan-genome pipeline and are still trying to manage it to work. Any help would be appreciated.

Attached please find the full log file.

Thanks
Hui

[cactus.err.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/8322475/cactus.err.txt)

**Comment by glennhickey** [comment]
Hi, judging from your log, it's crashing long before any SIMD instructions are used, so I don't think it's an AVX2 issue (also that type of incompatibility causes SIGILL and not SIGSEGV). It's crashing when it's loading the XML parameters (`'--params', '/tmp/c1594ed5c61a53b0992b43720300e0a2/4f55/97d4/tmpzk87xf7v.tmp'`).  All I can think of is that somehow the libxml2 it's built with is not compatible with your system, despite `ldd` saying it's completely static.  I'm not sure there's much I can do without being able to reproduce, I'm afraid.  Your best bet would be to try docker or singularity with the docker image or to build it yourself.

**Comment by lhui2010** [comment]
Hi,
Thanks for the reply! It's great to know that it's not the AVX2 issue. I'll have a check on libxml2 and recommended method. Many thanks!
Hui
