### ISSUE TITLE
Fresh virtualenv install, command cactus not found

### ISSUE THREAD

**Issue by rsharris** [ComparativeGenomicsToolkit/cactus#699]
I'm following the instructions at
    https://github.com/ComparativeGenomicsToolkit/cactus/blob/2dc700813f27536ca4ff1bef795ef8b1ab356e78/BIN-INSTALL.md
and have (apparently) succeeded with creating and initializing the virtual environment.

But when I get to the testing section, it turns out cactus is not in my PATH. In fact, I don't find a file named cactus (just "cactus").

There are two directories in my PATH (when the virtual environment is active):
    /some_path/cactus/cactus-bin-v2.0.5/bin
    /some_path/cactus/cactus-bin-v2.0.5/cactus.20220404.env/bin
(cactus.20220404.env is the name of my virtual environment)

Are there additional steps I need to take to install cactus itself?

Thanks,
Bob H

**Comment by glennhickey** [comment]
Looks like you didn't run the last command from the instructions:
```
# to be run from same path as prev commands: /some_path/cactus/cactus-bin-v2.0.5/
python3 -m pip install -U .
```

**Comment by rsharris** [comment]
D'oh!   I've now run that command and now cactus exists in the cactus.20220404.env/bin directory.

Thanks!

**Comment by jmbraverman** [comment]
I had the same issue.  But I double-checked and I had ran that command:

dell:~/Cactus/cactus-bin-v2.0.5$ python3 -m pip install -U .
Processing /home/jbraverm/Cactus/cactus-bin-v2.0.5
  Preparing metadata (setup.py) ... done
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: networkx<3,>=2 in ./cactus_env/lib/python3.8/site-packages (from Cactus==1.0) (2.8)
Collecting pytest
  Downloading pytest-7.1.2-py3-none-any.whl (297 kB)
     |████████████████████████████████| 297 kB 17.0 MB/s            
Collecting cigar
  Downloading cigar-0.1.3.tar.gz (7.0 kB)
  Preparing metadata (setup.py) ... done
Collecting biopython
  Downloading biopython-1.79-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 74.2 MB/s            
Collecting numpy
  Downloading numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 74.7 MB/s            
Collecting tomli>=1.0.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Requirement already satisfied: attrs>=19.2.0 in ./cactus_env/lib/python3.8/site-packages (from pytest->Cactus==1.0) (21.4.0)
Collecting py>=1.8.2
  Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 7.9 MB/s             
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: packaging in ./cactus_env/lib/python3.8/site-packages (from pytest->Cactus==1.0) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./cactus_env/lib/python3.8/site-packages (from packaging->pytest->Cactus==1.0) (3.0.9)
Building wheels for collected packages: Cactus, cigar
  Building wheel for Cactus (setup.py) ... done
  Created wheel for Cactus: filename=Cactus-1.0-py3-none-any.whl size=220532 sha256=7d848cacbb2998005201a9f6231536f8ae0f2dede682d1e26fad391f1a1f8700
  Stored in directory: /home/jbraverm/.cache/pip/wheels/d6/fa/6b/9811a1edbad1a00558cee72925255577d47ae421d1239cbe9c
  Building wheel for cigar (setup.py) ... done
  Created wheel for cigar: filename=cigar-0.1.3-py3-none-any.whl size=4018 sha256=7e1d028b6b20ed1c2e42e59dbea7db2417a0966f708f789f1ee45b6d0e7560ce
  Stored in directory: /home/jbraverm/.cache/pip/wheels/54/bc/ad/c9cbc7fbc6c50c511c42a49427e8920996ca35e4ed9c757b2f
Successfully built Cactus cigar
Installing collected packages: tomli, py, pluggy, numpy, iniconfig, pytest, decorator, cigar, biopython, Cactus
Successfully installed Cactus-1.0 biopython-1.79 cigar-0.1.3 decorator-5.1.1 iniconfig-1.1.1 numpy-1.22.3 pluggy-1.0.0 py-1.11.0 pytest-7.1.2 tomli-2.0.1
WARNING: You are using pip version 21.3.1; however, version 22.1 is available.
You should consider upgrading via the '/home/jbraverm/Cactus/cactus-bin-v2.0.5/cactus_env/bin/python3 -m pip install --upgrade pip' command.
