### ISSUE TITLE
Fresh virtualenv install, Cactus ... can't find the Cactus binaries

### ISSUE THREAD

**Issue by rsharris** [ComparativeGenomicsToolkit/cactus#700]
I installed the pre-compiled binaries under a virtualenv, following the instructions at
https://github.com/ComparativeGenomicsToolkit/cactus/blob/2dc700813f27536ca4ff1bef795ef8b1ab356e78/BIN-INSTALL.md

I'm now attempting to run cactus on a very small problem with simulated genomes (similar to the recommended test, but with six 50Kbp genomes). My command is

```
cd some_test_dir  
source /some_path/cactus/cactus-bin-v2.0.5/cactus.20220404.env/bin/activate
cactus jobstore seqFile.20220405C.txt seqFile.20220405C.hal 
```

And I get this error:
`RuntimeError: The `docker` executable wasn't found on the system. Please install Docker if possible, or use --binariesMode local and add cactus's bin directory to your PATH.
`

Installing docker on this system is a non-starter (the IT guys consider it a security risk).

If I add "--binariesMode local" to my command line, I get this error instead:
`RuntimeError: Cactus isn't using Docker, but it can't find the Cactus binaries. Please add Cactus's bin directory to your PATH (and run `make` in the Cactus directory if you haven't already).
`

I've confused (I guess) about what Cactus's bin directory is. My PATH contains
```
/some_path/cactus/cactus-bin-v2.0.5/bin
/some_path/cactus/cactus-bin-v2.0.5/cactus.20220404.env/bin
```
and "which cactus" shows
`/some_path/cactus/cactus-bin-v2.0.5/cactus.20220404.env/bin/cactus`

And of course, if cactus weren't in my PATH the command `cactus jobstore ...` wouldn't have gotten off the ground.

**Comment by glennhickey** [comment]
You definitely don't need docker to run the binary release.  If I go ahead and run the instructions from `~/hickey/temp`:
```
wget https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v2.0.5/cactus-bin-v2.0.5.tar.gz 
tar zxf cactus-bin-v2.0.5.tar.gz
cd cactus-bin-v2.0.5/
virtualenv -p python3.8 cactus_env
echo 'export PATH=$(pwd)/bin:$PATH' >> cactus_env/bin/activate
echo 'export PYTHONPATH=$(pwd)/lib:$PYTHONPATH' >> cactus_env/bin/activate
source cactus_env/bin/activate
python3 -m pip install -U setuptools pip==21.3.1
python3 -m pip install -U -r ./toil-requirement.txt
python3 -m pip install -U .
```
I see that I have the `cactus` script installed in the virtualenv
```
which cactus
/home/hickey/temp/cactus-bin-v2.0.5/cactus_env/bin/cactus
```
and the binaries are where they were extracted from the release, ex:
```
which cactus_consolidated
/home/hickey/temp/cactus-bin-v2.0.5/bin/cactus_consolidated
```
this works fine
```
cactus ./js ./examples/evolverMammals.txt evolver.hal --logError
which halStats
/home/hickey/temp/cactus-bin-v2.0.5/bin/halStats
halStats evolver.hal --genomes
Anc0 Anc1 simHuman_chr6 mr simMouse_chr6 simRat_chr6 Anc2 simCow_chr6 simDog_chr6

```
