### ISSUE TITLE
Tree branch lengths

### ISSUE THREAD

**Issue by abmudd** [ComparativeGenomicsToolkit/cactus#71]
Hi @benedictpaten and @joelarmstrong,

How does cactus use the input tree branch lengths? How exact do the branch lengths need to be? I haven't found any explanation of this in your paper or other materials. Thank you.

**Comment by jasonsydes** [comment]
Hi there @abmudd.  Just seeing this now.  Have you seen the discussion over here (on the older/deprecated version of cactus):

https://github.com/glennhickey/progressiveCactus/issues/109

From what I recall, setting all branch lengths to 1 (or not setting them at all) is the safest route to take.  Hopefully I'm not misquoting there.

**Comment by abmudd** [comment]
Hi @jasonsydes,

Thanks for the reply. I had not seen that discussion. That all makes sense, though I do support the [comment](https://github.com/glennhickey/progressiveCactus/issues/109#issuecomment-396091790) from @iminkin about adding this info to the documentation.
