### ISSUE TITLE
Stuck on 32 MB "Job" loop, repeatedly launched 

### ISSUE THREAD

**Issue by jasonsydes** [ComparativeGenomicsToolkit/cactus#72]
Hello cactus community!

I've recently been able to get cactus up and running on our SLURM cluster.  I've run through the evolverMammals.txt test dataset to success several times in various arrangements (e.g. local binaries, singularity binaries, batchSystem local, and batchSystem slurm).

There's a frustrating hiccup that keeps happening when running under SLURM.  A certain job (titled just "Job") is repeatedly launched, supposedly finished successfully, but apparently not, and gets relaunched.  This repeats over and and over, until eventually toil catches it, ups its memory, and then the job really finishes successfully, and cactus/toil moves onto the next job.

I'll attache the full log below, but here's a snippet of where the problem begins (it's job **job2g243T** below):
```
Job ended successfully: 'TrimAndRecurseOnOutgroups' 8/o/jobvo18Gf
Issued job 'BlastFirstOutgroup' P/J/jobyeSZCQ with job batch system ID: 143 and cores: 13, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'BlastFirstOutgroup' P/J/jobyeSZCQ
Issued job 'CollateBlasts' K/v/jobXDmPSY with job batch system ID: 144 and cores: 13, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'CollateBlasts' K/v/jobXDmPSY
Issued job 'CollateBlasts2' v/v/jobsooWQ2 with job batch system ID: 145 and cores: 13, disk: 100.0 M, and memory: 2.0 G
Job ended successfully: 'CollateBlasts2' v/v/jobsooWQ2
Issued job 'CollateBlasts' K/v/jobXDmPSY with job batch system ID: 146 and cores: 13, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'CollateBlasts' K/v/jobXDmPSY
Issued job 'BlastIngroupsAndOutgroups' t/m/jobxWQwpZ with job batch system ID: 147 and cores: 13, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'BlastIngroupsAndOutgroups' t/m/jobxWQwpZ
Issued job 'Job' S/s/job2g243T with job batch system ID: 148 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 149 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 150 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 151 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 152 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 153 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 154 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
Issued job 'Job' S/s/job2g243T with job batch system ID: 155 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' S/s/job2g243T
```

Looking at SLURM's sacct, I'm pretty sure that it's being killed by SLURM because it's consuming too much memory:

```
     User        JobID    JobName  Partition      State  Timelimit               Start    Elapsed
--------- ------------ ---------- ---------- ---------- ---------- ------------------- ----------
    sydes 3604291      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:13   00:00:02
    sydes 3604292      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:16   00:00:01
    sydes 3604293      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:19   00:00:01
    sydes 3604294      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:20   00:00:02
    sydes 3604295      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:23   00:00:02
    sydes 3604296      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:26   00:00:02
    sydes 3604297      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:29   00:00:02
    sydes 3604298      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:32   00:00:02
    sydes 3604299      toil_job_+        jhp OUT_OF_ME+ 30-00:00:+ 2019-04-05T11:33:34   00:00:04
``` 
Note that the job that keeps getting relaunched is only being allocated 32 MB of memory.

I'm new to this cactus installation using Toil, and I'm not familiar with how to link the output of the log file with the slurm logs, or even how to tell what "Job" is or where to find it.  I also don't know how to increase the amount of memory allocated to that job.  (I haven't even figured out how to turn on time stamps in the cactus log / output.)

Ah, I do have several slurm.logs (174 of them) that do show it being killed due to memory.  Here's an example of one.  Note that the job ID (job2g243T) matches the one above.
```
$ cat slurm-3601576.out
/cm/local/apps/slurm/var/spool/job3601576/slurm_script: line 4: 54101 Killed                  /home/sydes/bin/miniconda2/envs/cactus_20190401_py2_env/bin/_toil_worker Job file:/gpfs/projects/postlethwait/sydes/cactus/new_cactus_20190401/runs/20190405/jobStore S/s/job2g243T
slurmstepd: error: Detected 1 oom-kill event(s) in step 3601576.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
Is there someway to increase the default memory for this job?

It's not the end of the world, because as you can see, the job and cactus run eventually does complete.  But it would be nice to have this addressed.

(By the way, not sure if this is relevant, but this happens whether or not I turn on the  --disableCaching flag.)

I'm attaching the full cactus log below.  I was also able to grab a copy of the job file, so in case that's useful, I'm attaching it here as well.

Thank you for your time, and thank you for cactus!
Jason

[cactus.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/3049233/cactus.log)
[THE_32MB_JOB_THAT_KEEPS_REPEATEDLY_FAILING.job.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3049259/THE_32MB_JOB_THAT_KEEPS_REPEATEDLY_FAILING.job.txt)

**Comment by jasonsydes** [comment]
Ah, my apologies, I just realized the cactus.log file that I gave was from a run in which I stopped the run (with CTRL-C) and restarted it a handful of times (in an attempt to get cactus to "move on").

I'm attaching another cactus.log file below in which I did not restart the job at all (cactus/toil eventually figured it out and moved on on its own).  

Here's the relevant section from that log where it figured it out:
```
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 308 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 309 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 310 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 311 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 312 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 313 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 314 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 315 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 316 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 317 and cores: 0, disk: 1.0 M, and memory: 32.0 M
Job failed with exit value 135: 'Job' d/s/jobQ0PKIE
No log file is present, despite job failing: 'Job' d/s/jobQ0PKIE
Due to failure we are reducing the remaining retry count of job 'Job' d/s/jobQ0PKIE with ID d/s/jobQ0PKIE to 5
We have increased the default memory of the failed job 'Job' d/s/jobQ0PKIE to 2147483648 bytes
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 318 and cores: 0, disk: 1.0 M, and memory: 2.0 G
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'mappingQualityRescoring' z/e/jobZTuM4S with job batch system ID: 319 and cores: 13, disk: 2.0 G, and memory: 2.0 G
Got message from job at time 04-05-2019 10:23:24: Input cigar file has 7362 lines
Got message from job at time 04-05-2019 10:23:24: Filtered, non-overlapping primary cigar file has 11273 lines
Got message from job at time 04-05-2019 10:23:24: Filtered, non-overlapping secondary cigar file has 31711 lines
Job ended successfully: 'mappingQualityRescoring' z/e/jobZTuM4S
Issued job 'Job' d/s/jobQ0PKIE with job batch system ID: 320 and cores: 0, disk: 1.0 M, and memory: 2.0 G
Job ended successfully: 'Job' d/s/jobQ0PKIE
Issued job 'EncapsulatedJob' x/c/jobsFWphJ with job batch system ID: 321 and cores: 13, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'EncapsulatedJob' x/c/jobsFWphJ
Issued job 'CactusSetupCheckpoint' n/R/job9DUyRL with job batch system ID: 322 and cores: 1, disk: 2.0 G, and memory: 3.3 G
Job ended successfully: 'CactusSetupCheckpoint' n/R/job9DUyRL
Issued job 'StartPrimaryDB' z/y/jobghjHP7 with job batch system ID: 323 and cores: 1, disk: 2.0 G, and memory: 3.3 G
Job ended successfully: 'StartPrimaryDB' z/y/jobghjHP7
Issued job 'KtServerService' S/h/jobS_aWyj with job batch system ID: 324 and cores: 0, disk: 2.0 G, and memory: 2.3 G
Issued job 'CactusSetupPhase' h/m/jobjSYXJA with job batch system ID: 325 and cores: 1, disk: 2.0 G, and memory: 3.3 G
Job ended successfully: 'CactusSetupPhase' h/m/jobjSYXJA
```
Here's the full log file:
[cactus.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/3049300/cactus.log)

**Comment by lassancejm** [comment]
I am facing exactly the same error with Slurm + toil 3.18/3.19. The 32 Mb must be hard-coded somewhere, as this is not the default value for our queues. In my case, this was never caught and the jobs eventually timed out.

**Comment by jasonsydes** [comment]
Good to know I'm not the only one @lassancejm.  Since I've posted I've now seen some of my runs behave like the ones you describe, and simply (eventually) die.  It may be the majority (at least on the demo dataset), but I haven't quantified, so grain of salt.

I looked for the 32 Mb hard coding, but wasn't able to easily find it with grep and 30 minutes of time.

There are suggestions elsewhere (well, at least one suggestion, by @adamnovak, possibly more IIRC) on how to increase the default memory for a particular job, but his suggestion is for a BLAST job, not our "Job" job, so it very likely doesn't apply here: https://github.com/ComparativeGenomicsToolkit/cactus/issues/63#issuecomment-474961046

Hopefully this is just a super tiny quick tweak to that job "Job" (up to 64 or 128 Mb for that job "Job"??) and this Issue can be closed??

**Comment by lassancejm** [comment]
So, I searched through the code (also the code for toil) and I could not find that either, so I am not sure where it is coming from and what it is even. 

Fixing the  memory for BLAST, as you write, does not fix this. What puzzles me is that 32Mb is not even the default memory for our partitions. 

My solution, which is not an elegant one really, has been to change the memory requirement for that job manually (basically, editing `d/s/jobQ0PKIE/job` in your example above). This requires paying close attention to cactus and exiting it manually when it is in that weird loop. 

I will post if I find anything.

**Comment by adamnovak** [comment]
Here's the deserialized version of the offending job:

```
>>> import pickle
>>> pickle.load(open('pickle.txt'))
JobGraph( **{'predecessorNumber': 1, 'startJobStoreID': None, '_preemptable': False, 'errorJobStoreID': None, 'remainingRetryCount': 6, 'filesToDelete': [], 'checkpointFilesToDelete': None, 'checkpoint': None, '_cores': 0.1, 'logJobStoreFileID': None, 'jobStoreID': 'J/O/jobiOWG0f', 'unitName': None, 'chainedJobs': None, 'services': [], 'predecessorsFinished': set([]), 'stack': [[JobNode( **{'jobStoreID': '5/u/jobajzN3I', '_config': None, 'displayName': 'JobGraph', 'predecessorNumber': 1, 'unitName': None, '_preemptable': True, 'jobName': 'mappingQualityRescoring', '_disk': 2147483648, '_cores': 13.0, 'command': None, '_memory': 2147483648} )], []], '_config': None, 'displayName': 'JobGraph', 'jobName': 'Job', '_disk': 1048576, 'command': '_toil H/V/jobQQTt37/g/tmp0MyCGZ-_serialiseJob-stream /home/sydes/bin/miniconda2/envs/cactus_20190401_py2_env/lib/python2.7/site-packages toil.job True', '_memory': 33554432, 'terminateJobStoreID': None} )
```

So it looks like the job has something to do with `mappingQualityRescoring` in Cactus.

The relevant Cactus code is here:

https://github.com/ComparativeGenomicsToolkit/cactus/blob/466b5bb8727576d2f58c82222e71f1f2da65404e/src/cactus/pipeline/cactus_workflow.py#L566-L573

The `mappingQualityRescoring` job doesn't launch any child jobs; I think we're looking at the job created by `encapsulate`.

And here's the 32 MB memory requirement, hardcoded into Toil!

https://github.com/DataBiosphere/toil/blob/19c1ae969487e20eb28ad1cf36976f03a701aa0c/src/toil/job.py#L1574

So this looks like a Toil bug, along the lines of "32MB is too small of a memory requirement for encapsulating jobs".

**Comment by benedictpaten** [comment]
Hmm. @joelarmstrong This looks related to our recent changes to the mapping quality stuff. Thoughts?

**Comment by lassancejm** [comment]
Thanks for tracking this down @adamnovak. It seems my search within toil was partial only.

**Comment by jasonsydes** [comment]
Yes, thank you @adamnovak!  This is great!  Also, now I know that the jobs are pickled, and that I can unpickle them to read them! 

Thank you all for all the work you do on Cactus and Toil and related projects!!
