### ISSUE TITLE
problems when building cactus from source

### ISSUE THREAD

**Issue by Overcraft90** [ComparativeGenomicsToolkit/cactus#735]
Hi there,

I'm facing this error

> Defaulting to user installation because normal site-packages is not writeable
> Collecting toil[all]==5.6.0
>   Using cached toil-5.6.0-py3-none-any.whl (592 kB)
> Collecting py-tes<1,>=0.4.2
>   Using cached py-tes-0.4.2.tar.gz (6.3 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: requests<3,>=2 in /home/mat/.local/lib/python3.10/site-packages (from toil[all]==5.6.0->-r ./toil-requirement.txt (line 1)) (2.27.1)
> Collecting docker<6,>=3.7.2
>   Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)
> Collecting dill<0.4,>=0.3.2
>   Using cached dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
> Collecting enlighten<2,>=1.5.2
>   Using cached enlighten-1.10.2-py2.py3-none-any.whl (53 kB)
> Requirement already satisfied: pytz>=2012 in /usr/lib/python3/dist-packages (from toil[all]==5.6.0->-r ./toil-requirement.txt (line 1)) (2022.1)
> Requirement already satisfied: psutil<6,>=3.0.1 in /home/mat/.local/lib/python3.10/site-packages (from toil[all]==5.6.0->-r ./toil-requirement.txt (line 1)) (5.9.0)
> Collecting addict<2.5,>=2.2.1
>   Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
> Requirement already satisfied: python-dateutil in /home/mat/.local/lib/python3.10/site-packages (from toil[all]==5.6.0->-r ./toil-requirement.txt (line 1)) (2.8.2)
> Requirement already satisfied: pynacl<2,>=1.4.0 in /usr/lib/python3/dist-packages (from toil[all]==5.6.0->-r ./toil-requirement.txt (line 1)) (1.5.0)
> Collecting boto<3,>=2.48.0
>   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 13.1 MB/s eta 0:00:00
> Collecting celery<6,>=5.1.0
>   Downloading celery-5.2.7-py3-none-any.whl (405 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.6/405.6 kB 43.0 MB/s eta 0:00:00
> Collecting boto3<2,>=1.17
>   Using cached boto3-1.24.7-py3-none-any.whl (132 kB)
> Collecting cwltool==3.1.20211107152837
>   Downloading cwltool-3.1.20211107152837-py3-none-any.whl (1.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 75.0 MB/s eta 0:00:00
> Collecting connexion[swagger-ui]<3,>=2.5.1
>   Downloading connexion-2.13.1-py2.py3-none-any.whl (95 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 11.0 MB/s eta 0:00:00
> Collecting ruamel.yaml.clib>=0.2.6
>   Using cached ruamel.yaml.clib-0.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (519 kB)
> Collecting kubernetes<22,>=12.0.1
>   Downloading kubernetes-21.7.0-py2.py3-none-any.whl (1.8 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 72.9 MB/s eta 0:00:00
> Collecting apache-libcloud<3,>=2.2.1
>   Downloading apache_libcloud-2.8.3-py2.py3-none-any.whl (3.4 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 57.8 MB/s eta 0:00:00
> Collecting wdlparse==0.1.0
>   Downloading wdlparse-0.1.0-py3-none-any.whl (106 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.7/106.7 kB 8.7 MB/s eta 0:00:00
> Collecting flask-cors==3.0.10
>   Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
> Requirement already satisfied: idna>=2 in /usr/lib/python3/dist-packages (from toil[all]==5.6.0->-r ./toil-requirement.txt (line 1)) (3.3)
> Collecting galaxy-tool-util
>   Using cached galaxy_tool_util-21.9.2-py2.py3-none-any.whl (328 kB)
> Collecting boto3-stubs[s3]<2,>=1.17
>   Downloading boto3_stubs-1.24.7-py3-none-any.whl (46 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 22.2 MB/s eta 0:00:00
> Collecting gunicorn==20.1.0
>   Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
> Collecting ruamel.yaml==0.17.16
>   Downloading ruamel.yaml-0.17.16-py3-none-any.whl (109 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.0/109.0 kB 5.3 MB/s eta 0:00:00
> ERROR: Ignored the following versions that require a different python version: 3.1.1.post1 Requires-Python >=2.6, <3; 3.2.0 Requires-Python >=2.6, <3; 3.3.0 Requires-Python >=2.6, <3
> ERROR: Could not find a version that satisfies the requirement futures<4,>=3.1.1; extra == "all" (from toil[all]) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
> ERROR: No matching distribution found for futures<4,>=3.1.1; extra == "all"

when I try and run the following command `python3 -m pip install -U -r ./toil-requirement.txt`. Is this normal? The command seems to correctly install some packages, but then there is an issue, or maybe it already installed everything was needed? Let me know.
Thanks in advance!

For your information I'm working in Ubuntu 22.04 "Jammy Jellyfish" with native _**Phyton 3.10**_.

**Comment by glennhickey** [comment]
Are you following the [instructions](https://github.com/ComparativeGenomicsToolkit/cactus#build-from-source)?  Most importantly, did you run:
```
python3 -m pip install -U setuptools pip==21.3.1
```

**Comment by Overcraft90** [comment]
Hi @glennhickey,

Sorry I apologise. I did everything correctly up to that point _e.g._ creating the environment, activating it etc., but then I thought it could have been fine to go for the newest version of pip, so I installed the `22.1.2 version`.

After going back to `version 21.3.1` the errors disappeared. However, while building the make file, and just before the end I got this output
![Screenshot from 2022-06-13 19-01-48](https://user-images.githubusercontent.com/98895614/173406756-68564277-57a3-4b2f-9a02-25521106c177.png)
It says "All warnings being treated as errors", then it lists some issues I guess. Is this something I can disregard, or is it related to some missing dependencies?

By contrast, the following step of installing pangenome-specific binaries (which is the one I'm interested in) went on smoothly. Let me know, thanks!

**Comment by Overcraft90** [comment]
Thanks again, I had a look at the version of _**lastz**_ and I updated it although I think it was already the latest version. Anyway, `cactus` seems working just fine despite this message. I can see the help menu and so on, I think we can close this issue.

**Comment by glennhickey** [comment]
This is now fixed in the master branch (via #736).
