### ISSUE TITLE
Jobs being repeated twice (both successful)

### ISSUE THREAD

**Issue by jasonsydes** [ComparativeGenomicsToolkit/cactus#74]
Hi Cactus community!

I've been able to run cactus to success evolverMammals.txt demo, but I still haven't been able to get it to run successfully on our 4-species "test" alignment (zebrafish, gar, playfish, cavefish).  I'll submit an Issue on that soon-ish.

In the process of examining the failed runs just described, I've noticed that many (the majority apparently) of jobs are being run twice on our install.  At first I thought it was due to the species we were using, or slurm, but now I can see that it is happening even on the evolverMammals.txt species in singleMachine mode.

I can see that there are jobs being launched twice:
```
∴ grep Issued cactus.log | awk '{print $4}' | sort | uniq -c | sort -k1 -g | tail -3
      2 Z/q/jobyeVrB3
      2 Z/Y/jobMHQ_Am
      2 Z/z/jobSVOPzI
```
And running to completion successfully twice:
```
∴ grep 'Job ended successfully' cactus.log | awk '{print $5}' | sort | uniq -c | sort -k1 -g | tail -3
      2 Z/q/jobyeVrB3
      2 Z/Y/jobMHQ_Am
      2 Z/z/jobSVOPzI
```
Looking at the sample of 3 jobs described above, the jobs being relaunched are different (Job, BlastSequencesAllAgainstAll and CactusHalGeneratorRecursion):
```
∴ grep Z/q/jobyeVrB3 cactus.log
Issued job 'Job' Z/q/jobyeVrB3 with job batch system ID: 630 and cores: 0, disk: 100.0 M, and memory: 512.0 M
Job ended successfully: 'Job' Z/q/jobyeVrB3
Issued job 'Job' Z/q/jobyeVrB3 with job batch system ID: 632 and cores: 0, disk: 100.0 M, and memory: 512.0 M
Job ended successfully: 'Job' Z/q/jobyeVrB3

∴ grep Z/Y/jobMHQ_Am cactus.log
Issued job 'BlastSequencesAllAgainstAll' Z/Y/jobMHQ_Am with job batch system ID: 601 and cores: 1, disk: 100.0 M, and memory: 2.0 G
Job ended successfully: 'BlastSequencesAllAgainstAll' Z/Y/jobMHQ_Am
Issued job 'BlastSequencesAllAgainstAll' Z/Y/jobMHQ_Am with job batch system ID: 623 and cores: 1, disk: 100.0 M, and memory: 2.0 G
Job ended successfully: 'BlastSequencesAllAgainstAll' Z/Y/jobMHQ_Am

∴ grep Z/z/jobSVOPzI cactus.log
Issued job 'CactusHalGeneratorRecursion' Z/z/jobSVOPzI with job batch system ID: 966 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'CactusHalGeneratorRecursion' Z/z/jobSVOPzI
Issued job 'CactusHalGeneratorRecursion' Z/z/jobSVOPzI with job batch system ID: 983 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'CactusHalGeneratorRecursion' Z/z/jobSVOPzI
```
Looking at the overall count, I can see that 264 jobs were only issued once, while 368 jobs were issued twice:
```
∴ grep Issued cactus.log | awk '{print $4}' | sort | uniq -c | sort -k1 -g | awk '{print $1}' | sort | uniq -c | sort -k1 -g
    264 1
    368 2
```
All jobs reported success (whether issued once or twice):
```
∴ grep 'Job ended successfully' cactus.log | awk '{print $5}' | sort | uniq -c | sort -k1 -g | awk '{print $1}' | sort | uniq -c | sort -k1 -g
    264 1
    368 2
```
No jobs failed:
```
∴ grep -c -i fail cactus.log
0
```
This is probably different from #72, because following @adamnovak's lead, I increased the memory in these two lines in toil's job.py (and so I'm no longer seeing the same behavior from #72).
```
        # ORIGINAL: kwargs.update(dict(disk='1M', memory='32M', cores=0.1))
        kwargs.update(dict(disk='1M', memory='512M', cores=0.1))
and
        # ORIGINAL: self.encapsulatedFollowOn = Job(disk='1M', memory='32M', cores=0.1)
        self.encapsulatedFollowOn = Job(disk='100M', memory='512M', cores=0.1)
```
And the RunBlast jobs are not relaunching because of failure either (see #52) because I've upped the memory in these two lines in cactus's blast.py:
```
In RunSelfBlast:
        # ORIGINAL: memory = 3*seqFileID.size
        memory = max(700000000, 3*seqFileID.size)
and in RunBlast:
            # ORIGINAL: memory = 2*(seqFileID1.size + seqFileID2.size)
            memory = max(700000000, 2*(seqFileID1.size + seqFileID2.size))
```
Besides that, I've made no other changes to the cactus or toil code.

Could this possibly be related to @adamnovak's comment in DataBiosphere/toil#2590?  Quoting him:
*And we should also fix our notion that silence from a job equals success, or at least not report that kind of "success" to the user as success in the log. Toil is launching the same job repeatedly and hearing nothing back from any of the invocations; it should complain that the job got lost, treat it as a failure, and do a retry, not assert that it succeeded.*

I'm attaching the full cactus log in case its useful.  [cactus.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/3081866/cactus.log)

I don't know if this is an actual problem that needs to be examined or not, or if you were aware of this behavior, but I thought I should report it just in case.

Thanks,
Jason

**Comment by jasonsydes** [comment]
I should also note that (in contrast to the examples above) I'm seeing plenty of repeated jobs that have large differences in their Job ID numbers, such as:
```
INFO:toil.leader:Issued job 'ProgressiveNext' X/O/job3SjAPS with job batch system ID: 93 and cores: 1, disk: 2.0 G, and memory: 3.3 G
INFO:toil.leader:Job ended successfully: 'ProgressiveNext' X/O/job3SjAPS
INFO:toil.leader:Issued job 'ProgressiveNext' X/O/job3SjAPS with job batch system ID: 594 and cores: 1, disk: 2.0 G, and memory: 3.3 G
INFO:toil.leader:Job ended successfully: 'ProgressiveNext' X/O/job3SjAPS
```
So it strikes me as odd that a job would get launched (ID 93), supposedly finish successfully, wait for many many other jobs to run and finish, and then get launched again (ID 594) (looks possibly 17 minutes apart according to the log?).

**Comment by adamnovak** [comment]
I *think* this is an artifact of how Toil works. It is indeed creating
multiple submissions to the batch system (with different batch system
ID numbers) for the same Toil job. I think that the first one is what
does the actual work of the job, which involves creating child and
follow-on jobs, and then the second one runs later, maybe after the
child jobs, and cleans up the job.

I'm not sure why Toil feels the need to announce this the same way as
when it issues the job to be actually run. Perhaps the leader doesn't
know anything about the internal state of the job, and the worker
which gets run for it is responsible for figuring out it has already
done its actual work and needs cleanup. Nor am I really sure why it
can't just clean it up after it actually executes.

This could be wasteful of cluster resources, because it seems like it
is using the same requirements for both issuances. But I don't think
this phenomenon is visible from workflow code; the actual work is only
done once. This should not affect the operation of Cactus.

**Comment by jasonsydes** [comment]
Thanks for your insight @adamnovak. That helped me rule out one possibility.  I think I may have now figured out the actual cause of my actual problem (i.e. the 4way alignment job dying), so I probably won't need to submit that additional Issue that I had mentioned above.

Thank you for all your help!
