### ISSUE TITLE
Passing additional minigraph parameters

### ISSUE THREAD

**Issue by agolicz** [ComparativeGenomicsToolkit/cactus#758]
Hi,
I have a highly diverged region to align so the minigraph construct workflow would probably benefit from -j1 parameter (the graph suggests some under-alignment). Is there a way to pass additional parameters to cactus-minigraph? 
I tried changing minigraphConstructOptions to "-c -xggs -j1" in cactus-bin-v2.1.1/src/cactus/cactus_progressive_config.xml
But the log stills says:
[2022-08-02T12:59:46+0000] [MainThread] [I] [toil-rt] [minigraph]: [M::main] CMD: minigraph -c -xggs -t 6 hap1.fa hap2.0.fa
Agnieszka

**Comment by glennhickey** [comment]
You'd have to either do something like this
```
cp cactus-bin-v2.1.1/src/cactus/cactus_progressive_config.xml config.xml
# add your option
cactus-minigraph ..... --configFile ./config.xml
```
or if you edit `cactus-bin-v2.1.1/src/cactus/cactus_progressive_config.xml` directly, then you must run
```
pip install -U .
```
from the cactus directory for it to take effect.

**Comment by agolicz** [comment]
Great, thanks. That worked!
Agnieszka
