### ISSUE TITLE
After fresh install, attempt to run cactus reports "cwltool is not installed" and has several python tracebacks.

### ISSUE THREAD

**Issue by rsharris** [ComparativeGenomicsToolkit/cactus#762]
I have installed cactus v2.1.1 from pre-compiled linux tarball.

My machine is running debian with kernel 4.19.0-21-amd64, and the file system is nfs. My python is 3.8.13.

I ran what I was expecting to be a quicker test case than evolverMammals. My example has five 50Kbp "genomes" with induced divergence less than 5%. My command was `cactus jobstore seqFile.txt seqFile.hal` (run inside the virtualenv environment), where seqFile.txt is
```
(apefruit:0.182,cantalon:0.145,craisine:0.137,hubarine:0.071,pomelope:0.211,rhubange:0.142);
apefruit apefruit.fa
cantalon cantalon.fa
craisine craisine.fa
hubarine hubarine.fa
pomelope pomelope.fa
rhubange rhubange.fa
```

This ran for about 3 minutes.

The first output was
```
cwltool is not installed.
```

My guess is that is all that matters. There were four python exception tracebacks. Three of these were cactus/shared/common.py, line 868, in cactus_call raising RuntimeError. The other was /toil/leader.py", line 289, in run raising FailedJobsException. I'll post the full log if you think that's helpful.

I investigated `cwltool is not installed.` and it appears it is generated by toil/cwl/__init__.py when get_distribution("cwltool") raises an exception. Launching a python shell (inside the virtualenv) and trying get_distribution("cwltool") I do get a DistributionNotFound exception.

Comparing the output of the toil-requirement part of my installation, to a v2.0.5 that I was trying in April, I see that the v2.0.5 log shows
```
Collecting cwltool==3.1.20211107152837
  Downloading cwltool-3.1.20211107152837-py3-none-any.whl
```
while the v2.1.1 doesn't have anything for cwltool.

So, given that evidence, my guess is that I need cwltool (and toil/cwl/__init__.py is very specific about the version it needs) but for some reason it did not get installed.

**Comment by glennhickey** [comment]
No, the "cwtools is not installed" message is [harmless noise](https://github.com/DataBiosphere/toil/issues/4138).  You'll have to post the full log.  Also, please run with `--realTimeLogging` to get a better log of each command being run.

**Comment by rsharris** [comment]
Interesting. I'd done a search for issues containing "cwltools" but must've messed up the search — I didn't find 373.

Anyway, here is my full log:
[console log, 20220809C.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/9295911/console.log.20220809C.txt)

**Comment by glennhickey** [comment]
The underlying issue is as described in #574, see [this comment](https://github.com/ComparativeGenomicsToolkit/cactus/issues/574#issuecomment-926580117) in particular.

**Comment by rsharris** [comment]
Ahh, thanks. I'll either find a different machine to run cactus on -OR- I'll try the Pre-compiled Binaries For Older CPU Architectures (I don't think I need pangenome support but I need to read what that implies).

I should have tested whether the machine I was on had an appropriate CPU. But when I was at the release page (.../cactus/releases/tag/v2.1.1) my eye didn't consider the importance of that warning about AVX2. I remember noticing the one about not using the github tarballs, and the one about subscribing, so I must've read the AVX2 one and ignored it.

Thanks!

**Comment by glennhickey** [comment]
The story here is that we switched from Pecan to abPOA for filling in multiple alignments.  abPOA can be built without avx2, but I was getting segfaults on some big datasets with it.  

So by default, cactus builds with an avx2-enabled abpoa.  The legacy binaries will use Pecan instead (which is slower and also something we no longer tune for)

**Comment by rsharris** [comment]
I can confirm that the legacy binary cactus has successfully run my little test case.

This gives me a base against which to compare other installs. I may still try the non-legacy binary on another machine. "Slower" shouldn't be a big problem for me — my end game is just a half dozen primate X and Y chromosomes. But I wonder whether your meaning of "tune for" means the non-legacy binary might give better alignment results.

Thanks for your help.

**Comment by glennhickey** [comment]
I just mean we're not testing the old codepath much anymore when developing.  That said, the last time we did check, the accuracy was very comparable -- the main difference is the new version is way faster.

**Comment by glennhickey** [comment]
The "cwtool is not installed" message should go away after upgrading toil (#771)
