### ISSUE TITLE
cwltool is not installed

### ISSUE THREAD

**Issue by marcovth** [ComparativeGenomicsToolkit/cactus#770]
Hello ...

I continue to get "cwltool is not installed" lines while running cactus.

The cwltool is installed (pip install cwlref-runner), and executing fine when I enter it myself.

Anyway, could the cwltool be added to the docker image?

Thanks.

**Comment by glennhickey** [comment]
This message is annoying, but is harmless and can be ignored: https://github.com/ComparativeGenomicsToolkit/cactus/issues/762#issuecomment-1210059996
