### ISSUE TITLE
Failed to start the job in Terra using the example command in README

### ISSUE THREAD

**Issue by gq1** [ComparativeGenomicsToolkit/cactus#792]
https://github.com/ComparativeGenomicsToolkit/cactus/blob/9707fecdcc4d0026207cbbeac292cb0e2a745285/README.md?plain=1#L258

Use the above command to generate a WDL file and upload to Terra to run but the last step hal_append failed and here is the error message:

Execution failed: allocating: creating instance: inserting instance: Number of local SSDs for an instance of type n1-highmem-64 should be one of [0, 1, 2, 3, 4, 5, 6, 7, 8, 16, 24], while [10] is requested.

It seems we can't use 3750 disk size with 416G memory.

**Comment by glennhickey** [comment]
Thanks for pointing this out.  I'd just just changed this in an effort to simplify the process, but clearly didn't test it.  The [documentation](https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/) says

_The Disk type must be one of "LOCAL", "SSD", or "HDD". When set to "LOCAL", the size of the drive is constrained to 375 GB intervals so intermediate values will be rounded up to the next 375 GB. All disks are set to auto-delete after the job completes._

so the example (and underlying code) just keeps disk sizes rounded to the nearest 375. 

To fix this, you'd just need to change the `3750Gi` to something that's `375` * one of the multiples in `[0, 1, 2, 3, 4, 5, 6, 7, 8, 16, 24]`.  In general this value should be about twice the size of the final HAL output.

Cromwell supports specifying resources based on the input datasizes, so it'd be nice to one day implement this in `cactus-prepare`.  But for now we are stuck specifying everything by hand.  I will update Cactus to take into account the multiples list -- thanks.

**Comment by gq1** [comment]
Thanks.
