### ISSUE TITLE
cactus-graphmap throwing error at minigraph: galign.c:133

### ISSUE THREAD

**Issue by LindaMilne** [ComparativeGenomicsToolkit/cactus#800]
I've been trying out the cactus-minigraph pipeline and the yeast and primate examples worked for me. I get an error when I try with my own data. I've tried it with two barley genomes and with four, but get the same error in both. 

"minigraph: galign.c:133: mg_gchain_cigar: Assertion `l == gc->qe - gc->qs && gc->p->aplen == gc->pe - gc->ps' failed."

I've included the full output: 

[slurm-3405706_out.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/9673537/slurm-3405706_out.txt)

Thanks.

**Comment by glennhickey** [comment]
Goodness, this is a new one to me. Would it be possible for you to share the input data?

**Comment by LindaMilne** [comment]
I might be able to if I can get permission. Give me a while to see ....

**Comment by LindaMilne** [comment]
Ok, so I can't share the data files I originally used, but I repeated the process with very similar files I can share. I got the same error message. You can download them from here. 

https://ics.hutton.ac.uk/barleyrtd/data/
