### ISSUE TITLE
Capture all logging/output in a single place

### ISSUE THREAD

**Issue by sivico26** [ComparativeGenomicsToolkit/cactus#818]
Hi there, thanks for developing `Cactus`

I have been playing with Cactus lately to align several big plant genomes (~4Gb) of the same genus.

I have been struggling with several errors and issues, but I think I have managed to solve them so far. However, one thing that has made it especially difficult is that the logging and temporary files are leaky. What I mean by that is that temporary files/logs get redirected to wherever `Toil` thinks is appropriate. 

The problem is that the above behavior is usually exceeding my disk quota on my server and I get at best incomplete logs or at worst crashed jobs. I thought that `--workDir` was supposed to ensure that temporary files are handled in the given path, but unfortunately that is not guaranteed.

The latest issue I am experiencing is running the following command using `cactus v2.2.3`: 

```
cactus ./workdir seqFile hordeum.hal --workDir tmp --maxCores $threads --maxMemory 500Gi --defaultMemory 30Gi --defaultDisk 2000Gi --logFile log_restart --rotatingLogging --restart > extra_log_restart 2>&1
```

The process is crashing at `cactus_consolidated`:

```
[2022-10-25T17:49:45+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc3): ERROR: failed to create temporary file with pattern /var/tmp/pbs.13116228.meta-pbs.metacentrum.cz/stTmpXpOqiz: Disk quota exceeded
```

When I look up the file `stTmpXpOqiz`, it is essentially a `.paf` with alignments. Obviously `cactus_consolidated` is trying to output alignments somewhere to use them later, and when it cannot write anymore (reaches Disk quota) it crashes. Now, the question is why is it writing on `/var/tmp/pbs.13116228.meta-pbs.metacentrum.cz/` in the first place if I specified `--workDir`? How can I avoid this behavior and write to a single place where I can ensure I can give him the disk he needs? 

Is it just a matter of setting `TMPDIR`  environmental variable as you suggested previously (#755)? I am now trying this and I will report how it goes in this issue. Nevertheless, I wanted to ask you if setting this variable would guarantee no leaks or what would be the correct parametrization to get this guarantee.

Thanks in advance,

PS: I do not understand the `--logFile` parameter, because, as you can see from my command, even using it I have to redirect `stdout` and `stderr` to another file (which actually is massive compared to `log_restart`). So, this raises the question, what does `--logFile` actually do?

**Comment by diekhans** [comment]
I appears that PBS  is set TMPDIR  to /var/tmp/pbs.13116228.meta-pbs.metacentrum.cz/ .  You might not be able to override it externally to Toil.

**Comment by sivico26** [comment]
Okay so, just to confirm, setting TMPDIR should make the trick, right? 

I am running the job again making this adjustment. I will report how it goes.

**Comment by diekhans** [comment]
I don't know if setting TMPDIR will work, because PBS might overwrite it.

I have no experience with PBS. You might want to talk to your system
administrators.

**Comment by sivico26** [comment]
I am glad to report that setting ´TMPDIR´ and exporting it worked for PBS. I finally got the alignment. 

Thanks for the support.
