### ISSUE TITLE
cudaErrorMemoryAllocation and troubleshooting memory requirements

### ISSUE THREAD

**Issue by silastittes** [ComparativeGenomicsToolkit/cactus#830]
Hi there! 
I've attached the log for my most recent attempt at running cactus on some cephalopod genomes.
The uncompressed genome sizes are 2.6G, 1.7G, 4.9G, 3.9G, 2.3G, 4.9G, 4.6G, 2.6G, 711M, and 4.4G, with 
7376, 500, 2139, 1735, 48285, 2762, 583, 41584, 13516, 500, 77681, 500, and 5642 contigs, respectively.  

While the memory error is straightforward, I guess I'm just hoping for some advice as to how much memory roughly I should plan on needing, if this is feasible, etc. Currently giving the job 24G and 2 GPUs. As you can see from the log it runs for a good while before failing. 

Thanks for any and all suggestions! 

[cactus_error.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/9954122/cactus_error.txt)

**Comment by glennhickey** [comment]
We've recently discovered a bug in segalign that prevents it from masking a cuttlefish genome: https://github.com/gsneha26/SegAlign/issues/58.  In my tests, no amount of system or GPU memory was enough to get it to go through.  It used about 85G of system RAM (I forget how much GPU memory) before crashing, so your 24G is indeed too low.  But even if you added more memory, I think the odds are you'd run into the same problem as in the issue above.  The only work-around is to run `cactus-preprocess` with the CPU.  You can then continue with the gpu by running `cactus` on the output with the `--skipPreprocessor` option added.

**Comment by silastittes** [comment]
Thanks so much for the speedy and helpful reply! Will checkout the work-around you suggest.
