### ISSUE TITLE
Adjusting lastz parameters/scoring matrix

### ISSUE THREAD

**Issue by vpymerel** [ComparativeGenomicsToolkit/cactus#835]
Hello,

I was wondering is it possible to adjust lastz parameters (K,L,Y ...) including the scoring matrix used ?

Thank you,
V

**Comment by glennhickey** [comment]
lastz parameters are in the [config](https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.2.4/src/cactus/cactus_progressive_config.xml#L80-L88).  They are selected based on branch lengths as [mapped here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.2.4/src/cactus/cactus_progressive_config.xml#L9).  

You can edit this file to change the lastz paramaeters.  Or (recommended) copy the file to `my-config.xml`, edit it, then pass it to any cactus command with `--confgFile my-config.xml`

**Comment by vpymerel** [comment]
Thank you !
