### ISSUE TITLE
No such file or directory: 'scontrol'

### ISSUE THREAD

**Issue by silastittes** [ComparativeGenomicsToolkit/cactus#843]
Hi There! Following advice given in #830, I'm trying to preprocess with CPUs and then finish on GPUs. 
I'm working on an HPC and am hoping to parallelize the CPU runs as much as possible.
When I run the following command:

```
singularity exec \
          --bind $PWD \
          --nv \
          --workdir / docker://quay.io/comparative-genomics-toolkit/cactus:v2.2.4-gpu \
          cactus jobstore/1 {input.prepared_out} {output} \
          --realTimeLogging \
          --logInfo \
          --retryCount 0 \
          --skipPreprocessor \
          --batchSystem slurm \
          --consCores 20 \
          --restart \
          --disableCaching \
          --configFile {input.xml}
```

I get the error:
`No such file or directory: 'scontrol'`
Any thoughts on what's happening here? Are slurm user commands available inside the container?
Apologies if this has been answered elsewhere and I missed it!

**Comment by glennhickey** [comment]
slurm commands are not available in the container.  your best bet is to install cactus locally (ie following the binary release installation instructions) then to run with `--binariesMode singularity` so that toil jobs pull in commands from singularity as-needed.

**Comment by silastittes** [comment]
That makes sense. Thanks!
