### ISSUE TITLE
RuntimeError paf_to_bed

### ISSUE THREAD

**Issue by silastittes** [ComparativeGenomicsToolkit/cactus#845]
I'm getting an error towards the end of the pipeline.

Here's the relevant output section.

```
[2022-11-30T11:34:41-0800] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-M
ASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement
, otherwise, consider increasing the disk requirement. Job 'make_ingroup_to_outgroup_alignments_
2' kind-make_ingroup_to_outgroup_alignments_2/instance-hecl3jgc v7 used 10403.60% disk (208.1 Gi
B [223415685120B] used, 2.0 GiB [2147483648B] requested).                                       
        Traceback (most recent call last):                                                      
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 407, i
n workerScript                                                                                  
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)     
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2406, in 
_runner                                                                                         
            returnValues = self._run(jobGraph=None, fileStore=fileStore)                        
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2324, in 
_run                                                                                            
            return self.run(fileStore)                                                          
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2547, in
run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/paf/local_alignment.p
y", line 173, in make_ingroup_to_outgroup_alignments_2
            messages = cactus_call(parameters=['paf_to_bed', "--excludeAligned", "--binary",
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", li
ne 794, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.ret
urncode, out))
        RuntimeError: Command /usr/bin/time -v paf_to_bed --excludeAligned --binary --minSize 10
0 -i /home/stittes/tmp/e38121e7ffd15640b9b3d3c1e2033958/c55a/8279/tmptrhl5hjg.tmp --logLevel INF
O exited 137: stdout=None, stderr=Input file string : /home/stittes/tmp/e38121e7ffd15640b9b3d3c1
e2033958/c55a/8279/tmptrhl5hjg.tmp
        Output file string : (null)
        Command terminated by signal 9
Command being timed: "paf_to_bed --excludeAligned --binary --minSize 100 -i /hom
e/stittes/tmp/e38121e7ffd15640b9b3d3c1e2033958/c55a/8279/tmptrhl5hjg.tmp --logLevel INFO"       
                User time (seconds): 1178.14
                System time (seconds): 175.55
                Percent of CPU this job got: 88%
                Elapsed (wall clock) time (h:mm:ss or m:ss): 25:38.07
                Average shared text size (kbytes): 0
                Average unshared data size (kbytes): 0
                Average stack size (kbytes): 0
                Average total size (kbytes): 0
                Maximum resident set size (kbytes): 255133332
                Average resident set size (kbytes): 0
                Major (requiring I/O) page faults: 1673
                Minor (reclaiming a frame) page faults: 64348752
                Voluntary context switches: 5432
                Involuntary context switches: 196950
                Swaps: 0
                File system inputs: 50968008
                File system outputs: 0
                Socket messages sent: 0
                Socket messages received: 0
                Signals delivered: 0
                Page size (bytes): 4096
                Exit status: 0
```

The input file `/home/stittes/tmp/e38121e7ffd15640b9b3d3c1e2033958/c55a/8279/tmptrhl5hjg.tmp` Doesn't seem to exists. 

I did need to resume the run a few times because of disk space issues.

Any thoughts as to the problem and how to fix? I'm running via singularity, with v2.2.3-gpu

**Comment by glennhickey** [comment]
Seems like `paf_to_bed` was killed (`terminated by signal 9`), presumably by your OS or cluster environment.  This generally happens when something uses too much memory.  In this case your log shows it using `255Gb` before dying which is indeed quite a bit. 

I've never seen a problem with this particular tool before.  But I'd have to suspect that maybe your input genomes are not `RepeatMasksed` or not properly `RepeatMasksed`, and it's leading to giant alignments of repetitive regions which are overrunning this tool.  

You can get the input file by running with `--disableCaching --cleanWorkDir never`.  If it is massive, I think that would support the idea above.  If not, and you can share it, I would be curious to try to reproduce.

**Comment by silastittes** [comment]
Thanks (as always) for your speedy and helpful reply! 
I don't have a good frame of reference to judge, but the input file for `paf_to_bed` is ~209G, which seems notable.
Regarding repeat masking, the amount of sequence that is softmasked seems to be in the right ballpark based on previous studies. We are using single custom repeat library built using the unmasked input genomes. 

```
Architeuthis_dux masked: 1108430822 bp ( 41.15 %)
Doryteuthis_pealeii masked: 2955303676 bp ( 64.27 %)
Euprymna_scolopes masked: 1746824457 bp ( 34.14 %)
Hapalochlaena_maculosa masked: 1416682979 bp ( 35.33 %)
Nautilus_pompilius masked:   81030393 bp ( 11.09 %)
Octopus_bimaculoides masked: 1392740498 bp ( 59.37 %)
Octopus_minor masked: 3614304936 bp ( 71.00 %)
Octopus_sinensis masked: 1684375059 bp ( 61.94 %)
Octopus_vulgaris masked:  742183083 bp ( 41.86 %)
Sepia_pharaonis masked: 2862957625 bp ( 59.83 %)
```

The overall percentages look to scale with genome size. Nautilus_pompilius genome is small, so I wouldn't expect that alone to be the issue, but can't say for sure. 

All but one of these is a public resource. If you'd still like to reproduce, I can check with my colleagues to see if they're ok sharing the new genome for this purpose. 

Thanks!

**Comment by glennhickey** [comment]
209G is indeed huge for a paf file.  I guess `paf_to_bed` reads the whole thing in memory.  But even if it didn't, in the next phase `cactus_consolidated` would need to make a graph out of all inputs and use even more memory. 

This almost certainly boils down to unmasked repeats causing massive numbers of alignments to be found.  We definitely want to make cactus more robust to such circumstances, but that's still at least a little ways off.  

So these genomes were masked with `cactus-preprocess` as well as RepeatMasker with a de-novo library?  I'm not sure what I could suggest beyond that, perhaps windowmasker?  It could be just one genome spoiling it for everything (in which case running step-by-step with `cactus-prepare` might be informative).  

In general though, for genomes this size, especially if they are divergent, you will probably need more that 256Gb RAM to get through the whole pipeline even on the best days.

**Comment by silastittes** [comment]
Really appreciate all the guidance! Repeats being the core issue makes sense for these genomes. I'll spend some time thinking about our masking procedure.
