### ISSUE TITLE
How to extract Minigraph-Cactus bubble fasta

### ISSUE THREAD

**Issue by ld9866** [ComparativeGenomicsToolkit/cactus#849]
Hello developer!
At present, we are using Minigraph Cactus as our method to construct pan genome, but we found that only the vcf file in the tutorial can be used for subsequent analysis, and unlike minigraph, we can use gfatools bubble to extract pan sequences. We want to know how we should extract non reference sequences for subsequent analysis.
Thank you!
Dong

**Comment by ld9866** [comment]
Hello developer!
Thank you for your prompt reply. 
At present, we want to extract non reference genome sequences to check whether there are any neglected genes in the sequences that are not in the genome. 
I would like to ask you what method we should use to extract the fasta we want from the vcf file?
Thank you

**Comment by glennhickey** [comment]
In VCF, the non reference sequences would appear in the 5th column, and `bcftools` has many filters available for extracting them.  That said, you'd have to convert them into FASTA yourself. 

`vg paths` can convert paths in your graph to FASTA, But I don't see any way to drop all nodes from a reference path from the graph.  `vg mod` `vg clip` and `clip-vg` can all do similar things but not exactly that.  

So I do agree with you that this is an interesting feature request.  I will look into adding it to `vg`.

**Comment by ld9866** [comment]
Thank you for your advice
I will use your suggestions to test！
Best wishes!
