### ISSUE TITLE
Can't globalize module ModuleDescriptor in AWS and PicklingError

### ISSUE THREAD

**Issue by Secretloong** [ComparativeGenomicsToolkit/cactus#86]
I have restarted the Cactus, and the Warnings are still there.  
All steps follow the instruction https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/running-in-aws.md

Following is the detail log.
[error.example.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3449463/error.example.txt)

**Comment by joelarmstrong** [comment]
What version of Toil are you using? Did you possibly start the run with one version of toil and continue it with a different one? I know the location of the "BotoCredentialAdapter" changed in a relatively recent version of Toil.

**Comment by Secretloong** [comment]
Now I use this one: quay.io/ucsc_cgl/toil:3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932

And which one should I use for TOIL_APPLIANCE_SELF? I found quay.io/joelarmstrong/toil:latest doesn't work. Always 400 Bad Request.

**Comment by Secretloong** [comment]
With "TOIL_DOCKER_REGISTRY=quay.io/jorlarmstrong TOIL_APPLIANCE_SELF=quay.io/joelarmstrong/toil:latest", it works
