### ISSUE TITLE
Singularity executable not available in Docker container

### ISSUE THREAD

**Issue by oneillkza** [ComparativeGenomicsToolkit/cactus#868]
I'm trying to run cactus from the Docker container via singularity, and one issue it has is that it needs to run singularity from within singularity to pull the container. I eventually managed to figure out a workaround by binding the singularity and mksquashfs executables from the host into the container, but this is pretty cludgy and took a lot of fiddling to figure out. 
In my case, it was:

```
export SINGULARITYENV_APPEND_PATH=/opt/singularity-3.7.3/bin
/opt/singularity-3.7.3/bin/singularity exec -B /projects,/opt/singularity-3.7.3,/usr/bin/mksquashfs cactus_v2.3.0-gpu.sif cactus
```

It would be much easier if singularity was just built into the container in the first place, and if there were some instructions on running cactus with singularity.

**Comment by glennhickey** [comment]
I can't think of a use case of why you'd want to run singularity from within docker.  Could you please elaborate?

**Comment by oneillkza** [comment]
Well no I'm trying to run cactus using Singularity, by running the Docker image, on a slurm cluster. That means I have to run the master process inside the container, as above, but also that I'm passing the `--binariesMode singularity` parameter so Toil knows to run the jobs it spawns using Singularity as well. So cactus calls the various bits of code in `common.py` (e.g. `importSingularityImage`). For those, it needs the singularity binary to be on the path, which it is not when running inside the container.

**Comment by glennhickey** [comment]
As mentioned [here](https://github.com/ComparativeGenomicsToolkit/cactus/issues/843#issuecomment-1322630983), your best bet is to follow the binaries install instructions to install cactus on your head node, then run cactus with `--binariesMode singularity` from there.

**Comment by oneillkza** [comment]
Thanks -- I did see that, but it will be an even bigger headache than the way I've done it. 

ie I'd have to fiddle around with miniconda to get virtualenv and python3 set up before even getting started.

**Comment by glennhickey** [comment]
OK, I see.  Still, I'm surprised your hack would work given that, like in that other issue, you wouldn't expect to have your cluster-specific commands available inside the cactus image.  Anyway, sorry I couldn't help more.

**Comment by oneillkza** [comment]
Yeah it is a bit surprising -- I'm guessing that any dependencies for singularity are just in the right place since both the compute nodes on our GPU cluster and the container are running similar versions of Ubuntu.

**Comment by oneillkza** [comment]
And yep, where it falls over is that it also needs all the slurm executables to be available in the container. I guess it might be possible to include those (and singularity) in the Dockerfile, but in practice it's going to be easier to set up a Conda environment and run the cactus master process from there.
