### ISSUE TITLE
RuntimeError: Failed to parse newick tree:

### ISSUE THREAD

**Issue by oneillkza** [ComparativeGenomicsToolkit/cactus#869]
I'm trying to run cactus for the first time, and it's not happy with the Newick tree I gave it.

This is the tree I'm using, obtained from NCBI Taxonomy:

```
(Homo_sapiens:4,Gallus_gallus:4,((Actinemys_pallida:4,Actinemys_marmorata:4)Actinemys:4,(Aldabrachelys_gigantea:4,Chelonoidis_abingdonii:4)Testudinidae:4,(Cuora_mccordi:4,Cuora_amboinensis:4)Cuora:4,Dermatemys_mawii:4,Apalone_spinifera:4,Carettochelys_insculpta:4,Chelydra_serpentina:4,(Chelonia_mydas:4,Caretta_caretta:4)Cheloniidae:4)Testudines:4)Chordata:4
```

I saw on another issue the advice to paste the tree into http://etetoolkit.org/treeview/ and if it works there, it would most likely be fine for cactus. It does work there, but does not work with cactus.

I've seen some vague hints in other issues that cactus prefers (maybe even requires) that the tree be binary, but couldn't find anything explicit about that.

Is there somewhere in the documentation that specifies the exact format and requirements for the Newick tree to be accepted by cactus? And/or suggestions for generating one?

**Comment by glennhickey** [comment]
The exact format is described [here](https://en.wikipedia.org/wiki/Newick_format).  Note that it requires a `;` at the end.

**Comment by oneillkza** [comment]
Thanks -- the semicolon seems to be the main issue.

But now I'm getting 

```
RuntimeError: Error parsing tree "((Homo_sapiens:4.0,Gallus_gallus:4.0,((Actinemys_pallida:4.0,Actinemys_marmorata:4.0)Actinemys:4.0,(Aldabrachelys_gigantea:4.0,Chelonoidis_abingdonii:4.0)Testudinidae:4.0,(Cuora_mccordi:4.0,Cuora_amboinensis:4.0)Cuora:4.0,Dermatemys_mawii:4.0,Apalone_spinifera:4.0,Carettochelys_insculpta:4.0,Chelydra_serpentina:4.0,(Chelonia_mydas:4.0,Caretta_caretta:4.0)Cheloniidae:4.0)Testudines:4.0)Chordata:4.0)Anc0;":
 Node Anc0 (parent of Chordata) has single descendant: Please remove all such nodes and try again.
```

Why is it adding a single-descendent ancestor beyond the root of the tree (and then complaining about it?)


It works if I turn it into a binary tree and strip out all of the intermediary branches, ie:

```
((Homo_sapiens:10,Gallus_gallus:10),((Actinemys_pallida:4,Actinemys_marmorataActinemys:4),(Aldabrachelys_gigantea:4,Chelonoidis_abingdonii:4),(Cuora_mccordi:4,Cuora_amboinensis:4),(Dermatemys_mawii:4,Apalone_spinifera:4),(Carettochelys_insculpta:4,Chelydra_serpentina:4),(Chelonia_mydas:4,Caretta_caretta:4)));
```

But these are additional requirements beyond the Newick format.

It also supplies warnings like:

```
WARNING: Long branch length of 4.0 detected between Anc5 and Apalone_spinifera: Are you sure input branches reflect substitutions per site?
```

I'm 100% sure the distances are just placeholder values from NCBI Taxonomy. The documentation doesn't specify that they have to be reflect substitutions per site. How important is this? There's something called the R35 Fingerprint Protein for the turtles from which I can probably cludge together a molecular phylogeny, and I guess just set branch lengths to the outgroups at 1.0.

**Comment by glennhickey** [comment]
You got me: there is one additional requirement to the newick standard:  each ancestral node must have at least two children in the tree.  Because you have a branch length on `Chordata`, it thinks there is a node above it (with a single child) and complains. 

Cactus expects the branch lengths to be substitutions per site.

**Comment by oneillkza** [comment]
Thanks -- that makes sense.

How critical is it that the branch lengths be accurate? 

In a lot of our use cases, we're likely to have whole genome assemblies but possibly no gene annotations, so creating accurate molecular phylogenies might be a bit challenging. (Probably not impossible -- I guess we could fish out things like rRNA genes and such from the assemblies -- but definitely a large extra step.)

**Comment by glennhickey** [comment]
I answered this in the [FAQ](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#frequently-asked-questions)

**Comment by oneillkza** [comment]
Thanks! I'd missed that.

That's quite helpful. I also see that there's a tool called mashtree that will run mash and generate Newick trees all in one, so am in the process of trying that.

**Comment by oneillkza** [comment]
As noted above, the solution was to use mash (most easily via mashtree). This very quickly generates a tree using whole-genome fastas. (In my case, about 12 species complete within a minute or so on 72 cpus).

https://github.com/lskatz/mashtree
