### ISSUE TITLE
cactus-update-prepare replace AttributeError

### ISSUE THREAD

**Issue by JohnsonStev** [ComparativeGenomicsToolkit/cactus#908]
Hi, I am running cactus with the test data set using the command on the manual

cactus-update-prepare replace ./evolverMammals.hal ./input.txt --genome simHuman_chr6 --outDir ./steps --jobStore ./jobstore

and get this error
Traceback (most recent call last):
  File "cactus-bin-v2.4.0/cactus_env/bin/cactus-update-prepare", line 8, in <module>
    sys.exit(main())
  File "cactus-bin-v2.4.0/cactus_env/lib/python3.9/site-packages/cactus/update/cactus_update_prepare.py", line 1068, in main
    if not options.subcommand:
AttributeError: 'Namespace' object has no attribute 'subcommand'

However, I was able to run commands like add node.

**Comment by glennhickey** [comment]
@thiagogenez are you able to look at this?

**Comment by thiagogenez** [comment]
> @thiagogenez are you able to look at this?

Sure @glennhickey, thanks for letting me know. 

@JohnsonStev Thanks for reporting this issue. Will have a look and do a fix soon. Please let me know if you need a hand in the mean time to replace a genome. Thanks

**Comment by glennhickey** [comment]
Closed via #983
