### ISSUE TITLE
help with memory config

### ISSUE THREAD

**Issue by larryns** [ComparativeGenomicsToolkit/cactus#919]
Hi,

I'm running cactus in an environment that apparently seems pretty strick with memory requirements. My CactusHeadersJob is dying seemingly because it runs out of memory. I've tried to copy the default cactus_progressive_config.xml file and edited ```<preprocessor memory="mediumMemory" preprocessJob="cutHeaders" cutBefore="" cutAfter=". " active="1"/>```, and I've changed ```<defines littleMemory="2000000000" mediumMemory="4000000000" bigMemory="5000000000"/>```. Still it looks like the CactusHeadersJob is only using 2.0Gb from the logs. What am I missing?

Also, I don't quite understand how to change the disk requirements in the config file. Can someone please point me to an example or explain that to me?

Thanks for any help,
Larry.

**Comment by glennhickey** [comment]
Job requirements are either
* estimated from the data (for most larger jobs)
* not set by cactus, which means the default will be used (you can change with `--defaultMemory`, `--defaultDist` etc)
* "mediumMemory", "bigMemory" etc, which will be affected by the value in the config

Unforuntately, there's no global way to boost them all up (though it could be an interesting option).

**Comment by larryns** [comment]
Thanks for the help! So, the problem may not be with cactus. I'm trying to use the aws_batch batchSystem and running into problems. Are there any guidelines for this? I can also ask on the toil github.

Thanks!

**Comment by larryns** [comment]
Ya mesos seems to work for me. The only issue I've run into is that sometimes the nodes are not available in the AZ, and then toil gives a lot of warnings. AWS Batch gets around a lot of these issues and allows me to run different node combinations. If aws_batch isn't ready for prime time, then I'll go back to mesos, but thought I'd try.

Thanks again. Will close the issue soon, unless you have other thoughts.

**Comment by adamnovak** [comment]
We unfortunately don't have a Toil guide for running anything on AWS Batch outside of Amazon Genomics CLI, which is the use case we added the feature for. I was doing all that work and I don't actually *know* how to set up Amazon Batch, other than to ask the `agc` command line tool to deploy an AGC "context" that includes it.

The docs on how to run CWL workflows on Toil *inside* AGC would be in the AGC tool's docs, but they don't seem to have a real tutorial there, just a reference at https://aws.github.io/amazon-genomics-cli/docs/workflow-engines/toil/, and anyway that won't help run Cactus which doesn't have a CWL workflow implementation.

**Comment by larryns** [comment]
Thanks @glennhickey  and @adamnovak I'm going to close this issue. If I make progress on batch, I'll re-open and add any info.
