### ISSUE TITLE
Joining subtree of  HAL alignments

### ISSUE THREAD

**Issue by maomao2023** [ComparativeGenomicsToolkit/cactus#933]
Hi, 

I want to generated 100 whole genome sequences alignment using Cactus 2.1.1 version. To parallelize processing, I want to align these genomes from a lot of  subtrees to generated subtree hal files (marked with colors in the guide tree here) and merge them back onto an alignment of the root alignment using halAppendSubtree. Details:

![image](https://user-images.githubusercontent.com/121856797/219284644-37712193-7a79-49a9-906d-c31db9402732.png)
![image](https://user-images.githubusercontent.com/121856797/219284740-28faced0-6156-46f2-8fb4-900827d6c837.png)
![image](https://user-images.githubusercontent.com/121856797/219284788-359bf73c-f65b-452d-9d49-f53e699edceb.png)

1)   I ran three separate cactus comparisons, corresponding to the following three topologies, **Tree_1** and **Tree_2** . 

     In Tree_1, I generated hal file for  **(((subtree_1,C),B,),A);**  , named "**subtree_1.hal**" 

     In Tree_2, I generated hal file for  **(((subtree_2,C),B,),A);**  , named "**subtree_2.hal**" 

2)   Respectively removed A, B and C from "**subtree_1.hal**" and "**subtree_2.hal**", then hal2fasta to extract subtree_1 root sequences (**Red node**) and subtree_2 root sequecnes (**Green node**). 

3)   Re-run cactus with tree **((((Red, Green),C),B),A)** to generated the root hal file, named "**Root.hal**",  shown in Figure **Tree_3**.

4)   When I want to merge **"subtree_1.hal"** and **"subtree_2.hal"** into **"Root.hal"** using halAppendSubtree, i found the highest nodes in both of these two hal files are not the **Red** or **Green**.  I think that's definitely not the right way to merge, right?

So i checked issues in github, found some people has been asked the same question, such as #863. BUT, I still met some problems according to the reply at issues #863.  Details:

I first use "halExtract" with "--root" paramater to extract the subtree hal files with the specified node name. The extracted command is : 

"halExtract subtree_1.hal  subtree_1.root.hal  --root Red" 

"halExtract subtree_2.hal  subtree_2.root.hal  --root Green"

I also checked the highest node in these two subtree root hal files (**subtree_1.root.hal** and **subtree_2.root.hal**) that doesn't have A, B, C under it and the root is **Red** and **Green**, respectively. 

But I have a problem with the result of "halExtract". That is the extracted hal file (such as subtree_1.root.hal and subtree_2.root.hal) can not transform to maf format using "hal2maf" and just shown "Segmentation fault (core dumped)" error.  

Then I use "hal2fasta" to extracte the **Red** and **Green** sequecnes in **"subtree_1.root.hal"** and **"subtree_2.root.hal"** and got the fasta format files.  What surprised me was the sequence ID was not include in the maf file I transformed from raw hal (e.g. subtree_1.hal or subtree_2.hal).  

Also, when i use "halAppendSubtree" to merge **"subtree_1.root.hal"** and **"subtree_2.root.hal"** into **"Root.hal"**. The commands are 

 "halAppendSubtree --merge Root.hal subtree_1.root.hal Red Red"

 "halAppendSubtree --merge Root.hal subtree_2.root.hal Green  Green "

BUT it still tell me "Segmentation fault (core dumped)".  I have double checked the node names and make sure no genomes have the same name in "**subtree_1.root.hal**" and "**subtree_2.root.hal**" . 

The above are some of my experiences. I am not sure whether there is something wrong with my process, and whether the problems I have encountered are caused by my negligence in the process of handling. And whether there are other ways to get the alignment results for all species based on my existing results (such as subtree_1.hal, subtree_2.hal and Root.hal).  Looking forward to a reply very much

**Comment by glennhickey** [comment]
Hi, If I understand correctly, what you want to do really should be fine with 
```
halExtract subtree_1.hal subtree_1.root.hal --root Red --inMemory
halExtract subtree_2.hal subtree_2.root.hal --root Green --inMemory
halAppendSubtree --merge Root.hal subtree_1.root.hal Red Red --inMemory
halAppendSubtree --merge Root.hal subtree_2.root.hal Green Green  --inMemory
```
I think the first thing to do is to run `halValidate --inMemory` on `subtree_1.hal`, `subtree_2.hal` and `Root.hal` (hopefully you've backed this one up since your failed run of `halAppendSubtree` will have corrupted it).

If those all check out, then I would suggest installing the latest release of cactus (2.4.2) which contains a patch to `halAppendSubtree` which may fix this segmentation in that tool.

**Comment by maomao2023** [comment]
Thank you Glenn,  the first thing you mentioned i have tried and got the result shown "File valid" for each hal files (**subtree_1.hal**, **subtree_2.hal** and **Root.hal** , **also subtree_1.root.hal and subtree_2.root.hal**), does this mean my hal files are fine? 

But I still can't convert **subtree_1.root.hal** and **subtree_2.root.hal**  to normal maf format.  Is the hal file no longer converted to maf after extraction? i mean the **subtree_1.root.hal** and **subtree_2.root.hal**.

**Comment by maomao2023** [comment]
Sorry, Glenn,  I tried according to the version you said, but there were still errors and said **"Segmentation fault"** when i use **halAppendSubtree** (version 2.4.2).  I can send you the hal files of the test. It contained a small amount of data set, and there were already some errors. Could you help me check what the problem is? 
[Root hal file.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/10764295/Root.hal.file.zip)
[Subtree_1 hal file.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/10764314/Subtree_1.hal.file.zip)
[Subtree_1.root hal file.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/10764357/Subtree_1.root.hal.file.zip)

**Comment by glennhickey** [comment]
Look at `Sub_hal_1_root` in each file
```
halStats Root.hal | grep Sub_hal_1_root | tail -1
Sub_hal_1_root, 0, 616928, 250, 17462, 0

halStats Subtree_1.hal | grep Sub_hal_1_root | tail -1
Sub_hal_1_root, 2, 618022, 307, 19239, 33056
```
These are different sequences.  You therefore cannot use `halAppendSubtree` to merge the two alignments.  The only way that would work is if the sequences are the same.  This tells me that `Root.hal` was **not** made using `Sub_hal_1_root` as extracted with `hal2fasta Subtree_1.hal` .  (it's the 616928, 250 vs 618022, 307 which shows total length, number of contigs that I'm looking at -- you can also check they're differetn with hal2fasta). 

* * 

For `hal2maf`, that does look like a bug in `halExtract --root`.  I'll note that it will work using any genome *except* the root as a reference.  So this works
```
for i in Centrophorus_acus Sub_hal_1_anc4 Squatina_nebulosa Pristiophorus_japonicus ; \
   do hal2maf Subtree_1.root.hal out.maf --refGenome $i --inMemory; \
done
```
but as soon as you do `hal2maf Subtree_1.root.hal out.maf --refGenome Sub_hal_1_root` it crashes. 

If you really want to make a root-based MAF for that file you can, by rerunning `halExtract`:
```
halExtract Subtree_1.root.hal Subtree_1.root.fix.hal --inMemory
```
then `hal2maf Subtree_1.root.fix.hal out.maf` will work fine.  I've made a bug report with HAL: https://github.com/ComparativeGenomicsToolkit/hal/issues/263

**Comment by maomao2023** [comment]
Thank you Glenn, according to your suggestion, I can merge with the test data. Now I'm using real data, which is a lot bigger than test data, so hopefully everything goes well.

**Comment by xiaolongtu** [comment]
hi, have you solve this problem ?
