### ISSUE TITLE
cactus-graphmap-join error: unrecognized arguments: --wlineSep . --gfaffix

### ISSUE THREAD

**Issue by Phonenix233** [ComparativeGenomicsToolkit/cactus#953]
Hello, I met a problem when I was using cactus-graphmap-join to finish the last step to fix up the final pan genome. I don't know why and what should I do?
`cactus-graphmap-join ./jobstore --wlineSep "." --vg Quercus8_pangenopme_rename/chrom-alignments/*.vg --hal Quercus8_pangenopme_rename/chrom-alignments/*.hal --outDir ./Quercus-pg --outName Quercus-pg --reference Quercus_aquifolioides --vcf --giraffe --gfaffix
`
The error is
`cactus-graphmap-join: error: unrecognized arguments: --wlineSep . --gfaffix`

**Comment by glennhickey** [comment]
`cactus-graphmap-join`'s interface was changed back in version [2.3.0](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.3.0).  The `--wlineSep` and `--gfaffix` options no longer exist.  You can just run that same command without using those two options.  

I'm guessing you're getting this from the examples here: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/mc-pangenomes/README.md so I added a similar note to that page.

**Comment by Phonenix233** [comment]
Thanks for your explanation!
But I met another error without using --wlineSep and --gfaffix , 
The error is 
`Traceback (most recent call last):
	  File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2743, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2660, in _run
	    return self.run(fileStore)
	  File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2888, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap_join.py", line 673, in cat_stats
	    cactus_call(parameters=['tar', 'czf', os.path.join(work_dir, 'stats.tgz')] + list(merged_dict.values()))
	  File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 772, in cactus_call
	    output, stderr = process.communicate(stdin_string if first_run else None, timeout=10)
	  File "/usr/lib/python3.8/subprocess.py", line 1029, in communicate
	    stdout, stderr = self._communicate(input, endtime, timeout)
	  File "/usr/lib/python3.8/subprocess.py", line 1911, in _communicate
	    stderr = self._translate_newlines(stderr,
	  File "/usr/lib/python3.8/subprocess.py", line 906, in _translate_newlines
	    data = data.decode(encoding, errors)
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 5: ordinal not in range(128)
	[2023-03-09T21:44:39+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host dell-PowerEdge-R440`

**Comment by Phonenix233** [comment]
> Thanks for your explanation! But I met another error without using --wlineSep and --gfaffix , The error is
> 
> `Traceback (most recent call last): File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer) File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2743, in _runner returnValues = self._run(jobGraph=None, fileStore=fileStore) File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2660, in _run return self.run(fileStore) File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2888, in run rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs) File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap_join.py", line 673, in cat_stats cactus_call(parameters=['tar', 'czf', os.path.join(work_dir, 'stats.tgz')] + list(merged_dict.values())) File "/data/yxzhu/software/cactus-bin-v2.4.2/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 772, in cactus_call output, stderr = process.communicate(stdin_string if first_run else None, timeout=10) File "/usr/lib/python3.8/subprocess.py", line 1029, in communicate stdout, stderr = self._communicate(input, endtime, timeout) File "/usr/lib/python3.8/subprocess.py", line 1911, in _communicate stderr = self._translate_newlines(stderr, File "/usr/lib/python3.8/subprocess.py", line 906, in _translate_newlines data = data.decode(encoding, errors) UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 5: ordinal not in range(128) [2023-03-09T21:44:39+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host dell-PowerEdge-R440`

I have solved this error by changing my locale environment.
