### ISSUE TITLE
cactus-graphmap-join error in vg validate step

### ISSUE THREAD

**Issue by ETC100** [ComparativeGenomicsToolkit/cactus#971]
Hello,
I tried to construct graph pangenome with cactus version 2.4.3 and complete the cactus-minigraph, cactus-graphmap, cactus-graphmap-split, cactus-align-batch steps. However, when I ran cactus-graphmap-join step with command cactus-graphmap-join ./jobstore --vg graph_chroms1/alignments/*.vg --hal graph_chroms1/alignments/*.hal --outDir ./Result --outName Last_graph --reference REF --vcf --giraffe clip", It cause an error as followed. "NC_006096.5" means "Chr9" chromosome, so it seems that error only occured in Chr9.
The related file you might need: [https://drive.google.com/file/d/1-90qWGcrvPyvx4h-8rlpllFk7PwQLORy/view?usp=share_link](url)

### Error
        [2023-03-22T00:17:00+0800] [MainThread] [I] [toil-rt] 2023-03-22 00:17:00.664846: Running the command: "vg validate /tmp/7354cdf93ebd53ce9cae66b053fc47da/3538/ec6f/tmppo15uaev/NC_006096.5.vg.clip"
        [2023-03-22T00:17:15+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-03-22T00:17:15+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-8e4f1e0faa464ff7910cfa98df7184c1/NC_006096.5.vg' to path '/tmp/7354cdf93ebd53ce9cae66b053fc47da/3538/ec6f/tmppo15uaev/NC_006096.5.vg'
        Traceback (most recent call last):
          File "/home/user/anaconda3/envs/graph_genome/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/user/anaconda3/envs/graph_genome/lib/python3.8/site-packages/toil/job.py", line 2743, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/user/anaconda3/envs/graph_genome/lib/python3.8/site-packages/toil/job.py", line 2660, in _run
            return self.run(fileStore)
          File "/home/user/anaconda3/envs/graph_genome/lib/python3.8/site-packages/toil/job.py", line 2888, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/user/anaconda3/envs/graph_genome/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap_join.py", line 421, in clip_vg
            cactus_call(parameters=['vg', 'validate', clipped_path])
          File "/home/user/anaconda3/envs/graph_genome/lib/python3.8/site-packages/cactus/shared/common.py", line 839, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command ['vg', 'validate', '/tmp/7354cdf93ebd53ce9cae66b053fc47da/3538/ec6f/tmppo15uaev/NC_006096.5.vg.clip'] exited 1: stdout=None, stderr=graph invalid: missing edge between 434922th step (320323:0) and 434923th step (877048:0) of path BLH#0#Chr9#0
        graph invalid: missing edge between 434923th step (877048:1) and 434922th step (320323:0) of path BLH#0#Chr9#0
        graph invalid: missing edge between 434555th step (320323:0) and 434556th step (877048:0) of path Thailand#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 434556th step (877048:1) and 434555th step (320323:0) of path Thailand#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 436330th step (320323:0) and 436331th step (877048:0) of path Cornish#0#Chr9#0
        graph invalid: missing edge between 436331th step (877048:1) and 436330th step (320323:0) of path Cornish#0#Chr9#0
        graph invalid: missing edge between 926th step (320323:0) and 927th step (877048:0) of path _MINIGRAPH_#s57999
        graph invalid: missing edge between 927th step (877048:1) and 926th step (320323:0) of path _MINIGRAPH_#s57999
        graph invalid: missing edge between 433238th step (320323:0) and 433239th step (877048:0) of path Houdan#0#Chr9#0
        graph invalid: missing edge between 433239th step (877048:1) and 433238th step (320323:0) of path Houdan#0#Chr9#0
        graph invalid: missing edge between 442338th step (320323:0) and 442339th step (877048:0) of path Naked_neck#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 442339th step (877048:1) and 442338th step (320323:0) of path Naked_neck#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 434937th step (320323:0) and 434938th step (877048:0) of path Silkies#0#Chr9#0
        graph invalid: missing edge between 434938th step (877048:1) and 434937th step (320323:0) of path Silkies#0#Chr9#0
        graph invalid: missing edge between 441017th step (320323:0) and 441018th step (877048:0) of path REF#NC_006096.5
        graph invalid: missing edge between 441018th step (877048:1) and 441017th step (320323:0) of path REF#NC_006096.5
        graph invalid: missing edge between 435304th step (877048:1) and 435303th step (320323:0) of path Asil#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 473941th step (320323:0) and 473942th step (877048:0) of path Fayoumi#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 473942th step (877048:1) and 473941th step (320323:0) of path Fayoumi#0#NC_006096.5_RagTag#0
        graph invalid: missing edge between 433174th step (320323:0) and 433175th step (877048:0) of path Tibetan#0#Chr9#0
        graph invalid: missing edge between 433175th step (877048:1) and 433174th step (320323:0) of path Tibetan#0#Chr9#0
        graph: invalid

        [2023-03-22T00:17:15+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host CAU
<=========

**Comment by ETC100** [comment]
Thanks for your help. I have solved this problem according to your suggestion. The graph genome constructed without normalization is just a little bigger than normalized one.

**Comment by jwli-code** [comment]
> Fixed the bug in GFAffix--let me know in case any further issues pop up.

I also encountered this problem, but my cactus version is 3.14.

**Comment by danydoerr** [comment]
Hi @jwli-code, can you provide me with a GFA file that produces the bug, for debugging? Also possible in private communication -> daniel dot doerr at hhu dot de

**Comment by jwli-code** [comment]
Thanks for getting back! Just a heads-up: the file is ~10 GB, so I might need an extra day to send it. If you have a preferred way to receive large files—or if there's a way I could first extract and share just the essential parts—please let me know!


1369176312
***@***.***



        



         Original
         
       
From:Daniel Doerr ***@***.***&gt;
Sent Time:Apr 15, 2026 15:55
To:ComparativeGenomicsToolkit/cactus ***@***.***&gt;
Cc:jwli ***@***.***&gt;, Mention ***@***.***&gt;
Subject:Re: [ComparativeGenomicsToolkit/cactus] cactus-graphmap-join error in vg validate step (Issue #971)



danydoerr left a comment (ComparativeGenomicsToolkit/cactus#971)

Hi @jwli-code, can you provide me with a GFA file that produces the bug, for debugging? Also possible in private communication -&gt; daniel dot doerr at hhu dot de

**Comment by jwli-code** [comment]
> 你好[@jwli-code](https://github.com/jwli-code)您能否提供一个能重现此错误的 GFA 文件，以便我进行调试？也可以私下联系我 -> daniel dot doerr at hhu dot de
@danydoerr @glennhickey 
Hi there,

I'm encountering an issue with the HAL and VG files generated for A06. I've uploaded the problematic files here: [🔗 paste download link]

Could you please take a look and advise on how to resolve or work around this error? I've also included the relevant error log and environment details below. Thanks in advance for your help! https://drive.google.com/file/d/1KpMEsvMz9RFr-v--RNg7r859iwt8sarO/view?usp=sharing

**Comment by jwli-code** [comment]
I'm encountering an issue with the HAL and VG files generated for A06. I've uploaded the problematic files here: [🔗 paste download link]

Could you please take a look and advise on how to resolve or work around this error? I've also included the relevant error log and environment details below. Thanks in advance for your help! https://drive.google.com/file/d/1KpMEsvMz9RFr-v--RNg7r859iwt8sarO/view?usp=sharing






1369176312
***@***.***



        



         Original
         
       
From:Daniel Doerr ***@***.***&gt;
Sent Time:Apr 15, 2026 15:55
To:ComparativeGenomicsToolkit/cactus ***@***.***&gt;
Cc:jwli ***@***.***&gt;, Mention ***@***.***&gt;
Subject:Re: [ComparativeGenomicsToolkit/cactus] cactus-graphmap-join error in vg validate step (Issue #971)



danydoerr left a comment (ComparativeGenomicsToolkit/cactus#971)

Hi @jwli-code, can you provide me with a GFA file that produces the bug, for debugging? Also possible in private communication -&gt; daniel dot doerr at hhu dot de

**Comment by danydoerr** [comment]
I'll look at the issue as soon as I have time.

**Comment by danydoerr** [comment]
I found the bug and pushed a new release that fixes it. @jwli-code Thanks for sharing your graph, that was helpful. @glennhickey can you please update your workflow to the new version? Thanks! 

https://github.com/codialab/GFAffix/releases/tag/0.2.2

**Comment by jwli-code** [comment]
Thank you so much for your help. My data ran successfully using the new software version.
